### ISSUE TITLE
 Process for reviewing and approving before posting any official content.

### ISSUE THREAD

**Issue by shaheerwasti** [thenewboston-developers/Marketing#10]
https://thenewboston.slack.com/archives/C07PJ5ETS/p1607482572352900

https://thenewboston.slack.com/files/U01F9P6RV9U/F01H628UTEU/screenshot_20201208-185519_discord.jpg

https://thenewboston.slack.com/archives/C07PJ5ETS/p1607482607353800

**Comment by heykulthe** [comment]
@shaheerwasti Can you please tell me your directly here? I guess the message you gave in the URL has surpassed the 10k messaging limit.
