### ISSUE TITLE
Promote TNB Faucet

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#115]
Share/promote the new TNB faucet on social media. Here is Skys announcement post for context:

> Me and @Bucky have started a Faucet https://tnbfaucet.com that will help bring in new users into the community and help spread word about thenewboston blockchain. We feel putting more coins in the hands of people in the long run will have more people talking about the chain because they have some of the coins in a wallet.
> This will also give the marketing team anonymous data about who the people we are targeting and can target come beta launch and full release.

https://tnbfaucet.com/

**Comment by Chrisha1212** [comment]
This is Great :) Hey @SOHDA31 can you make an infographic promoting this?

**Comment by SOHDA31** [comment]
![tnbcfaucet](https://user-images.githubusercontent.com/74038568/110739107-88de4b00-8256-11eb-8ce7-7b5b07ad9a30.png)
[tnbcfaucet.zip](https://github.com/thenewboston-developers/Marketing/files/6120578/tnbcfaucet.zip)

**Comment by Prawesh-MAGNETIC** [comment]
Can I create a TNB Faucet post.???

**Comment by tspearing** [comment]
> Can I create a TNB Faucet post.???

@Prawesh-MAGNETIC , where are you referring to?

**Comment by Prawesh-MAGNETIC** [comment]
![TNB FAUCET](https://user-images.githubusercontent.com/71756108/113663173-35311700-96c7-11eb-9745-a078acfd1761.png)

TNB Faucet Promotion!
A/c:  b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd
