### ISSUE TITLE
Make  GIF's for Social Media Stories

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#117]
**You will make GIFs about ff,**

**Rules**
Make sure to avoid typos.
GIFs should be 5-10 seconds.
Always include thenewboston logo at the end.
Submit work before Friday.

This task may include
- Daily updates about thenewboston
- Announcements [if any]
- Promotions
- Cool things going on in our community

1. Did you know that there are [# of people who earn coins] people now earning coins through their own talent and skills?
2. How to join our community [thenewboston.com]
3. How to submit proposals [https://github.com/thenewboston-developers/Project-Proposals/issues]
4. How to earn coins [Visit thenewboston.com and join us on slack to introduce yourself and showcase your talent]
5. What it's like to be on our team [Investing coins/cryptocurrency without needing to pay for it. All you have to do is showcase the talent/skills that you have]
6. Advantages of joining our community [Getting to know people around the world while earning and learning]

**Comment by BenCooler** [comment]
edited
