### ISSUE TITLE
Infographic Social Media Polls #99

### ISSUE THREAD

**Issue by Mathlucklala** [thenewboston-developers/Marketing#119]
1.	Have you heard about cryptocurrency?

•	Yes 
•	No

2.	Are you aware of cryptocurrencies other than Bitcoin, Ethereum, Litecoin, and Binance?

•	Yes 
•	No

3.	If you answered "yes" to Q2, list four of them apart from the ones mentioned above.

•	One - 
•	Two -  
•	Three -
•	Four –

4.	Have you invested in any cryptocurrency?

•	Yes
•	No

5.	How likely are you to invest in a new cryptocurrency?

•	Very Likely
•	Somewhat likely
•	Not so likely
•	Not at all likely

6.	Have you heard about thenewboston coin (TNBC)?

•	Yes 
•	No

7.	If you answered "yes" to Q6, do you own TNBC?

•	Yes
•	No

8.	What is your nationality and which country do you live in?

•	Nationality –
•	Country –

9.	Which cryptocurrencies do you think are safer to invest in?

•	Older ones (More than 5 years old)
•	Newer ones (Less than 1 year old) 

10.	Do you agree with the following statement? "Cryptocurrencies differ in transaction speed (average time it takes to complete a transaction)."

•	Yes
•	No

**Comment by BenCooler** [comment]
edited

**Comment by Chrisha1212** [comment]
@SOHDA31 assigned you this task no need to make infographic for question answerable by yes or no.

**Comment by swaiba43** [comment]
1.Have you heard about cryptocurrency?
• Yes

Are you aware of cryptocurrencies other than Bitcoin, Ethereum, Litecoin, and Binance?
• Yes

If you answered "yes" to Q2, list four of them apart from the ones mentioned above.
• TNBCoin
• Petro
• Cardano
• Stellar

Have you invested in any cryptocurrency?
• Yes

How likely are you to invest in a new cryptocurrency?
• Very Likely

Have you heard about thenewboston coin (TNBC)?
• Yes

If you answered "yes" to Q6, do you own TNBC?
• Yes

What is your nationality and which country do you live in?
• Nationality – Tanzanian
• Country – Tanzania

Which cryptocurrencies do you think are safer to invest in?
• Newer ones (Less than 1 year old)

Do you agree with the following statement? "Cryptocurrencies differ in transaction speed (average time it takes to complete a transaction)."
• Yes
