### ISSUE TITLE
memes about TNBC

### ISSUE THREAD

**Issue by Ayah206** [thenewboston-developers/Marketing#120]
![20210309_224911](https://user-images.githubusercontent.com/53304347/110620455-51f62f80-8199-11eb-910c-11034870c1c2.jpg)

![20210309_223334](https://user-images.githubusercontent.com/53304347/110620458-53275c80-8199-11eb-8fc1-78bb762194ad.jpg)

![20210310_004854](https://user-images.githubusercontent.com/53304347/110620436-4acf2180-8199-11eb-88cc-337c1bfdd1c2.jpg)

My account number :
9e40414427477a3b75fbf2174553b1aa548c3f4e5ff4acbb125aa26f20081821

**Comment by Prawesh-MAGNETIC** [comment]
![avg blocktime](https://user-images.githubusercontent.com/71756108/111152791-24552000-85b7-11eb-8fe6-d1de8ad693be.png)


561c44e5b11429371511b1976122b013fb05d14aacebbe600fd4cec529113eec
My Account No.
