### ISSUE TITLE
Social Media Polls (LinkedIn)

### ISSUE THREAD

**Issue by NodeSpice** [thenewboston-developers/Marketing#121]
Cryptocurrency is quite new and not many people are aware of it yet. It also takes time for the average person to learn how to invest in it. Would this deter you from using cryptocurrency? 
Yes
No

Cryptocurrency has no tangible form. Does that diminish the value you perceive about the currency?
Yes
No

Unlike other currencies, cryptocurrency requires a lot less fees to operate. Would this increase your interest in using cryptocurrency?
Yes
No

If cryptocurrency providers created tangible coins (or notes) for cryptocurrency users with banks and ATMs readily available, but remained non-government regulated, would this increase your interest in cryptocurrency?
Yes
No

Have you used bitcoin or any other forms of cryptocurrency to purchase goods?
Yes
No

In what year were you born? 
(2001–present)
(1981–2000)
(1965 –1980)
(1946 –1964)
(1927 –1945)

What is your income level?
$0–$20,000
$20,000–$50,000
$50,000–$100,000
+$100,000

**Comment by Chrisha1212** [comment]
@Toledit can you make an infographic for this? No need to make an infographic for questions that are answered by yes or no.

**Comment by BenCooler** [comment]
edited

**Comment by Toledit** [comment]
Alright is it for instagram stories?

**Comment by Chrisha1212** [comment]
> Alright is it for instagram stories?

those questions that are answerable by yes or no will be in stories that are not will be posted to all social media account. so no need to make an infographic for those questions that answerable by yes or no.

**Comment by Toledit** [comment]
Ok. I was asking to determine the aspect ratio of the designs

**Comment by Toledit** [comment]
![Age](https://user-images.githubusercontent.com/27518021/111004012-3fe2df80-8399-11eb-991b-712b9226447c.jpg)
![income](https://user-images.githubusercontent.com/27518021/111004017-42453980-8399-11eb-9571-4b84bd127009.jpg)

**Comment by Toledit** [comment]
This hasn't been paid no? Was assigned by @Chrisha1212. Not sure if she used them though, so no big deal...
