### ISSUE TITLE
Promotional post for saturday.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#122]
Do you have some ideas in your head and want to contribute to thenewboston, but don't know where to start? Here is a video
just for you. 

Join us now and get rewarded! 

#thenewboston

**Comment by Chrisha1212** [comment]
https://drive.google.com/drive/u/0/folders/1Fq3WhV_C59aqeGAFh_fE3vYQrAogEvMI

**Comment by BenCooler** [comment]
edited
