### ISSUE TITLE
Proof of work week 2 march

### ISSUE THREAD

**Issue by johnson-nnaemeka** [thenewboston-developers/Marketing#123]

**Comment by johnson-nnaemeka** [comment]
Proof of work march week 2

![My Post (4)](https://user-images.githubusercontent.com/79226942/110783830-38241d80-8269-11eb-981d-d3f68b2eae5d.jpg)
![My Post (3)](https://user-images.githubusercontent.com/79226942/110783843-3b1f0e00-8269-11eb-8ed5-8b7716b6adc1.jpg)
![KISS MY ASS](https://user-images.githubusercontent.com/79226942/110855222-5e23df00-82b6-11eb-8281-7efdd6a963b5.jpg)

**Comment by johnson-nnaemeka** [comment]
there are three memes

https://user-images.githubusercontent.com/79226942/110958173-b4436180-834c-11eb-87c1-1699053e3002.mp4

**Comment by johnson-nnaemeka** [comment]
![My Post (3)](https://user-images.githubusercontent.com/79226942/110958221-c58c6e00-834c-11eb-9974-d206d1750f3e.jpg)

**Comment by johnson-nnaemeka** [comment]
![KISS MY ASS](https://user-images.githubusercontent.com/79226942/110958312-ddfc8880-834c-11eb-83ce-89b15c2766b0.jpg)

**Comment by kristykjlee** [comment]
@johnson-nnaemeka Account number?

**Comment by johnson-nnaemeka** [comment]
> @johnson-nnaemeka Account number?

c82745b716430050a130094a84d0518149fcf03d5b63c34f5f29f06b50836348
