### ISSUE TITLE
Make a Video for app awareness.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#124]
Make a quick video showing how to use thenewboston app.

**Comment by Chrisha1212** [comment]
Wondering how fast thenewboston app can get just to send a coins? Here the Video of Hussu https://www.youtube.com/watch?v=U9Z5bnBTKzw

**Comment by hussu010** [comment]
My Account Number: 22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a
