### ISSUE TITLE
week 5 memes (contains 15)

### ISSUE THREAD

**Issue by kizzi789** [thenewboston-developers/Marketing#125]
Account number:  1ddde4c124a46e71c3777eaa5fd1ba4e2e67cefa2a868ecacb95c2797ea4545c
Google drive link for all contents: https://drive.google.com/drive/folders/1EMN4guom9bmYUozsbdnuX5r5k2mHzYDw?usp=sharing

![1](https://user-images.githubusercontent.com/78949557/110948621-ad771780-8369-11eb-900c-4db11bdfcbd8.jpg)
![2](https://user-images.githubusercontent.com/78949557/110948632-b10a9e80-8369-11eb-9e84-8fc86ac272aa.jpg)
![3](https://user-images.githubusercontent.com/78949557/110948636-b36cf880-8369-11eb-860d-455c56fd4da3.png)
![4](https://user-images.githubusercontent.com/78949557/110948639-b536bc00-8369-11eb-9109-73e2e6cd47e3.png)

https://user-images.githubusercontent.com/78949557/110948644-b667e900-8369-11eb-9619-bd47aa2c3d66.mp4

![6](https://user-images.githubusercontent.com/78949557/110948651-b8ca4300-8369-11eb-88e6-57d08144db32.png)
![7](https://user-images.githubusercontent.com/78949557/110948659-bcf66080-8369-11eb-8121-373b8dfc91ac.png)
![8](https://user-images.githubusercontent.com/78949557/110948679-c1bb1480-8369-11eb-93d1-ad1e57ec3d5e.png)
![9](https://user-images.githubusercontent.com/78949557/110948726-cc75a980-8369-11eb-92eb-482c8b7f9771.png)
![10](https://user-images.githubusercontent.com/78949557/110948790-e1523d00-8369-11eb-803a-10280273ac99.png)
![11](https://user-images.githubusercontent.com/78949557/110948813-eadba500-8369-11eb-8c08-0be6be091c33.png)
![12](https://user-images.githubusercontent.com/78949557/110948834-f0d18600-8369-11eb-80db-05ce5b5e125e.png)
![13](https://user-images.githubusercontent.com/78949557/110948863-f9c25780-8369-11eb-93e4-e76d42536e06.png)
![14](https://user-images.githubusercontent.com/78949557/110948884-0050cf00-836a-11eb-9170-2dcc96393c98.png)
![15](https://user-images.githubusercontent.com/78949557/110948887-0181fc00-836a-11eb-8778-d1e6bba30e32.png)

**Comment by Prawesh-MAGNETIC** [comment]
![thenewboston](https://user-images.githubusercontent.com/71756108/111153013-68e0bb80-85b7-11eb-87a1-622f59bde94a.png)


b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd
My A/c Number
