### ISSUE TITLE
Memes for TBNC 

### ISSUE THREAD

**Issue by shalombrain** [thenewboston-developers/Marketing#132]
![untitled-4n](https://user-images.githubusercontent.com/20520142/111067687-a9f8a300-84c5-11eb-9503-964f3800fc13.jpg)
![untitled-jhkj](https://user-images.githubusercontent.com/20520142/111067697-b1b84780-84c5-11eb-9f6b-dc0739408f09.png)

https://user-images.githubusercontent.com/20520142/111067704-b977ec00-84c5-11eb-867d-5cb24cdb39ce.mp4

![final_6046538bba46bb00702160a8_643790](https://user-images.githubusercontent.com/20520142/111067713-bf6dcd00-84c5-11eb-8aa8-172ad05d5d78.png)

https://user-images.githubusercontent.com/20520142/111067719-c563ae00-84c5-11eb-9e1e-f31c8434aa3a.mp4

https://user-images.githubusercontent.com/20520142/111067726-cb598f00-84c5-11eb-8f07-6a5038d8cc27.mp4

![when_the_tnbc_paycheck_hits](https://user-images.githubusercontent.com/20520142/111067732-d1e80680-84c5-11eb-90c1-270de196ec17.png)
![tnbc](https://user-images.githubusercontent.com/20520142/111067735-d7dde780-84c5-11eb-9e7c-c0d1a46b38a1.png)

51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by shalombrain** [comment]
Hi @Chrisha1212 @kristykjlee I think the wrong payment label was added to this

It's supposed to be 1000 for each of the memes not 1000 for the entirety of the memes

**Comment by kristykjlee** [comment]
Hi @shalombrain, yeah looks like the wrong payment was added, so the prices were updated to 250 per meme last week, so I will give you an extra 1000 since I already paid you 1000. So then you will have received 2000 total.
