### ISSUE TITLE
Week 8 - Social Media Graphics

### ISSUE THREAD

**Issue by tspearing** [thenewboston-developers/Marketing#133]
**Monday**
The ownership of any asset can be tracked through non-fungible tokens. Learn more at thenewboston blog.

**Tuesday**
CryptoKitties are blockchain based virtual pets which are bred, collected, and sold for real world goods.

**Wednesday**
Non-fungible tokens represent unique digital assets which are recorded on a blockchain. Musician Grimes recently sold an art collection for almost $6 million using NFTs!

**Thursday**
The NBA is getting involved with non-fungible tokens. Top Shot lets collectors own moments in NBA history with varying levels of rarity. It's still in beta and over 2 million transactions have already taken place.

**Friday**
Gaming is incorporating the blockchain! Axie Infinity is a game with virtual land where 9 plots of land have recently sold for $1.5 Million USD!

**Comment by BenCooler** [comment]
edited
