### ISSUE TITLE
Non-fungible Tokens

### ISSUE THREAD

**Issue by tspearing** [thenewboston-developers/Marketing#134]
[Non-fungible Tokens.docx](https://github.com/thenewboston-developers/Marketing/files/6137463/Non-fungible.Tokens.docx)

**Comment by BenCooler** [comment]
edited
[Non-fungible.Tokens-edited.docx](https://github.com/thenewboston-developers/Marketing/files/6138477/Non-fungible.Tokens-edited.docx)

**Comment by tawanike** [comment]
Hi guys, kindly asking for whoever is going to be paid for the work to have the issue assigned to them, and also please kindly add the number of coins to be paid out.
