### ISSUE TITLE
Week 1 Content for Daily Stories

### ISSUE THREAD

**Issue by BagyPo** [thenewboston-developers/Marketing#135]
**Monday**
Did you know that there are people earning coins using their talents and knowledge, while at the same time improving their skills?

**Tuesday**
Are you a student that wants to learn and earn? Come join us in our community.
thenewboston.com

**Wednesday**
If you want to be part of the community, visit thenewboston.com/social for our social media info. Join us on Slack and introduce yourself in the #Intro channel.

**Thursday**
Did you know that there are more than 40 groups on Slack? All you have to do is to find the right project for yourself and start earning.

**Friday**
There are more than 3000+ people in thenewboston community. You can collaborate with many people, meet people from all over the world, and more importantly, gain experience and earn coins.

**Saturday**
Did you know you can invest in our cryptocurrency as well as work for coins?

**Sunday**
Explore ways to get involved, earn coins, and stay up-to-date with the latest announcements and events. Follow us on our Social Media.

**Comment by BenCooler** [comment]
@BagyPo 

Can you clarify or rephrase this sentence for Wednesday:
 "If you are talented and find yourself in a certain area..."

It's not clear what "find yourself in a certain area" means. Thanks!

**Comment by BenCooler** [comment]
edited
