### ISSUE TITLE
meme-contains 3

### ISSUE THREAD

**Issue by Prawesh-MAGNETIC** [thenewboston-developers/Marketing#137]
![avg blocktime](https://user-images.githubusercontent.com/71756108/111155555-9b3fe800-85ba-11eb-8a21-ca107a722a15.png)
![thenewboston](https://user-images.githubusercontent.com/71756108/111155558-9da24200-85ba-11eb-93fe-f72cb59d9dbf.png)
<img width="1191" alt="crypto" src="https://user-images.githubusercontent.com/71756108/111155561-9e3ad880-85ba-11eb-9470-651b33edc220.png">

My Account No.  b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by kristykjlee** [comment]
@Prawesh-MAGNETIC Per community feedback, we are no longer giving payments for memes.

**Comment by Prawesh-MAGNETIC** [comment]
@kristykjlee Acknowledged, Thank you!
