### ISSUE TITLE
In need of 1004 TNBC for giveraway

### ISSUE THREAD

**Issue by Francaolisa** [thenewboston-developers/Marketing#139]
We will be doing giveaways on Twitter and Instagram tomorrow Wednesday. One person will be picked randomly every week on each platform to win 500 TNBC. Winners will be announced every 24hrs.

Account Address: 
b17034fe3625d69148f5ed001e5d82a22276772d9782b918aed6dbaf771c4d19

note: Pls add 4 TNBC

**Comment by hussu010** [comment]
heey @kristykjlee I think the reward is too high for a random person. In tnbfaucet.com, we're giving away only 50 coins and they are filling a form and creating a tweet that promotes thenewboston. Rather than 500 per person, why don't we host giveaways more often with lesser rewards?

**Comment by kristykjlee** [comment]
@dhakal0kushal I 100% agree with this.
