### ISSUE TITLE
Create Crypto Glossary

### ISSUE THREAD

**Issue by tspearing** [thenewboston-developers/Marketing#142]
Create a glossary of generic crypto terms which will go on thenewboston.com.

**Comment by tspearing** [comment]
Send and assigned to Muhammad for technical review.

**Comment by bart-jay** [comment]
Can I join this project?

**Comment by tspearing** [comment]
https://docs.google.com/document/d/1ZAPOvIAimOhtZJQ1hvjsy1VYYQLC9zc7-KSdmqqN-GE/edit

Ready for deployment. 

@kristykjlee, I shared a version with you a few minutes ago that was from MyDrive. Please ignore that as the version linked above is saved in the thenewboston/marketing.

**Comment by buckyroberts** [comment]
Closing in favor of https://github.com/thenewboston-developers/Management/issues/193
