### ISSUE TITLE
Create FAQ's for website

### ISSUE THREAD

**Issue by tspearing** [thenewboston-developers/Marketing#144]
Create FAQ's for the core website.

**Comment by tspearing** [comment]
https://docs.google.com/document/d/12DzwJnge7LaVabgtnkIjM9fpuVp1fNS4KdVsndiU4uc/edit

@kristykjlee, done and ready for deployment. The red questions are the "top questions" which can will be the ones shown to on the first page. They also belong with their categories.

**Comment by buckyroberts** [comment]
https://github.com/thenewboston-developers/Website/issues/1779
