### ISSUE TITLE
Change thenewboston.com social media links

### ISSUE THREAD

**Issue by tspearing** [thenewboston-developers/Marketing#146]
On https://thenewboston.com/social change the following social media links:

Instagram: https://www.instagram.com/thenewbostoncoin/

Facebook: https://www.facebook.com/thenewbostoncoin/

LinkedIn: https://www.linkedin.com/company/thenewbostoncoin/

**Comment by thesanjeevsharma** [comment]
@tspearing Done!

**Comment by tspearing** [comment]
@thesanjeevsharma, I'm new to github (usually use Jira) but I'm assuming the results won't show on the site until there's a pull request?

**Comment by thesanjeevsharma** [comment]
@tspearing 
So, this was the PR that got merged in:
https://github.com/thenewboston-developers/Website/pull/1672

Once a PR gets merged into `development` branch. It can be marked done. Changes will go live when Bucky re-deploys the website with the latest changes.
