### ISSUE TITLE
Landing Page Content Iteration

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#148]
@tspearing Hey Tristan, can you update the body text for the images below?
 Titles are all good to go. 

![Screen Shot 2021-04-10 at 10 14 07 PM](https://user-images.githubusercontent.com/68207101/114328589-eeda1e80-9af1-11eb-86e8-a9a9de57d6f5.png)
![Screen Shot 2021-04-10 at 10 14 09 PM](https://user-images.githubusercontent.com/68207101/114328590-ef72b500-9af1-11eb-8fba-14689c8e1c5a.png)

**Comment by tspearing** [comment]
**Low Fees**
Our infrastructure incentivizes low network fees which creates endless development possibilities.

**The value comes from you**
Coins are minted when utility is added to the platform through DApp creation or contributions. This Proof of Value system gives everyone a chance to participate, not just coin or hardware owners.
