### ISSUE TITLE
Graphic for TNB Faucet

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#159]
**Task**
Create a square graphic to promote the TNB Faucet. Must include a call to action instructing them to visit the faucet website at https://tnbfaucet.com/

For the call to action, any phrasing is fine (visit, head over to, check out, etc...)

**Background**
TNB Faucet is a website that distributes small amounts of coins (our digital currency) to users for tweeting and then completing a survey.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

---

**Previous examples:**

![faucet0](https://user-images.githubusercontent.com/8547538/117751797-8fdbf800-b1ca-11eb-8046-63d1ba169aa6.png)

![faucet1](https://user-images.githubusercontent.com/8547538/117751793-8f436180-b1ca-11eb-9a76-5d1233683a1b.jpeg)

**Comment by stoimenov00** [comment]
![tnbfaucet1](https://user-images.githubusercontent.com/78659181/118067302-902dec00-b3a0-11eb-9d02-4ce3bcde116d.png)



My Account Number
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Prawesh-MAGNETIC** [comment]
![Experience the speed With TNBC](https://user-images.githubusercontent.com/71756108/118066495-75697080-b3bc-11eb-84cd-558a3b297124.png)

My Account Number:
b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Prawesh-MAGNETIC 
Amount: 1,000
