### ISSUE TITLE
Graphic for Mobile App

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#160]
**Task**
Create a graphic that we will be used across our various social media sites to promote our upcoming mobile app. This app is currently under development, so we will need to convey this information by stating "Coming Soon" or something along those lines (just so they know it's not ready to download yet).

**Background**
This mobile app will be used for our digital currency called "coins". The symbol for our coins is TNBC. On the mobile app you will be able to manage your accounts, add friends, and send coins.

**Figma Link (for screenshots)**
https://www.figma.com/file/h6f3frXkqhEegiHdmQFhRR/Cryptocurrency-App?node-id=0%3A1

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by MusabIlhan** [comment]
Can i take this one?

**Comment by buckyroberts** [comment]
@Musabii yep!

**Comment by MusabIlhan** [comment]
![Connect to the network](https://user-images.githubusercontent.com/60546157/118026549-918ff200-b369-11eb-8b45-6b7ef2411c50.png)
<img width="1080" alt="Connect to the network" src="https://user-images.githubusercontent.com/60546157/118026691-c2702700-b369-11eb-82ae-255f0ff63fcf.png">

account:
40e778329f4d75ced4ea412f7acd0634b2c44d355bf2d479a054c9b5a44b5432

**Comment by stoimenov00** [comment]
![MobileApp post1](https://user-images.githubusercontent.com/78659181/118053181-518a3880-b384-11eb-9148-64615715cd4b.png)



My Account Number
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Prawesh-MAGNETIC** [comment]
![TNBC Mobile app Coming Soon](https://user-images.githubusercontent.com/71756108/118082773-62b26400-b3db-11eb-81a5-54c56b3d8592.png)


b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by ThejeshBommisetty** [comment]
![TNBC coming soon-v1 0](https://user-images.githubusercontent.com/47267710/118402524-de383d80-b687-11eb-9cca-6f4d5dd3db7c.jpg)


adf0b5529eb8dc52ff636f1fd8c43d1d59e077a88def0014476a03d6cd301e26

**Comment by Toledit** [comment]
![app design](https://user-images.githubusercontent.com/27518021/119155261-a94b3280-ba5b-11eb-9145-ee77f285c23b.jpg)
animation video:
https://user-images.githubusercontent.com/27518021/119155383-ce3fa580-ba5b-11eb-8e81-c1ebf83b2b56.mp4

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Prawesh-MAGNETIC 
Amount: 1,000

---

User: @ThejeshBommisetty 
Amount: 1,000

---

User: @Toledit 
Amount: 1,000
