### ISSUE TITLE
Retro / Vintage Advertisement Graphic

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#162]
**Task**
Create a retro / vintage advertisement for social media for our new cryptocurrency. Some good keywords and phrases to include are:
- thenewboston
- digital currency
- TNBC
- coins
- We're building a better economy
- The value comes from you
- Low fees
- Blazing fast
- Community built

**Background**
We are an open source development community and we are building our own cryptocurrency called "coins". Contributors are able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

---

**Examples / Inspiration**

![1222](https://user-images.githubusercontent.com/8547538/118074004-f9423f00-b361-11eb-8122-699aba9eee2e.jpeg)

**Comment by mollykn** [comment]
Hey Bucky, I'll work on this tonight

**Comment by buckyroberts** [comment]
@mollykn alright, sounds good!

**Comment by Prawesh-MAGNETIC** [comment]
![TV Ad](https://user-images.githubusercontent.com/71756108/118078868-a35aaf00-b3d4-11eb-8d79-b22dc17ab79e.png)



b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by SOHDA31** [comment]
![tnb](https://user-images.githubusercontent.com/74038568/118770616-2bdac300-b89f-11eb-8e0d-7573fcd370a3.png)
Account Number:5257c00dc543a348f3aee0c7871d7e659d4ec63b68838302f3f4da978e13c92a

**Comment by Toledit** [comment]
![vintage](https://user-images.githubusercontent.com/27518021/119207196-1aafd300-baa6-11eb-8bf1-4947dcbfc973.jpg)
![vintage1](https://user-images.githubusercontent.com/27518021/119207229-2ef3d000-baa6-11eb-8d9a-febcd77d9e93.jpg)

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Prawesh-MAGNETIC 
Amount: 1,000

---

User: @SOHDA31 
Amount: 1,000

---

User: @Toledit 
Amount: 2,000
