### ISSUE TITLE
Graphic for 3 Ways to Earn TNBC

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#165]
**Task**
Create a graphic to inform users about the 3 ways they can earn TNBC:
- Tasks / bounties
- Jobs (on the core team)
- Projects / building apps

**Image Specs**
Size: 1080px wide minimum (whichever height works best)
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

---

**Examples / Inspiration** 

![three1](https://user-images.githubusercontent.com/8547538/118073206-3f969e80-b360-11eb-9477-c3997411dcf3.png)
![three2](https://user-images.githubusercontent.com/8547538/118073209-40c7cb80-b360-11eb-864a-db07da2dc2fa.png)
![three3](https://user-images.githubusercontent.com/8547538/118073212-41606200-b360-11eb-8e5f-eb2762ab8326.png)
![three4](https://user-images.githubusercontent.com/8547538/118073215-41f8f880-b360-11eb-90fc-a4466ca7685c.png)

**Comment by stoimenov00** [comment]
Hey Bucky, can I take this one?

**Comment by buckyroberts** [comment]
@stoimenov00 yep!

**Comment by Chrisha1212** [comment]
> Hey Bucky, can I take this one?

@stoimenov00  Are you still working on this one?

**Comment by ThejeshBommisetty** [comment]
I would lik to take this one

**Comment by ThejeshBommisetty** [comment]
![3 ways to earn TNBC](https://user-images.githubusercontent.com/47267710/123553238-a8fb3100-d797-11eb-9798-ae4ef8394ba1.jpg)

Account Number : adf0b5529eb8dc52ff636f1fd8c43d1d59e077a88def0014476a03d6cd301e26

hey Bucky, I can add any description as well if u provide.

**Comment by clarkycode** [comment]
Is this task still open?

Here's an output though

Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![3 Ways to Earn](https://user-images.githubusercontent.com/76585195/123662896-753c0c00-d868-11eb-8fcc-d7c182ae5859.png)

Background Photo by <a href="https://unsplash.com/@blueskin?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Terry</a> on <a href="https://unsplash.com/s/photos/blockchain?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>

**Comment by Chrisha1212** [comment]
@clarkycode -800
