### ISSUE TITLE
Earn Coins Graphic

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#166]
**Task**
Create a graphic letting people know that they can earn coins by:

- Completing tasks
- Creating/Contributing to projects
- Joining the core team

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I am working on this

**Comment by Docebo-Netflix** [comment]
I'll work on this graphic since @stoimenov00 you already completed 4 of them

**Comment by Docebo-Netflix** [comment]
![Earn-Coins-Graphic-166-05-23-2021](https://user-images.githubusercontent.com/78985665/119251868-c405d000-bb5d-11eb-9aca-2f64463b485b.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman kindly include your account number.

**Comment by Docebo-Netflix** [comment]
Hi Chrisha,
Here's my account info:
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f
Best regards, Ed 

    On Sunday, May 23, 2021, 8:20:35 PM PDT, MsChrishaph ***@***.***> wrote:  
 
 


@SwedishFisherman kindly include your account number.

**Comment by Docebo-Netflix** [comment]
Revision for Instagram
![Insta-166-Monday](https://user-images.githubusercontent.com/78985665/119322519-8aeb5f80-bc32-11eb-8784-6f9e88bc9a85.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-166-Monday](https://user-images.githubusercontent.com/78985665/119322578-99397b80-bc32-11eb-8b19-666c1ea3f4d5.png)

**Comment by Toledit** [comment]
Reddit
![reddit-166-monday](https://user-images.githubusercontent.com/27518021/119494244-c2a8f300-bd69-11eb-97fc-f5e833fdf7e5.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by stoimenov00** [comment]
> Revision for Instagram
> ![Insta-166-Monday](https://user-images.githubusercontent.com/78985665/119322519-8aeb5f80-bc32-11eb-8784-6f9e88bc9a85.png)

https://github.com/thenewboston-developers/Marketing/issues/170 this task is about Account Manager

**Comment by stoimenov00** [comment]
Facebook 
![166](https://user-images.githubusercontent.com/78659181/119398618-19fe8300-bcd8-11eb-9ee9-10bcb414b5cd.png)

![166 2](https://user-images.githubusercontent.com/78659181/119399188-e2440b00-bcd8-11eb-9f51-1feb987363cd.png)


a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Docebo-Netflix** [comment]
Revision to Twitter
![Twitter-166-Monday-v2](https://user-images.githubusercontent.com/78985665/119416790-45b64480-bca9-11eb-833f-0aac9046509f.png)

**Comment by stoimenov00** [comment]
Linkedin
![166 2](https://user-images.githubusercontent.com/78659181/119418382-2e527800-bcf8-11eb-9b9d-49fd53c7ab8a.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 2,000

---

User: @Toledit  
Amount: 1,000

---

User: @stoimenov00  
Amount: 2,000
