### ISSUE TITLE
Graphic for joining the community 

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#167]
**Task**
Create a graphic letting people know how they can join our community by visiting our website and joining our Discord

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
Linkedin
![167](https://user-images.githubusercontent.com/78659181/119246930-ec092980-bb85-11eb-8a5e-a72c62997617.png)


a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Docebo-Netflix** [comment]
Instagram
![Insta-167-Tuesday](https://user-images.githubusercontent.com/78985665/119322314-5ecfde80-bc32-11eb-9142-33dce57bad63.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-166-Tuesday](https://user-images.githubusercontent.com/78985665/119322392-727b4500-bc32-11eb-9c7d-189cc7ebeeb9.png)

**Comment by stoimenov00** [comment]
Facebook
![167](https://user-images.githubusercontent.com/78659181/119349699-b60b9880-bc9e-11eb-82c6-665e2482b6b4.png)


a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Toledit** [comment]
Reddit
![reddit-167-tuesday](https://user-images.githubusercontent.com/27518021/119361912-d5adbb80-bcb4-11eb-8f32-65d4430cb592.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by Docebo-Netflix** [comment]
Revision to Twitter. Please let me know if this works
![Twitter-166-Tuesday-v2](https://user-images.githubusercontent.com/78985665/119421591-e7db2a00-bcb3-11eb-99cc-6714fd7f436a.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 2,000

---

User: @SwedishFisherman  
Amount: 2,000

---

User: @Toledit 
Amount: 1,000
