### ISSUE TITLE
Earn Coins With Your Own App

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#168]
**Task**
A graphic telling users how they can create their own app that has integrations with thenewboston network.

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
Linkedin
![168](https://user-images.githubusercontent.com/78659181/119247026-c0d30a00-bb86-11eb-80b5-7932b8f679cf.png) 

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Docebo-Netflix** [comment]
Instagram
![Insta-168-Wednesday](https://user-images.githubusercontent.com/78985665/119325946-46fa5980-bc36-11eb-9f34-b71260f6c14f.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-167-Wednesday](https://user-images.githubusercontent.com/78985665/119326084-62fdfb00-bc36-11eb-874f-d334188992c1.png)

**Comment by stoimenov00** [comment]
Facebook
![168](https://user-images.githubusercontent.com/78659181/119395123-5da2be00-bcd3-11eb-8df7-c5c4ececa79b.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Docebo-Netflix** [comment]
Revision Twitter
![Twitter-168-Wednesday](https://user-images.githubusercontent.com/78985665/119437955-f9ccc500-bcd3-11eb-84c4-936b4b7578bc.png)

**Comment by Toledit** [comment]
Reddit
![reddit-168-wednesday](https://user-images.githubusercontent.com/27518021/119494623-2df2c500-bd6a-11eb-98ca-171dee8ed65f.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 2,000

---

User: @SwedishFisherman 
Amount: 2,000

---

User: @Toledit 
Amount: 1,000
