### ISSUE TITLE
Earning Coins by Creating Memes

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#169]
**Task**
Create a graphic telling people that they can earn coins by creating memes and submitting them in our #memes channel on Discord

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
Linkedin
![169](https://user-images.githubusercontent.com/78659181/119247034-d47e7080-bb86-11eb-87c7-39accd3c3b90.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Facebook
![169](https://user-images.githubusercontent.com/78659181/119400634-bd509780-bcda-11eb-8ee0-a6661d1836c8.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Docebo-Netflix** [comment]
Instagram
![Insta-169-Friday](https://user-images.githubusercontent.com/78985665/119437857-d144cb00-bcd3-11eb-8b78-4245fef72f6c.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-169-Friday](https://user-images.githubusercontent.com/78985665/119437888-dd308d00-bcd3-11eb-8bbe-847d5fc4f628.png)

**Comment by Toledit** [comment]
Reddit
![reddit-169-Friday](https://user-images.githubusercontent.com/27518021/119494723-4bc02a00-bd6a-11eb-91d0-37e83b2a4cfc.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 2,000

---

User: @SwedishFisherman 
Amount: 2,000

---

User: @Toledit 
Amount: 1,000
