### ISSUE TITLE
Earn TNBC Graphic

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#170]
**Task**
Graphic focused on telling people to download the account manager which is where they can store their TNBC 

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by ed72** [comment]
I can create this graphic

**Comment by stoimenov00** [comment]
Linkedin
![170](https://user-images.githubusercontent.com/78659181/119247048-ed872180-bb86-11eb-9f2f-651ec1454100.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Facebook

![170 2](https://user-images.githubusercontent.com/78659181/119410949-e7f61c80-bce9-11eb-8023-298e14c56b06.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Docebo-Netflix** [comment]
Instagram
![Insta-170-Thursday](https://user-images.githubusercontent.com/78985665/119438015-1a951a80-bcd4-11eb-9424-6df74eaf27ef.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-170-Thursday](https://user-images.githubusercontent.com/78985665/119438034-27197300-bcd4-11eb-88ed-55ac92cd797e.png)

**Comment by Toledit** [comment]
Reddit
![reddit-170-thursday](https://user-images.githubusercontent.com/27518021/119494400-f126ce00-bd69-11eb-8ece-3a9824248ab5.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 2,000

---

User: @SwedishFisherman 
Amount: 2,000

---

User: @Toledit 
Amount: 1,000
