### ISSUE TITLE
Update faucet form

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#171]
Talk with Sky to get the faucet form updated so that account number is a required field.

**Comment by hussu010** [comment]
Hi @buckyroberts I have been working on revamping tnbfaucet.com and I guess the users wont need to enter the account number twice (once in twitter post and again in google form). Here's the demo video: https://youtu.be/YkjWgE_4iaM

and here's the source code: https://github.com/hussu010/TNBFAUCET
