### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#175]
**Task**
Create a graphic showing the speed of TNB. At  3,238 transactions per second and a block time of 0.015 seconds TNBC is the fastest emerging crypto! 
(We need this for Reddit and Twitter only, that's 2 infographics!)

Due Date: 05/29/2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I will work on this issue

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter--Speed-175](https://user-images.githubusercontent.com/78985665/120053225-ed9b7d00-bfdd-11eb-9494-54542241c84d.png)

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit--Speed-175](https://user-images.githubusercontent.com/78985665/120053233-f8eea880-bfdd-11eb-8bc6-60ba003b2419.png)

**Comment by Prawesh-MAGNETIC** [comment]
![TNBC is the fastest emerging crypto!](https://user-images.githubusercontent.com/71756108/120066523-90163780-c094-11eb-86b7-08124fb2f6e9.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 1,600

---

User: @Prawesh-MAGNETIC 
Amount: 800
