### ISSUE TITLE
Phone App

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#176]
**Task**
A graphic about our mobile app where you can add friends and receive coins - has to include that the app is coming soon.
(We need this for Facebook and Twitter)

Due Date: 05/29/2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I will work on this issue

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter--App-176](https://user-images.githubusercontent.com/78985665/120089976-ce6f1f00-c0b3-11eb-823a-92bda7c5eddf.png)

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook--App-176](https://user-images.githubusercontent.com/78985665/120090056-6ff67080-c0b4-11eb-8a34-9fc51f26e205.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 1,600
