### ISSUE TITLE
Account Manager

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#177]
**Task**
An infographic about the account manager. Showing the difference between the "Bank" and your account and/or how to create your account.
(We need this for Facebook, Instagram, Reddit and Twitter)

Due Date: 05/29/2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I am working on this

**Comment by stoimenov00** [comment]
Instagram
![Instagram](https://user-images.githubusercontent.com/78659181/120089321-59bed380-c0f9-11eb-849a-d3f3e9c2937d.png)


a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Facebook
![Facebook](https://user-images.githubusercontent.com/78659181/120089364-b1f5d580-c0f9-11eb-9692-cc03a94b1644.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
![Twitter](https://user-images.githubusercontent.com/78659181/120089369-bfab5b00-c0f9-11eb-8457-2843f049d48b.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![Reddit](https://user-images.githubusercontent.com/78659181/120089408-3f392a00-c0fa-11eb-8411-2a3a910f8905.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
![Twitter](https://user-images.githubusercontent.com/78659181/120089382-f41f1700-c0f9-11eb-94e2-653db2908912.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Facebook

![Facebook](https://user-images.githubusercontent.com/78659181/120171726-a17d5200-c202-11eb-96c6-314afbfe8c55.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
![Twitter (2)](https://user-images.githubusercontent.com/78659181/120171864-c40f6b00-c202-11eb-872c-0a7f584320eb.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![reddit](https://user-images.githubusercontent.com/78659181/120171918-d4bfe100-c202-11eb-8cec-2846242b6bf1.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
![Instagram](https://user-images.githubusercontent.com/78659181/120171989-e43f2a00-c202-11eb-8407-ab6f828077d6.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
For better quality
https://we.tl/t-RhiNZRpzPC

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 3,200
