### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#178]
**Task**
A graphic telling people to download the account manager from our website.
(Twitter only)

Due date: 05/29/2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![Download the TNB account manager](https://user-images.githubusercontent.com/71756108/120023266-2e5dbb00-c00b-11eb-9e03-ac7ad7047c32.png)





A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by Toledit** [comment]
![twitter-178 3](https://user-images.githubusercontent.com/27518021/120217713-6e0de800-c241-11eb-95f2-d42d6114c82e.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by Prawesh-MAGNETIC** [comment]
![AccountManager](https://user-images.githubusercontent.com/71756108/120185308-a4db0280-c22f-11eb-85f6-72c702e26da5.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Toledit 
Amount: 800

---

User: @Prawesh-MAGNETIC  
Amount: 800
