### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#179]
**Task**
Graphic reaching to all the people who are interested in crypto and want to own a cryptocurrency 
(This is mostly targeting people who don't own crypto and TNB being their first)
(Twitter only)

Due Date: 05/29/2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
![twitter-179 landscape2](https://user-images.githubusercontent.com/27518021/120064696-3b63c400-c076-11eb-8fae-f74494f479f3.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Toledit 
Amount: 800
