### ISSUE TITLE
Join us

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#180]
**Task**
A graphic inviting people to join us in the Discord
(LinkedIn only)

Due Date: 05/29/2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![Join thenewboston Discord](https://user-images.githubusercontent.com/71756108/120031869-0411fa80-c017-11eb-8e00-dd07cd7bd05b.png)



A/c: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by Toledit** [comment]
![Linkdn-180](https://user-images.githubusercontent.com/27518021/120067473-766cf400-c084-11eb-8126-0e6d21ca05ac.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Prawesh-MAGNETIC 
Amount: 800

---

User: @Toledit  
Amount: 800
