### ISSUE TITLE
Earn TNBCoins

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#181]
**Task**
A graphic telling designers that they can earn coins through making infographics.
(LinkedIn only)

Due date: 05/29/2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
![Linkdn-181](https://user-images.githubusercontent.com/27518021/120066764-ab774780-c080-11eb-958d-0b570db22a34.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Toledit 
Amount: 800
