### ISSUE TITLE
Playlist Thumbnail for "React JS for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#182]
**Task**
Create a thumbnail graphic for the "React JS for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/tmUBqSY.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stoimenov00** [comment]
![react](https://user-images.githubusercontent.com/78659181/120049359-fdd14d80-c019-11eb-81b9-89d876586cf6.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 400
