### ISSUE TITLE
Playlist Thumbnail for "React JS / Redux for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#183]
**Task**
Create a thumbnail graphic for the "React JS / Redux for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Docebo-Netflix** [comment]
![Thumbnail_React_Redux](https://user-images.githubusercontent.com/78985665/120090340-830a4000-c0b6-11eb-8ea1-28033d6c92fe.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman  
Amount: 400
