### ISSUE TITLE
Playlist Thumbnail for "Bootstrap for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#184]
**Task**
Create a thumbnail graphic for the "Bootstrap for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stoimenov00** [comment]
![bootstrap](https://user-images.githubusercontent.com/78659181/120052500-ec8e3e00-c025-11eb-9c0d-387a221d655d.png)

![bootstrap (1)](https://user-images.githubusercontent.com/78659181/120052630-73dbb180-c026-11eb-8268-d09e1b5dc0c3.png)


a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 400

**Comment by buckyroberts** [comment]
@stoimenov00 can I get these in jpg? For some reason the pngs aren't working :-/
