### ISSUE TITLE
Playlist Thumbnail for "Less CSS for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#185]
**Task**
Create a thumbnail graphic for the "Less CSS for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by SwedishFisherman** [comment]
![Uploading Thumbnail_Less_CSS_185.png…]()

**Comment by Docebo-Netflix** [comment]
![Thumbnail_Less_CSS_185](https://user-images.githubusercontent.com/78985665/120090627-dda49b80-c0b8-11eb-83b7-9fa8e9364036.png)

**Comment by buckyroberts** [comment]
@SwedishFisherman beautiful

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 400
