### ISSUE TITLE
Playlist Thumbnail for "Grunt JS for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#186]
**Task**
Create a thumbnail graphic for the "Grunt JS for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Docebo-Netflix** [comment]
![Thumbnail_GRUNT_186](https://user-images.githubusercontent.com/78985665/120091531-c23d8e80-c0c0-11eb-962c-87d1992586df.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 400
