### ISSUE TITLE
Playlist Thumbnail for "Sass & SCSS for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#187]
**Task**
Create a thumbnail graphic for the "Sass & SCSS for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Prawesh-MAGNETIC** [comment]
![Sass   SCSS for Beginners](https://user-images.githubusercontent.com/71756108/120094900-a7126380-c140-11eb-97e1-986d87070096.png)



A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by stweyel** [comment]
![Sass](https://user-images.githubusercontent.com/25363181/120119499-4282f300-c198-11eb-9566-b7d8248d3029.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by joeonit** [comment]
![Sass   SCSS forBeginners](https://user-images.githubusercontent.com/85009659/120123583-ef1c9f00-c1af-11eb-97a6-cdd2fc67ad41.png)
Account: 1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901
