### ISSUE TITLE
Playlist Thumbnail for "Foundation for Responsive Web Design for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#188]
**Task**
Create a thumbnail graphic for the "Foundation for Responsive Web Design for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Docebo-Netflix** [comment]
![Thumbnail_Foundation-for-Responsive-Web-Design-for-Beginners_188](https://user-images.githubusercontent.com/78985665/120091974-915f5880-c0c4-11eb-8872-33d840127da0.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 400
