### ISSUE TITLE
Playlist Thumbnail for "Gulp (Gulp.js) for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#189]
**Task**
Create a thumbnail graphic for the "Gulp (Gulp.js) for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Docebo-Netflix** [comment]
![Thumbnail_Gulp_189](https://user-images.githubusercontent.com/78985665/120097203-1a39bc80-c0e4-11eb-8d3f-dd0db01fa29b.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 400
