### ISSUE TITLE
Playlist Thumbnail for "Angular 2 for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#190]
**Task**
Create a thumbnail graphic for the "Angular 2 for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by SwedishFisherman** [comment]
![Uploading Thumbnail_Angular2_190.png…]()

**Comment by Docebo-Netflix** [comment]
![Thumbnail_Angular2_190](https://user-images.githubusercontent.com/78985665/120097706-f035c980-c0e6-11eb-871c-fa5c6e00987d.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 400
