### ISSUE TITLE
Playlist Thumbnail for "ECMAScript 6 / ES6"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#191]
**Task**
Create a thumbnail graphic for the "ECMAScript 6 / ES6" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Docebo-Netflix** [comment]
![Thumbnail_ECMAScript_191](https://user-images.githubusercontent.com/78985665/120115521-e2109900-c138-11eb-81e8-82a5c7d103ba.png)

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 400
