### ISSUE TITLE
Playlist Thumbnail for "HTML5"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#192]
**Task**
Create a thumbnail graphic for the "HTML5" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stoimenov00** [comment]
![html](https://user-images.githubusercontent.com/78659181/120045762-0cffcd80-c011-11eb-9b13-895305a429e8.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

https://we.tl/t-LUc8OWzgwu

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 400
