### ISSUE TITLE
Playlist Thumbnail for "AJAX"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#193]
**Task**
Create a thumbnail graphic for the "AJAX" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stoimenov00** [comment]
![ajax](https://user-images.githubusercontent.com/78659181/120046120-c2cb1c00-c011-11eb-8816-bcf7fe97194e.png)
https://we.tl/t-XbYslvx2EJ

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00 
Amount: 400
