### ISSUE TITLE
Playlist Thumbnail for "Responsive Web Design"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#194]
**Task**
Create a thumbnail graphic for the "Responsive Web Design" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![Responsive Web Design Tutorial](https://user-images.githubusercontent.com/85009659/120124045-7c60f300-c1b2-11eb-8d36-101f6d079df3.png)
Account: 1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400

**Comment by stweyel** [comment]
![Responsive](https://user-images.githubusercontent.com/25363181/120235670-da491580-c25a-11eb-9592-6a44f2464ed5.png)

...aarrgh... too late
