### ISSUE TITLE
Playlist Thumbnail for "Django for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#196]
**Task**
Create a thumbnail graphic for the "Django for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Prawesh-MAGNETIC** [comment]
![Django for Beginners](https://user-images.githubusercontent.com/71756108/120056123-edd85e80-c057-11eb-99a0-9fc1739f75de.png)



A/c: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by buckyroberts** [comment]
@Prawesh-MAGNETIC can you make the "django" graphic larger and use a "Django green" background?

**Comment by hussu010** [comment]
![Linux for Beginners (1)](https://user-images.githubusercontent.com/55182298/120099693-9b349a80-c15c-11eb-830d-b4e77c2acaeb.png)
#django #love
My Account Number: 22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @hussu010 
Amount: 400
