### ISSUE TITLE
Playlist Thumbnail for "TNBC Node Deployment"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#198]
**Task**
Create a thumbnail graphic for the "TNBC Node Deployment" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stweyel** [comment]
![Node Deplyment3](https://user-images.githubusercontent.com/25363181/120118112-36476780-c191-11eb-9b67-615bb42398ba.png)


![Node Deplyment](https://user-images.githubusercontent.com/25363181/120115042-3e4bdb00-c182-11eb-94ad-99d8ca83974b.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stweyel 
Amount: 400
