### ISSUE TITLE
Playlist Thumbnail for "SEO for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#200]
**Task**
Create a thumbnail graphic for the "SEO for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Prawesh-MAGNETIC** [comment]
![SEO for Beginners](https://user-images.githubusercontent.com/71756108/120113324-8d503b00-c197-11eb-92a3-5664f2020799.png)




A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by buckyroberts** [comment]
@Prawesh-MAGNETIC can you make the text "SEO for Beginners" a lot bigger? Also can we have a non-white background? That way it will stand out better from the website background.

**Comment by joeonit** [comment]
![SEO for Beginners](https://user-images.githubusercontent.com/85009659/120123063-14f47480-c1ad-11eb-9be0-2a4b3ca692d4.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by Prawesh-MAGNETIC** [comment]
![SEO for Beginners](https://user-images.githubusercontent.com/71756108/120148238-8a8c2f00-c205-11eb-916a-8a4dca16feb3.png)



A/c:  b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Prawesh-MAGNETIC 
Amount: 400
