### ISSUE TITLE
Playlist Thumbnail for "Python 3.4 Programming"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#201]
**Task**
Create a thumbnail graphic for the "Python 3.4 Programming" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Prawesh-MAGNETIC** [comment]
![Python 3 4](https://user-images.githubusercontent.com/71756108/120056882-a6080600-c05c-11eb-9bb8-e524fe947ee4.png)



A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by Prawesh-MAGNETIC** [comment]
![Python 3 4 Programming](https://user-images.githubusercontent.com/71756108/120096934-a03d1e00-c14b-11eb-872b-4bdb26b64cc0.png)

**Comment by buckyroberts** [comment]
@Prawesh-MAGNETIC noice

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Prawesh-MAGNETIC 
Amount: 400
