### ISSUE TITLE
Playlist Thumbnail for "Linux for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#202]
**Task**
Create a thumbnail graphic for the "Linux for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Prawesh-MAGNETIC** [comment]
![Linux for Beginners](https://user-images.githubusercontent.com/71756108/120057529-714a7d80-c061-11eb-867d-767f29242dda.png)




A/c:  b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by Prawesh-MAGNETIC** [comment]
![Uploading Linux for Beginners.png…]()

**Comment by Prawesh-MAGNETIC** [comment]
![Linux for Beginners](https://user-images.githubusercontent.com/71756108/120057776-6f81b980-c063-11eb-8115-80c59914b7d2.png)

**Comment by buckyroberts** [comment]
@Prawesh-MAGNETIC can you make the text a lot bigger for graphic 2? They are going to be displayed on this page https://thenewboston.com/tutorials/All so the graphics will be pretty small, want to make sure the text is big enough for people to read easily.

**Comment by Prawesh-MAGNETIC** [comment]
![Linux for Beginners](https://user-images.githubusercontent.com/71756108/120095457-b810a400-c143-11eb-8a4c-b5d130b062f6.png)



edited sir @buckyroberts

**Comment by hussu010** [comment]
![Linux for Beginners](https://user-images.githubusercontent.com/55182298/120099474-565c3400-c15b-11eb-88c8-f25f7d5d96de.png)

Bounty to @Prawesh-MAGNETIC

**Comment by Prawesh-MAGNETIC** [comment]
> ![Linux for Beginners](https://user-images.githubusercontent.com/55182298/120099474-565c3400-c15b-11eb-88c8-f25f7d5d96de.png)
> 
> Bounty to @Prawesh-MAGNETIC

Loved the design @hussu010  You deserve the Bounty. Thank you for counting me :)

**Comment by hussu010** [comment]
Alright @Prawesh-MAGNETIC

My Account Number: 22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @hussu010 
Amount: 400
