### ISSUE TITLE
Playlist Thumbnail for "Python Network Packet Sniffer"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#204]
**Task**
Create a thumbnail graphic for the "Python Network Packet Sniffer" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![Python Network Packet Sniffer](https://user-images.githubusercontent.com/85009659/120125132-b2ed3c80-c1b7-11eb-9aa0-aad45dac0175.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
