### ISSUE TITLE
Playlist Thumbnail for "Wireshark for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#205]
**Task**
Create a thumbnail graphic for the "Wireshark for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![for Beginners](https://user-images.githubusercontent.com/85009659/120116607-2b88d480-c189-11eb-80a9-f0fff6d17dc9.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by stweyel** [comment]
![Wireshark2](https://user-images.githubusercontent.com/25363181/120117739-f0899f80-c18e-11eb-9fbe-9a805ebe074f.png)

![Wireshark3](https://user-images.githubusercontent.com/25363181/120117519-ec10b700-c18d-11eb-8442-3c9fd84b47c3.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stweyel 
Amount: 400
