### ISSUE TITLE
Playlist Thumbnail for "Flask Web Development with Python"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#207]
**Task**
Create a thumbnail graphic for the "Flask Web Development with Python" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Prawesh-MAGNETIC** [comment]
![Flask web development with python](https://user-images.githubusercontent.com/71756108/120111690-8eca3500-c190-11eb-8083-d807b7dedaf2.png)




A/c:    b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by joeonit** [comment]
![Flask Web Development with Python](https://user-images.githubusercontent.com/85009659/120115178-cf22b680-c182-11eb-9a46-11938ba13176.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
