### ISSUE TITLE
Playlist Thumbnail for "Python GUI Development with GTK+ 3"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#208]
**Task**
Create a thumbnail graphic for the "Python GUI Development with GTK+ 3" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![Python GUI Development with GTK+ 3](https://user-images.githubusercontent.com/85009659/120113899-ef4f7700-c17c-11eb-8493-a225b38c71bc.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
