### ISSUE TITLE
Playlist Thumbnail for "Python Website Scanner"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#209]
**Task**
Create a thumbnail graphic for the "Python Website Scanner" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![Python Website Scanner](https://user-images.githubusercontent.com/85009659/120113650-b662d280-c17b-11eb-98da-36fec1a7e83c.png)
Account: 1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![Python Website Scanner (1)](https://user-images.githubusercontent.com/85009659/120113659-c4b0ee80-c17b-11eb-8ea9-03c900613333.png)
v2

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
