### ISSUE TITLE
Playlist Thumbnail for "Metasploit for Network Security"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#210]
**Task**
Create a thumbnail graphic for the "Metasploit for Network Security" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![Metasploit for Network Security](https://user-images.githubusercontent.com/85009659/120112985-ac8ba000-c178-11eb-8c71-74abe264f1dd.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![Uploading Metasploit for Network Security (1).png…]()
v2

**Comment by joeonit** [comment]
![Metasploit for Network Security (1)](https://user-images.githubusercontent.com/85009659/120113000-ca590500-c178-11eb-967c-c072e1db4725.png)
v2

**Comment by buckyroberts** [comment]
@joeonit beautiful

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
