### ISSUE TITLE
Playlist Thumbnail for "Nmap"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#211]
**Task**
Create a thumbnail graphic for the "Nmap" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![sitelogo-nmap-1680x900](https://user-images.githubusercontent.com/85009659/120085352-c628db00-c0d7-11eb-97ad-ad71f305eb85.png)
Account: 1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![Nmap (1)](https://user-images.githubusercontent.com/85009659/120085374-ee183e80-c0d7-11eb-8158-c1b735e2276a.png)
Account: 1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![Nmap (2)](https://user-images.githubusercontent.com/85009659/120085397-12741b00-c0d8-11eb-9cef-ccda82468022.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@joeonit beautiful

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
