### ISSUE TITLE
Playlist Thumbnail for "JavaFX Java GUI Design"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#215]
**Task**
Create a thumbnail graphic for the "JavaFX Java GUI Design" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![JavaFX Java GUI Design (1)](https://user-images.githubusercontent.com/85009659/120112437-1eaeb580-c176-11eb-8cfc-0d24782b040f.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![JavaFX Java GUI Design (2)](https://user-images.githubusercontent.com/85009659/120112552-9f6db180-c176-11eb-9fbd-06b0f24e7ea2.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
