### ISSUE TITLE
Playlist Thumbnail for "MongoDB for Beginners"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#216]
**Task**
Create a thumbnail graphic for the "MongoDB for Beginners" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![MongoDB for Beginners](https://user-images.githubusercontent.com/85009659/120074650-17b47400-c09e-11eb-80d6-d1422fa651db.png)
Account: e33e430484e5bfb08c25788c2889e9af39b9853c961f5776f0253000759e2108

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
