### ISSUE TITLE
Playlist Thumbnail for "Pygame (Python Game Development)"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#220]
**Task**
Create a thumbnail graphic for the "Pygame (Python Game Development)" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![Your paragraph text](https://user-images.githubusercontent.com/85009659/120111098-dc36aa00-c170-11eb-8add-43f320ce2b69.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by Prawesh-MAGNETIC** [comment]
![Pygame](https://user-images.githubusercontent.com/71756108/120115012-73b2f180-c19f-11eb-853e-87c8eef48c9f.png)


A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
