### ISSUE TITLE
Playlist Thumbnail for "Microsoft Excel 2013"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#222]
**Task**
Create a thumbnail graphic for the "Microsoft Excel 2013" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by Prawesh-MAGNETIC** [comment]
![Microsoft Excel 2013](https://user-images.githubusercontent.com/71756108/120066494-56453100-c094-11eb-9eba-089bc6216e57.png)




A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by buckyroberts** [comment]
@Prawesh-MAGNETIC can you make the text a lot bigger?

**Comment by Prawesh-MAGNETIC** [comment]
![Microsoft Excel 2013](https://user-images.githubusercontent.com/71756108/120095144-f1481480-c141-11eb-813d-f846b9307909.png)



edited sir @buckyroberts

**Comment by Prawesh-MAGNETIC** [comment]
![Microsoft Excel 2013](https://user-images.githubusercontent.com/71756108/120101134-2bc1a980-c162-11eb-9c88-10a0b1dd6d26.png)



A/c:    b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by joeonit** [comment]
![Microsoft Excel 2013 Tutorial](https://user-images.githubusercontent.com/85009659/120110470-e7d4a180-c16d-11eb-83c0-ce023514e030.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![Microsoft Excel 2013 Tutorial (1)](https://user-images.githubusercontent.com/85009659/120110494-089cf700-c16e-11eb-8c6c-475a620c2b45.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
