### ISSUE TITLE
Playlist Thumbnail for "R Programming"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#224]
**Task**
Create a thumbnail graphic for the "R Programming" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![R Programming](https://user-images.githubusercontent.com/85009659/120072903-46c6e780-c096-11eb-8dc0-5b7a0b8e5793.png)
Account: 1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
