### ISSUE TITLE
Playlist Thumbnail for "C Programming"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#226]
**Task**
Create a thumbnail graphic for the "C Programming" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stoimenov00** [comment]
![c programming (1)](https://user-images.githubusercontent.com/78659181/120050428-9b7a4c00-c01d-11eb-9918-50cbf80eb5a2.png)



a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00  
Amount: 400
