### ISSUE TITLE
Playlist Thumbnail for "Physics Puzzle Game Development w/ Construct 2"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#227]
**Task**
Create a thumbnail graphic for the "Physics Puzzle Game Development w/ Construct 2" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by joeonit** [comment]
![Game Development (3)](https://user-images.githubusercontent.com/85009659/120107378-21eb7680-c161-11eb-97d7-d1c36517158e.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![Game Development (4)](https://user-images.githubusercontent.com/85009659/120107398-30d22900-c161-11eb-92fd-8f6d54017f2d.png)
v2

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @joeonit 
Amount: 400
