### ISSUE TITLE
Playlist Thumbnail for "After Effects CS6"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#231]
**Task**
Create a thumbnail graphic for the "After Effects CS6" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stoimenov00** [comment]
![AE](https://user-images.githubusercontent.com/78659181/120052122-0169d200-c024-11eb-95e2-74a1a8b17f52.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stoimenov00  
Amount: 400
