### ISSUE TITLE
OG Image

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#232]
**Task**
Create an Open Graph image that will be shown when people share our link on social media. This will be our default image for every link so it should be rather generic and include our logo.

**Image Specs**
Size: 1200 x 627
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

![og-tags-1](https://user-images.githubusercontent.com/8547538/120055106-cac29600-bfe8-11eb-8b7f-64d63f26fb42.png)

**Comment by buckyroberts** [comment]
Note: related to these changes https://github.com/thenewboston-developers/Website/pull/1824

**Comment by SOHDA31** [comment]
![open graph image](https://user-images.githubusercontent.com/74038568/120231888-f99e6d80-c26f-11eb-925b-99815160d0b4.png)
Account Number : 5257c00dc543a348f3aee0c7871d7e659d4ec63b68838302f3f4da978e13c92a

**Comment by muriuki54** [comment]
![tnb_og_image](https://user-images.githubusercontent.com/43035842/120315283-dbbf2000-c2e4-11eb-9f4a-4a7fc52aa739.png)

Account number: e3a94381f8db207ddad931391886d611d6f4c060d0db2b0e373738e2f4db96d6

**Comment by Toledit** [comment]
![og](https://user-images.githubusercontent.com/27518021/120790550-c68ffe80-c53b-11eb-8ee1-07cd7546bd09.jpg)
![og2](https://user-images.githubusercontent.com/27518021/122070313-87489400-cdfe-11eb-890d-5c7990bd1bdc.jpg)

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by muriuki54** [comment]
![tnb_og](https://user-images.githubusercontent.com/43035842/120887689-fd7a1900-c5fc-11eb-9b9d-e4c4bf6a33d3.png)

63bc695af3450e84a893f2168dea3db910eee2367d4da5a5526c2a7b03108f20

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Toledit 
Amount: 400
