### ISSUE TITLE
Logo for TNB Discord Bot

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#233]
Logo needed for the "TNB Discord Bot" project. Logo will be displayed alongside the project on this page https://thenewboston.com/projects

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Comment by stweyel** [comment]
![logo2](https://user-images.githubusercontent.com/25363181/120113617-929f8c80-c17b-11eb-8d7a-0f4282c31f50.png)
![logo3](https://user-images.githubusercontent.com/25363181/120113621-93d0b980-c17b-11eb-8707-91c9bcf263ab.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stweyel 
Amount: 400
