### ISSUE TITLE
Logo for Restaurants Self-Order App

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#234]
Logo needed for the "Restaurants Self-Order App" project. Logo will be displayed alongside the project on this page https://thenewboston.com/projects

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Comment by joeonit** [comment]
![resta_prev_ui (1)](https://user-images.githubusercontent.com/85009659/120216832-cc35cd80-c237-11eb-8118-97935dde2a29.png)

**Comment by joeonit** [comment]
![resta_prev_ui (1)](https://user-images.githubusercontent.com/85009659/120216901-e079ca80-c237-11eb-8fc9-359893399d52.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by trohym** [comment]
![the new boston food logo larger](https://user-images.githubusercontent.com/50759813/120362474-baeccf80-c2d0-11eb-90c1-1863411d4f18.png)

Account: 3f9b789e2160a95e4cf0d7587cd76a3a37d47356ac26f1da6631b67e0a2ab047
