### ISSUE TITLE
Logo for TNB Faucet

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#235]
Logo needed for the "TNB Faucet" project. Logo will be displayed alongside the project on this page https://thenewboston.com/projects

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Comment by joeonit** [comment]
![Faucet](https://user-images.githubusercontent.com/85009659/120209884-75c49100-c22f-11eb-8a5f-3e9691beb98c.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by stweyel** [comment]
![Faucet](https://user-images.githubusercontent.com/25363181/120230348-6ce3b780-c24f-11eb-90ff-834089631576.png)
![Faucet2](https://user-images.githubusercontent.com/25363181/120239136-f13d3700-c25d-11eb-8b64-f6e18736bf2b.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
