### ISSUE TITLE
Logo for TNB Forum

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#236]
Logo needed for the "TNB Forum" project. Logo will be displayed alongside the project on this page https://thenewboston.com/projects

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Comment by joeonit** [comment]
![foram](https://user-images.githubusercontent.com/85009659/120208210-7e1bcc80-c22d-11eb-870c-b6c2166c267c.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by madodadev** [comment]
![logo_forum](https://user-images.githubusercontent.com/71338666/120491523-9882b100-c3b9-11eb-95ed-c8111ea64c19.png)

Account:db9494cdf4fb87ca3fcb431ea6e0a06fe9758add946d87cd9f5583b2913e243f
