### ISSUE TITLE
Logo for TNB MMORPG

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#237]
Logo needed for the "TNB MMORPG" project. Logo will be displayed alongside the project on this page https://thenewboston.com/projects

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Comment by joeonit** [comment]
![tnb game](https://user-images.githubusercontent.com/85009659/120206251-40b63f80-c22b-11eb-8ce3-d25537035b17.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901
