### ISSUE TITLE
Project Copy for "Blockchain Explorer"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#238]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/23)
- [TNB project details page](https://thenewboston.com/projects/704f9bbb-3947-4fe4-8847-94936df54edb)

**Comment by kizzi789** [comment]
Account number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8


**- Overview:** 
This project looks to create a browser for the blockchain for everyone. The system will be able to track all transactions in real-time. The project success is evaluated on the basis of the growth of users, powerful data API, and Real-time data Analysis. 


**- Problem:**
Blockchain explorer allows viewing and reading detailed data about transactions while ensuring transparency of transactions and blockchain. Users can easily read blockchain transaction histories, balances in the wallet, and so on.


**- Target Market:** 
Anyone who uses the listed blockchain(s) network, or who wants to learn to explore transactions/ledger blockchain.


**- Benefit to Network & Community:** 
The data-driven approach of the browser can benefit all individuals. For validators/miners, the explorer will provide helpful resources. Powerful search will be one prominent attribute. 


**- Centered around TNB:** 
The thenewboston digital currency will be exclusively supported on the platform.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @kizzi789 
Amount: 400
