### ISSUE TITLE
Project Copy for "Keysign"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#239]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/6)
- [TNB project details page](https://thenewboston.com/projects/00e64bb4-37b0-453e-a778-26251818affc)

**Comment by kizzi789** [comment]
Account number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8


**- Overview:** 
This project will create a Chrome/Firefox extension for transaction signing, a Website wallet with merchant services, a Mobile wallet application for TNB blockchain, a Desktop Wallet application for TNB, and Plugins that allow connection to merchant services and TNB blockchain. The project success is evaluated with the wide adoption from online services and users.


**- Problem:**
The project expects to create a decentralized interaction with the chain.


**- Target Market:** 
Site operators, Project creators, e-commerce services are the main targeted people.


**- Benefit to Network & Community:** 
Decentralized logins and communication to the chain from the Browser/Desktop/in-game and App will be allowed.


**- Centered around TNB:** 
This project is partnering with the thenewboston-js team for API features. It will create a handshake between sites and the browser that allows them to connect to the chain.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @kizzi789 
Amount: 400
