### ISSUE TITLE
Project Copy for "Restaurants Self-Order App"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#240]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/26)
- [TNB project details page](https://thenewboston.com/projects/a3026771-741d-4904-9b62-0e09580cdec0)

**Comment by kizzi789** [comment]
Account number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8

**Overview:** 
This project will create an App/Web App in which customers will navigate to the restaurant they like to pay for their order. Both cryptocurrency payments or direct POS payments will be added for more convenience. The project success is evaluated by the number of restaurants and cafes enrolled with us.

**Problem:**
Customers can easily checkout and browse restaurant menus on their own devices. This project will make a centric system for all the restaurants and the cafes.

**Target Market:**
Restaurants, Cafes, TNBC holders

**Benefit to Network and Community:**
It will make life easier and reduce waiting time for customers, and reduce cost on restaurants. Customers no longer need to wait in line.
 
**Centered Around TNB:**
This project will make a value for TNBC as it will be the circulated coin. The restaurants will receive direct payments from customers.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @kizzi789 
Amount: 400
