### ISSUE TITLE
Project Copy for "TNB Faucet"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#242]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/141)
- [TNB project details page](https://thenewboston.com/projects/589649fb-dfaa-4081-b04a-2e9179cf1a21)

**Comment by kizzi789** [comment]
Account number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8

**Overview:**
It is a project to create a faucet to allow people to put their wallet address in and get coins. The project's success can be evaluated if we can get tens of thousands of people holding the coins. UI/UX designing, Setting up CAPTCHA and landing page, designing backend to send coins, and so on come under the major milestones of this project.


**Problem:** 
The project eases the distribution of the thenewboston coins to people. The project will also be looking to solve problems from the Normal bot abuse and people trying to claim on multiple accounts.


**Target Market:**
Crypto World, Bucky’s followers, and people looking to find a way in with no skill set.


**Benefit to Network & Community:**
TNB Faucet will allow the spread of coins early on. It would also allow any project to give away coins. It’s also a way to educate people of the chain by steering them into the right channels like the main website, discord, and GitHub.


**Centered around TNB:**
This faucet pays people out to their wallets. TNBC is the circulated coin.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @kizzi789 
Amount: 400
