### ISSUE TITLE
Project Copy for "TNB MMORPG"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#244]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/108)
- [TNB project details page](https://thenewboston.com/projects/a8ec0b29-281c-4a6f-aed2-4a2007eab350)

**Comment by kizzi789** [comment]
Account number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8

**Overview:**
The main goal for the project is to get a game first to the BETA release, and then launch fully to help the chain advertise its capabilities. The project success is evaluated with the number of network transactions happening with the ID of the game. Finalizing scope, Building story, Character designs, Asset, and map creation, Quests, Skill tree, crafting, and many more come under our milestones.
 

**Problem:**
Token sink for token lockup. Sidewise, the project will also be looking to solve problems that will come from the possibility of high fees for transactions as time goes on.
 

**Target market:**
Gamers and crypto investors are the main targets. Investors and more other active users are also the targeted people.
 
**Benefits:**
The project expects to bring investors and active users into the network. This could help to highlight the chain's strengths against all chains that pre-exist.
 
**Centered around TNB:**
We will be using the upcoming feeless transactions to create items and in-game currency.  We will also be looking to facilitate trades for those items.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @kizzi789 
Amount: 400
