### ISSUE TITLE
Project Logo for "Kotlin Multiplaform Mobile SDK"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#245]
**Task**
Create a logo for the "Kotlin Multiplaform Mobile SDK" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Comment by stweyel** [comment]
![Kotlin](https://user-images.githubusercontent.com/25363181/120204545-3bf08c00-c229-11eb-8c3d-e247d3de6f81.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
