### ISSUE TITLE
Project Logo for "TNBpay"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#246]
**Task**
Create a logo for the "TNBpay" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Comment by joeonit** [comment]
![pay](https://user-images.githubusercontent.com/85009659/120218169-a0b3e280-c239-11eb-9053-8089f2b96171.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by joeonit** [comment]
![pay1](https://user-images.githubusercontent.com/85009659/120218281-c93bdc80-c239-11eb-85dd-bff0b98f98d4.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by stweyel** [comment]
![Pay3a](https://user-images.githubusercontent.com/25363181/120229072-ae269800-c24c-11eb-836f-551c9861ad0d.png)
![Pay3](https://user-images.githubusercontent.com/25363181/120228877-4d975b00-c24c-11eb-97ec-56a1a5ca316f.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
