### ISSUE TITLE
Project Logo for "Hierarchical deterministic (HD) Wallets for TNB"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#247]
**Task**
Create a logo for the "Hierarchical deterministic (HD) Wallets for TNB" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Links**
- [Project Proposal](https://github.com/thenewboston-developers/Projects/issues/198)

**Comment by joeonit** [comment]
![wallet tnb](https://user-images.githubusercontent.com/85009659/120195586-43129c80-c21f-11eb-8039-dacee038a912.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901
