### ISSUE TITLE
Project Logo for "TNBAnon"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#248]
**Task**
Create a logo for the "TNBAnon" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Links**
- [Project Proposal](https://github.com/thenewboston-developers/Projects/issues/201)

**Comment by joeonit** [comment]
![TNBAnon](https://user-images.githubusercontent.com/85009659/120193311-8cadb800-c21c-11eb-918e-223e44901425.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by stweyel** [comment]
![Anon](https://user-images.githubusercontent.com/25363181/120202611-18c4dd00-c227-11eb-941d-b93096b0b41c.png)
94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
