### ISSUE TITLE
Project Logo for "TNB Minecraft Integration"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#249]
**Task**
Create a logo for the "TNB Minecraft Integration" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Links**
- [Project Proposal](https://github.com/thenewboston-developers/Projects/issues/206)

**Comment by joeonit** [comment]
![minecraft](https://user-images.githubusercontent.com/85009659/120190487-f75cf480-c218-11eb-9226-90b397b6d150.png)
Account:1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by brain-dead-diode** [comment]
![TNB_Redstone](https://user-images.githubusercontent.com/54914039/120225240-ddb8ae80-c212-11eb-8f54-477dce8e3463.jpg)
Account:938e08fcef206dbd45588dbb7b6e27ae40a1dbb7d632340faa205a67ae9f7d2b

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @datdood 
Amount: 400
