### ISSUE TITLE
Project Logo for "tnbGo"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#250]
**Task**
Create a logo for the "tnbGo" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64
Format: JPG or PNG

**Links**
- [Project Proposal](https://github.com/thenewboston-developers/Projects/issues/212)

**Comment by joeonit** [comment]
![untitled](https://user-images.githubusercontent.com/85009659/120168707-76ddca00-c1ff-11eb-808a-25605884e541.png)

**Comment by joeonit** [comment]
![tnbgo](https://user-images.githubusercontent.com/85009659/120172271-25cfd500-c203-11eb-9228-a4cece5064fa.png)
Account: 1e21e1a87c6fb97623cae87b2d664b3c66b7101035e4fce74117d58701d21901

**Comment by stweyel** [comment]
![Go](https://user-images.githubusercontent.com/25363181/120196482-32aef180-c220-11eb-9d90-b36785c804f2.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by Toledit** [comment]
![64 blue](https://user-images.githubusercontent.com/27518021/120224808-cd252a00-c24c-11eb-9e39-f02d58bc2c61.jpg)
![64 blue white](https://user-images.githubusercontent.com/27518021/120224830-ddd5a000-c24c-11eb-995d-0ca61e52e144.jpg)
![red](https://user-images.githubusercontent.com/27518021/120225142-5d636f00-c24d-11eb-8a00-dfbbad52c783.jpg)
![Asset 1](https://user-images.githubusercontent.com/27518021/120225049-373dcf00-c24d-11eb-9db1-e983fddff06e.png)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a
*the payment might be so little as a result i fear it might demotivate our professional designers to take part

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Toledit  
Amount: 400
