### ISSUE TITLE
Project Copy for "TNBpay"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#252]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/172)

**Comment by kizzi789** [comment]
Account number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8

**- Overview:** 
This project will be creating a plugin that allows users to pay with TNBC on popular E-commerce platforms. User flow and wireframing, Hifi Design, and WordPress, Shopify, Wix store, Bigcommerce, and PrestaShop development are the main milestones of this project.


**- Problem:** 
Users can pay directly with TNBC for products and services on popular E-commerce platforms. This eradicates the need to sell their coins for the required currency.
 

**- Target Market:** 
TNBC users who own E-commerce sites, and who participate in online shopping. 


**-Benefit to Network & Community:** This project involves more people with TNB. TNBC holders can easily buy products and services from popular E-commerce platforms.


**- Centered around TNB:** 
It would bring more people to use thenewboston digital currency as TNBC is the circulated coin.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @kizzi789 
Amount: 400
