### ISSUE TITLE
Project Copy for "tnbGo"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#256]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/212)

**Comment by kizzi789** [comment]
Account number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8


**- Overview:** 
This project looks to provide a Software Development Kit (SDK) written in Go to interact with thenewboston network. 

 
**- Problem:** 
Many programmers who use languages other than Javascript do not have an easy and simple way to access the network. This project is looking to solve this problem.


**- Target Market:** 
Developers who are interested in interacting with the chain through Golang (an open-source programming language).


**Benefit to Network & Community:** 
More apps and projects will pop up written in Golang which will be helpful because of Golang's unique features.


**- Centered around TNB:** 
As **tnbGo** is an SDK for thenewboston network, it will always revolve around TNB.

**Comment by gligorovam** [comment]
tnbGo is a project that will enable better interaction with thenewboston network by providing SDK written in Go.  It has the goal to promote different programming languages other than Javascript.
 This would offer a solution for the programmers using programming languages other than Javascript, encouraging more programmers to join. It would solve the problem of people using different languages having difficulties with accessing the network. Ultimately, it would give a fair opportunity to a wider mass of programmers.
 This expands the opportunities for any developer interested in working with the chain through Gulang, so anyone with passion and wish would be a part of the target market. It is also an opportunity with users with different skills set to shine.
 The result from this would be the wider representation of projects written in Golang, carrying its unique features. By offering more apps and projects In this programming language, it's pros will be highlighted. 
 This project is an SDK for thenewboston network, contributing directly to the website. This is further directly contributing to the website.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @gligorovam  
Amount: 400

**Comment by Chrisha1212** [comment]
> tnbGo is a project that will enable better interaction with thenewboston network by providing SDK written in Go. It has the goal to promote different programming languages other than Javascript.
> This would offer a solution for the programmers using programming languages other than Javascript, encouraging more programmers to join. It would solve the problem of people using different languages having difficulties with accessing the network. Ultimately, it would give a fair opportunity to a wider mass of programmers.
> This expands the opportunities for any developer interested in working with the chain through Gulang, so anyone with passion and wish would be a part of the target market. It is also an opportunity with users with different skills set to shine.
> The result from this would be the wider representation of projects written in Golang, carrying its unique features. By offering more apps and projects In this programming language, it's pros will be highlighted.
> This project is an SDK for thenewboston network, contributing directly to the website. This is further directly contributing to the website.

can you include your account number?

**Comment by buckyroberts** [comment]
@gligorovam ^

**Comment by Chrisha1212** [comment]
@gligorovam
