### ISSUE TITLE
Playlist Thumbnail for "PHP Instagram Downloader"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#257]
**Task**
Create a thumbnail graphic for the "PHP Instagram Downloader" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/5aDrcya.png)
![](https://i.imgur.com/Nm0S2Oe.jpg)
![](https://i.imgur.com/zpr5cU8.jpg])

**Comment by stweyel** [comment]
![php insta downloader](https://user-images.githubusercontent.com/25363181/120247745-d88c4b80-c274-11eb-8bd6-2871f72033fa.png)



94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @stweyel 
Amount: 400
