### ISSUE TITLE
 Join us

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#258]
**Task**
You know the drill, a graphic telling people to join us.
(Facebook, Twitter, Instagram)
Due Date: 06.03.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I will work on this task

**Comment by stoimenov00** [comment]
Facebook
![#258 Facebook](https://user-images.githubusercontent.com/78659181/120565090-9dbd1b80-c40c-11eb-9abc-a2fb667fc800.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
![#258 INSTAGRAM](https://user-images.githubusercontent.com/78659181/120566170-fbeafe00-c40e-11eb-9361-944754e15c0e.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
![#258 Twitter (1)](https://user-images.githubusercontent.com/78659181/120664589-57f36800-c48b-11eb-9d31-51bf4c836729.png)


a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoimenov00 -2400
