### ISSUE TITLE
Download the Account Manager

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#259]
**Task**
A graphic telling to download their account manager so they can have an account number and interact with TNB.
(Facebook, Twitter, Instagram)
Due date: 06.03.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I'll work on these

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook--DownloadApp-259](https://user-images.githubusercontent.com/78985665/120609123-c3dfbd00-c406-11eb-8def-c31c6bbb200e.png)

**Comment by Docebo-Netflix** [comment]
Instagram
![Insta--DownloadApp-259](https://user-images.githubusercontent.com/78985665/120609191-d0fcac00-c406-11eb-80ba-9972c7d93886.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter--DownloadApp-259](https://user-images.githubusercontent.com/78985665/120609244-da861400-c406-11eb-9a32-ed350e749703.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman -2400
