### ISSUE TITLE
Faucet

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#260]
**Task**
A graphic telling people to to visit our faucet at https://tnbfaucet.com if they want FREE 50 TNBC.
(Facebook, Twitter, Instagram)
Due date: 06.03.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I am working on this task

**Comment by stoimenov00** [comment]
Facebook
![#260 Facebook](https://user-images.githubusercontent.com/78659181/120572425-33ac7280-c41c-11eb-9d08-d86926b7144e.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
![#260 INSTAGRAM](https://user-images.githubusercontent.com/78659181/120572493-52126e00-c41c-11eb-97ba-6bbcd6856f2b.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter 
![#260 Twitter](https://user-images.githubusercontent.com/78659181/120671492-b9b6d080-c491-11eb-8972-b47f647f5fa4.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoimenov00 -2400
