### ISSUE TITLE
Fastest Blockchain

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#261]
**Task**
A graphic telling people how TNBC has the fastest network out there!
(Twitter, Instagram)
Due date: 06.03.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
Instagram *Edited(fixed dimension issue)
![instagram 2 #262](https://user-images.githubusercontent.com/27518021/120614308-c28eae80-c45f-11eb-83ed-6ba98864948d.jpg)

Twitter
![twitter-#261 2](https://user-images.githubusercontent.com/27518021/120489080-016d2780-c3c0-11eb-871d-304d1c2e3095.jpg)

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by Chrisha1212** [comment]
@Toledit -1600
