### ISSUE TITLE
Decentralized App

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#262]
**Task**
A graphic for all the people (not just coders) who want to create a decentralized app by creating a project proposal
(Facebook, Twitter, Instagram)
Due date: 06.03.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![dApps](https://user-images.githubusercontent.com/71756108/120493962-068aa080-c3d9-11eb-84f5-b09cead5b4c5.png)





A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by Toledit** [comment]
> ![dApps](https://user-images.githubusercontent.com/71756108/120493962-068aa080-c3d9-11eb-84f5-b09cead5b4c5.png)
> 
> A/c: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

Cool Designs! FYI, The lesser the text the better - while designing your infographics. The core team prefers it that way. Cheers.

**Comment by Toledit** [comment]
@Prawesh-MAGNETIC Cool Designs! FYI, The lesser the text the better - while designing your infographics. The core team prefers it that way. Cheers.

**Comment by Toledit** [comment]
Instagram
![instagram  #262](https://user-images.githubusercontent.com/27518021/120633506-e6a7bb00-c472-11eb-9618-3ea124d8f5f4.jpg)
Facebook
![facebook  #262](https://user-images.githubusercontent.com/27518021/120633565-f3c4aa00-c472-11eb-8236-feadc49a4040.jpg)
Twitter
![twitter-#262](https://user-images.githubusercontent.com/27518021/120633580-fb844e80-c472-11eb-8452-15f15b8dfbf0.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by Prawesh-MAGNETIC** [comment]
@Toledit Thank you so much for the compliment. I am growing and thenewboston and the community contributors like you are a real booster. let us grow together! I am enjoying the community. #HelpMeGrow !

**Comment by Toledit** [comment]
Definitely! If you want any assets or questions, feel free to ping🚀

**Comment by Chrisha1212** [comment]
@Toledit- 2400
