### ISSUE TITLE
Playlist Thumbnail for "Docker"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#263]
**Task**
Create a thumbnail graphic for the "Docker" tutorial series to be used on this page https://thenewboston.com/tutorials/All

Thumbnail should:
- Incorporate the topic logo (if available)
- Match colors/styling for the topic
- Be high quality

**Image Specs**
Size: 1280 x 720
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/Kcaf9k2.png)
![](https://i.imgur.com/q5RINQX.png)
![](https://i.imgur.com/l8hYdVD.png)

**Comment by RobbieObe** [comment]
![TNB_DOCKER](https://user-images.githubusercontent.com/81463471/120717760-5e540500-c4c8-11eb-9936-1853c5c0fd45.png)
61b2d9af56556e3b973dd6417da14bf9c5b5d306d0043439bc744fd828b3a640

**Comment by Docebo-Netflix** [comment]
![Thumbnail_Docker_263](https://user-images.githubusercontent.com/78985665/120719598-6a67a480-c47f-11eb-9f46-82bcd157aeba.png)

**Comment by muriuki54** [comment]
![docker_thumb](https://user-images.githubusercontent.com/43035842/120888851-3fa65900-c603-11eb-8912-7a6f20a8908c.png)

63bc695af3450e84a893f2168dea3db910eee2367d4da5a5526c2a7b03108f20

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @SwedishFisherman 
Amount: 400
