### ISSUE TITLE
Promote Senior Python / Django Developer opening

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#265]
**Task**
Create a graphic to promote our open Senior Python / Django Developer position.

https://thenewboston.com/openings/Engineering/senior-python-django-developer

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I’m working on this

**Comment by Docebo-Netflix** [comment]
Instagram
Facebook
LinkedIn
Reddit
![FB-Insta--Issue-265](https://user-images.githubusercontent.com/78985665/121797401-da3f0300-cbd4-11eb-88dc-561d98785616.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter--Issue-265](https://user-images.githubusercontent.com/78985665/121797415-ef1b9680-cbd4-11eb-9da4-7ba6fbd98516.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman -1600
