### ISSUE TITLE
Crypto Quote 

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#266]
**Task**
This will be the description: Education is not always about the degree. Learn, build and grow your skills with thenewboston.

We need this for Facebook, Twitter, Instagram, LinkedIn, Reddit and Pintrest

Due Date: 15.06.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I am working on this

**Comment by stoimenov00** [comment]
Facebook
<img width="1200" alt="#266 Facebook (1)" src="https://user-images.githubusercontent.com/78659181/122049473-bf41de00-cde2-11eb-8495-deca3a67579a.png">

Edited:
<img width="1200" alt="#266 Facebook" src="https://user-images.githubusercontent.com/78659181/122247332-8f203b00-cec7-11eb-9520-c19cb730a2d7.png">



a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
<img width="1080" alt="#266 INSTAGRAM" src="https://user-images.githubusercontent.com/78659181/121942637-ff588080-cd50-11eb-9f4f-43a6175db8c3.png">

Edited:
<img width="1080" alt="#266 INSTAGRAM" src="https://user-images.githubusercontent.com/78659181/122247413-9c3d2a00-cec7-11eb-95b6-c49bc897ab73.png">


a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Linkedin
<img width="1080" alt="#266 Linkedin" src="https://user-images.githubusercontent.com/78659181/121943286-b81ebf80-cd51-11eb-9761-7165abed6739.png">

Edited:
<img width="1080" alt="#266 Linkedin" src="https://user-images.githubusercontent.com/78659181/122247529-b37c1780-cec7-11eb-997b-abb5bc66b972.png">

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pinterest
![Uploading #266 Pineterest.png…]()
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pinterest
<img width="1000" alt="#266 Pineterest" src="https://user-images.githubusercontent.com/78659181/122049989-5149e680-cde3-11eb-9eef-eeb5339c4e0a.png">

Edited:
<img width="1000" alt="#266 Pineterest" src="https://user-images.githubusercontent.com/78659181/122247626-c5f65100-cec7-11eb-8a76-3b558fe5f1f9.png">



a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
<img width="1200" alt="#266 Twitter" src="https://user-images.githubusercontent.com/78659181/121944461-fc5e8f80-cd52-11eb-92f2-0ccc5e14ac50.png">

Edited:
<img width="1200" alt="#266 Twitter" src="https://user-images.githubusercontent.com/78659181/122247683-d27aa980-cec7-11eb-9698-23865c34a67b.png">

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![#266 reddit](https://user-images.githubusercontent.com/78659181/121944539-0d0f0580-cd53-11eb-8590-4a374a1a2fd0.png)

Edited:
![reddit](https://user-images.githubusercontent.com/78659181/122247749-e1f9f280-cec7-11eb-861a-6b3c3c4db8aa.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoime-4800
