### ISSUE TITLE
Inspirational Post

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#267]
**Task**
This will be the description: Erik Finman - Teenage Bitcoin Millionaire

We need this for Facebook, Twitter, Instagram, LinkedIn, Reddit and Pintrest

Due Date: `15.06.2021`

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
Facebook
![facebook #267](https://user-images.githubusercontent.com/27518021/122070627-ce368980-cdfe-11eb-8aec-1d5fc4853df2.jpg)
Twitter
![twitter-#267](https://user-images.githubusercontent.com/27518021/122071421-646aaf80-cdff-11eb-9590-89862e919698.jpg)
Instagram
![instagram #267](https://user-images.githubusercontent.com/27518021/122071460-6b91bd80-cdff-11eb-946f-0d748ea99df0.jpg)
LinkedIn
![LinkedIn #267](https://user-images.githubusercontent.com/27518021/122071543-78161600-cdff-11eb-9b46-7dcba3d437c4.jpg)
Reddit 
![Reddit #267](https://user-images.githubusercontent.com/27518021/122071567-7f3d2400-cdff-11eb-9d60-6b0f8e56ef00.jpg)
Pintrest
![Pinterest-#267](https://user-images.githubusercontent.com/27518021/122071577-8401d800-cdff-11eb-975e-48a67165a80d.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by Prawesh-MAGNETIC** [comment]
@Toledit Lovely.

**Comment by Chrisha1212** [comment]
@Toledit -4800
