### ISSUE TITLE
Crypto Tips and Hacks

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#268]
**Task**
This will be the description: The only investment you need is your time

We need this for Facebook, Twitter, Instagram, LinkedIn, Reddit and Pintrest

Due Date: 15.06.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I will work on this task

**Comment by stoimenov00** [comment]
Facebook
<img width="1200" alt="#268 Facebook" src="https://user-images.githubusercontent.com/78659181/121927184-0d9da100-cd3f-11eb-9867-897ebd2fdbda.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
<img width="1080" alt="#268 INSTAGRAM" src="https://user-images.githubusercontent.com/78659181/121927424-4e95b580-cd3f-11eb-97a6-d2b618177628.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Linkedin
<img width="1080" alt="#268 Linkedin" src="https://user-images.githubusercontent.com/78659181/121927462-5b1a0e00-cd3f-11eb-8166-82e832cd8ae9.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pinterest
<img width="1000" alt="#268 Pineterest" src="https://user-images.githubusercontent.com/78659181/121927492-6705d000-cd3f-11eb-91f5-5c7adc323c83.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
<img width="1200" alt="#268 Twitter" src="https://user-images.githubusercontent.com/78659181/121927593-869cf880-cd3f-11eb-8f54-ffab00e7305e.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![#268 reddit](https://user-images.githubusercontent.com/78659181/121927938-ec898000-cd3f-11eb-941d-d0ab2fe3c9c2.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoimenov00 - 4800
