### ISSUE TITLE
Crypto Questions

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#269]
**Task**
The description will be: How old were you when you started learning about cryptocurrency?

We need this for Facebook, Twitter, Instagram, LinkedIn, Reddit and Pintrest

Due Date: 15.06.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I’m working on this

**Comment by SwedishFisherman** [comment]
Instagram
![Instagram--Issue-269](https://user-images.githubusercontent.com/78985665/121823231-cc32c600-cc58-11eb-9a8a-8dd5ed6f4cac.png)

**Comment by Docebo-Netflix** [comment]
Instagram
![Instagram--Issue-269](https://user-images.githubusercontent.com/78985665/121823255-eff60c00-cc58-11eb-8a69-83f6e0d1686b.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter--Issue-269](https://user-images.githubusercontent.com/78985665/121834465-bbe41080-cc83-11eb-8cde-71dabf629433.png)

**Comment by Docebo-Netflix** [comment]
LinkedIn
![LinkedIn--Issue-269](https://user-images.githubusercontent.com/78985665/121834492-cb635980-cc83-11eb-8a85-4089f017d00f.png)

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook--Issue-269](https://user-images.githubusercontent.com/78985665/121834508-d322fe00-cc83-11eb-8c79-9c8a40c8279c.png)

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit--Issue-269](https://user-images.githubusercontent.com/78985665/121835315-cd2e1c80-cc85-11eb-8740-d97ef3b9367b.png)

**Comment by Docebo-Netflix** [comment]
Pinterest
![Pinterest---Issue-269](https://user-images.githubusercontent.com/78985665/121835324-d8814800-cc85-11eb-9fdb-bfe342ea0963.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman -4800
