### ISSUE TITLE
Good ol' infographic

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#270]
**Task**
What makes TNBC unique?
1. It's the fastest blockchain in the world 
2. Controlled by the community

We need this for Facebook, Twitter, Instagram, LinkedIn, Reddit and Pintrest

Due Date: 15.06.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by SwedishFisherman** [comment]
Instagram
![Instagram-01-Issue-270](https://user-images.githubusercontent.com/78985665/122122703-ffed2780-cde1-11eb-8280-75fd2bf86f3b.png)
![Instagram-02-Issue-270](https://user-images.githubusercontent.com/78985665/122122709-0085be00-cde2-11eb-84f5-bd17777c899a.png)

**Comment by SwedishFisherman** [comment]
Pinterest
![Pinterest-Issue-270](https://user-images.githubusercontent.com/78985665/122122742-0aa7bc80-cde2-11eb-8680-ec2e45897c72.png)

**Comment by SwedishFisherman** [comment]
Facebook
![Facebook-Issue-270](https://user-images.githubusercontent.com/78985665/122130600-bbb35480-cdec-11eb-8426-5b8b097c04bc.png)

**Comment by SwedishFisherman** [comment]
Twitter
![Twitter-Issue-270](https://user-images.githubusercontent.com/78985665/122139554-173a0e00-cdfe-11eb-8346-00714ffe14e5.png)

**Comment by SwedishFisherman** [comment]
LinkedIn
![LinkedIn--Issue-270](https://user-images.githubusercontent.com/78985665/122140992-4736e080-ce01-11eb-95cd-6927bfa244ce.png)

**Comment by SwedishFisherman** [comment]
Reddit
![Reddit---Issue-270](https://user-images.githubusercontent.com/78985665/122141281-da701600-ce01-11eb-9801-0afc6032b74e.png)

**Comment by Docebo-Netflix** [comment]
Here are the edits to the copy:

Instagram
![Instagram-01-Issue-270](https://user-images.githubusercontent.com/78985665/122257821-392aa380-ce85-11eb-8973-68128f9c0781.png)

![Instagram-02-Issue-270](https://user-images.githubusercontent.com/78985665/122257849-4051b180-ce85-11eb-927f-bf0352fe55bb.png)

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook-Issue-270](https://user-images.githubusercontent.com/78985665/122257970-624b3400-ce85-11eb-9d7b-5889392db174.png)

**Comment by Docebo-Netflix** [comment]
Linikedin
![LinkedIn--Issue-270](https://user-images.githubusercontent.com/78985665/122258007-6ecf8c80-ce85-11eb-8188-a963533201e1.png)

**Comment by Docebo-Netflix** [comment]
Pinterest
![Pinterest-Issue-270](https://user-images.githubusercontent.com/78985665/122258039-7727c780-ce85-11eb-9472-f08bdcc82209.png)

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit-Issue-270](https://user-images.githubusercontent.com/78985665/122258070-7f800280-ce85-11eb-81f5-b30c1e216033.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter--Issue-270](https://user-images.githubusercontent.com/78985665/122258151-93c3ff80-ce85-11eb-9b04-1aa8f2991e22.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman -4800
