### ISSUE TITLE
Discord Logo Graphic

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#271]
**Task**
Create a circular coin graphic that we can use as our Discord logo. It should be relatively simple (no small text or fine details) since it will be displayed as a small icon on the left Discord menu.

**Image Specs**
Size: 512 x 512
Format: PNG with transparent background

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

![coin](https://user-images.githubusercontent.com/8547538/122304553-46ae5080-ceba-11eb-96b4-9d0b65fe6f8d.jpg)

**Comment by SazidAhmed** [comment]
The Logo is here.
There are several versions with several colors.

https://drive.google.com/drive/folders/1pa-YM0NANdYNPor6Cm9oaFlQ86rmO_bC

My account number : a5dbcded3501291743e0cb4c6a186afa2c87a54f4a876c620dbd68385cba80d0

**Comment by stweyel** [comment]
![Logo](https://user-images.githubusercontent.com/25363181/122403347-99514080-cf7e-11eb-9a9f-8261f4f1ef2d.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due
---
User: @stweyel 
Amount: 800
