### ISSUE TITLE
Voice over 

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#272]
We are looking for a voice-over artist for our Animated blog video.

- Narrate our overview blog Information
- Match the music to your voice 

 This is the video that needs the audio re-recorded:

https://user-images.githubusercontent.com/8547538/122314958-f3de9400-cecd-11eb-8590-ec86cf9c3471.mp4

**Comment by hayderkharrufa** [comment]
Can you upload the video without the voice narration?

**Comment by hayderkharrufa** [comment]
WAV: https://drive.google.com/file/d/1uEWlhIfyehkGFKq5Ah9HPuxAb1wvdf9k/view?usp=sharing
MP3: https://drive.google.com/file/d/1YbNpOtS0t_avtumPCXGzrmHXiLNKlKm8/view?usp=sharing

a785e45bb8135caeff2bc34fa45a8e36213eed17421bcc0c2c03f4abb736cc11

**Comment by Chrisha1212** [comment]
@hayderkharrufa - 4000
