### ISSUE TITLE
Wordpress Blog Menu & Footer

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#273]
1. Create menu with internal and external links to thenewboston official website
2. Create Footer with links to all our social media 
3. Have dark and light mode to the whole website

This issue is for certain developers that have access to our Wordpress.

**Comment by IvanDanilov66** [comment]
Done! 
Account number : f1d85cecf85d7da38401dc58fabf1aa4294c881bb9d2c47642d1b460017f06cd

**Comment by bojan-ilijevski** [comment]
For approval and future references

![image](https://user-images.githubusercontent.com/58598872/122850568-ba62ba00-d30d-11eb-90d6-c1af6b358859.png)
