### ISSUE TITLE
Wordpress Blog Homepage

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#274]
1. Have one active banner with the latest post.
2. On the right sidebar have this week's Trending Posts
3. Have a carousel slider with Hand-picked Curated Posts
4. Have a Tech News section
5. A section for Hand-picked Weekly Posts
6. A slider for Futured Guides 
7. Most Recent Articles and a sidebar with Top Posts right now
8. Latest posts on our Instagram (Make it a sticky sidebar after you pass it)
9. Choose meta settings from your liking to all of these categories
10. Add Images to all the articles and make sure they are uncropped

**Comment by SazidAhmed** [comment]
This this a WordPress content management task?
Would you prove us the theme?
Or we have to develop a WordPress theme from scratch with all of these functionalities ?

**Comment by liefwerk** [comment]
Hi, I agree with Sazid that we need more information about these tasks. Should we make a plugin ? Do you use Gutenberg or are we going to make Shortcodes ?

Also the point n°9 isn't clear enough, could you reformulate/elaborate ? By meta settings do you mean taxonomies ?

**Comment by bojan-ilijevski** [comment]
We already have devs that have login info from our wordpress account. They have done most of these issues, I'm making them so they can get paid. That's why I didn't go much into detail with them.

**Comment by IvanDanilov66** [comment]
Done! 
Account number : f1d85cecf85d7da38401dc58fabf1aa4294c881bb9d2c47642d1b460017f06cd

**Comment by bojan-ilijevski** [comment]
For approval and future references

![image](https://user-images.githubusercontent.com/58598872/122850568-ba62ba00-d30d-11eb-90d6-c1af6b358859.png)
