### ISSUE TITLE
Wordpress Blog, Blog Page

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#275]
1. Have the latest posts in column of two 
2. On the right side have a sidebar with the top posts
3. Again, choose meta settings for all the categories

**Comment by IvanDanilov66** [comment]
Done! 
Account number : f1d85cecf85d7da38401dc58fabf1aa4294c881bb9d2c47642d1b460017f06cd

**Comment by bojan-ilijevski** [comment]
For approval and future references

![image](https://user-images.githubusercontent.com/58598872/122850568-ba62ba00-d30d-11eb-90d6-c1af6b358859.png)
