### ISSUE TITLE
Wordpress Blog Post page

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#276]
1. Have the Title, Image and all the text in centered middle
2. Have navigation like Previous Post, Next Post
3. Comment section, if someone wants to comment they're required to put email and username so we don't get bombarded by bots
4. Have a carousel with related posts
5. Again, choose meta settings for all the categories

**Comment by IvanDanilov66** [comment]
Done! 
Account number : f1d85cecf85d7da38401dc58fabf1aa4294c881bb9d2c47642d1b460017f06cd

**Comment by bojan-ilijevski** [comment]
For approval and future references

![image](https://user-images.githubusercontent.com/58598872/122850568-ba62ba00-d30d-11eb-90d6-c1af6b358859.png)
