### ISSUE TITLE
Project Logo for "tnbc Paper Wallet "

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#277]
Task
Create a logo for the **tnbc Paper Wallet** project that will be displayed alongside the project on
[thenewboston.com/projects](thenewboston.com/projects)

**Image Specs**
**Size:** 64 x 64
**Format:** JPG or PNG

**Links**

[**Project Proposal**](https://github.com/thenewboston-developers/Projects/issues/244)

**Comment by Toledit** [comment]
64x
![tnb paper wallet2-1](https://user-images.githubusercontent.com/27518021/122624097-65be0580-d0a7-11eb-974b-35562e4547f5.jpg)
295x
![tnb paper wallet h2-1](https://user-images.githubusercontent.com/27518021/122624120-766e7b80-d0a7-11eb-8eb8-5242af3dacf4.jpg)

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by stweyel** [comment]
![Paper Wallet](https://user-images.githubusercontent.com/25363181/122650155-95195480-d131-11eb-85ac-510a66461f24.png)
94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due
---
User: @Toledit 
Amount: 800
