### ISSUE TITLE
Wordpress Blog Menu Revision 

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#278]
Make a revision on the menu to look like the following image
![image](https://user-images.githubusercontent.com/58598872/122628077-4679a500-d0b4-11eb-9ba5-d1a146bab1c5.png)

**Comment by bojan-ilijevski** [comment]
For approval and future references

![image](https://user-images.githubusercontent.com/58598872/122850568-ba62ba00-d30d-11eb-90d6-c1af6b358859.png)

**Comment by IvanDanilov66** [comment]
Done!
Acc number: f1d85cecf85d7da38401dc58fabf1aa4294c881bb9d2c47642d1b460017f06cd

**Comment by IvanDanilov66** [comment]
@Chrisha1212

**Comment by Chrisha1212** [comment]
@IvanDanilov66 - 1000
