### ISSUE TITLE
Crypto Quote

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#279]
**Task**
The description will be "Build your dreams"

Due date: 06.22.2021
We need an infographic for: Facebook, Instagram, Twitter, Reddit, Linkedin and Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
working on this 🔨

**Comment by Toledit** [comment]
Facebook
![facebook #279](https://user-images.githubusercontent.com/27518021/122852736-c5bbe280-d319-11eb-8f85-ec18e2f169ab.jpg)

Instagram
![Instagram #279 ](https://user-images.githubusercontent.com/27518021/122852744-c9e80000-d319-11eb-8cb2-db22984c96df.jpg)

Twitter
![twitter-#279](https://user-images.githubusercontent.com/27518021/122852754-cf454a80-d319-11eb-9c31-a18874dbdd00.jpg)

Reddit
![Reddit #279](https://user-images.githubusercontent.com/27518021/122852760-d2403b00-d319-11eb-81b4-6bb0a3fb1d61.jpg)

Linkedin
![Linkedin #279](https://user-images.githubusercontent.com/27518021/122852769-d79d8580-d319-11eb-82d1-b779129f9b23.jpg)

Pinterest
![Pinterest-#267](https://user-images.githubusercontent.com/27518021/122852786-dff5c080-d319-11eb-9466-305d5549172a.jpg)

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by Chrisha1212** [comment]
@Toledit - 4000
