### ISSUE TITLE
Crypto Story

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#280]
**Task**
The description will be "Kristoffer Koch – Millionaire by Accident"

Due date: 06.22.2021
We need an infographic for: Facebook, Instagram, Twitter, Reddit, Linkedin, Pintrest and Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I’ll work on this issue

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook-Issue-280](https://user-images.githubusercontent.com/78985665/122701257-af226800-d201-11eb-8c64-71a13f82e704.png)

**Comment by Docebo-Netflix** [comment]
Instagram
![Instagram-Issue-280](https://user-images.githubusercontent.com/78985665/122701291-bfd2de00-d201-11eb-9371-169b2b019152.png)

**Comment by Docebo-Netflix** [comment]
Linkedin
![LinkedIn-Issue-280](https://user-images.githubusercontent.com/78985665/122701313-cd886380-d201-11eb-8f49-dec602295528.png)

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit-Issue-280](https://user-images.githubusercontent.com/78985665/122720855-d2aada00-d224-11eb-89a5-65559b30cc6d.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-Issue-280](https://user-images.githubusercontent.com/78985665/122720928-e7876d80-d224-11eb-894f-6b82f8f2c2bd.png)

**Comment by Docebo-Netflix** [comment]
Pinterest
![Pinterest-Issue-280](https://user-images.githubusercontent.com/78985665/122808571-eb95a880-d281-11eb-9078-3cd7e481157a.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman - 4800
