### ISSUE TITLE
Crypto Questions

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#281]
**Task**
The description will be "Did you know there are many ways crypto is mined? Proof of work, proof of stake and proof of value are three options out of many"

Due date: 06.22.2021
We need an infographic for: Facebook, Instagram, Twitter, Reddit, Linkedin, Pintrest and Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I am working on this one

**Comment by stoimenov00** [comment]
Facebook

<img width="1200" alt="#281 Facebook" src="https://user-images.githubusercontent.com/78659181/122767577-19d7b000-d2a3-11eb-805d-aa3d2dad5579.png">

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pineterest
<img width="1000" alt="#281 Pineterest" src="https://user-images.githubusercontent.com/78659181/122767702-34aa2480-d2a3-11eb-8542-d820ea0b5a81.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
<img width="1200" alt="#281 Twitter" src="https://user-images.githubusercontent.com/78659181/122767828-55727a00-d2a3-11eb-9ee3-b7bdbdfc9239.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Linkedin
<img width="1080" alt="#266 Linkedin" src="https://user-images.githubusercontent.com/78659181/122767901-658a5980-d2a3-11eb-921a-9e5087ff8a55.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
<img width="1200" alt="#281 Twitter" src="https://user-images.githubusercontent.com/78659181/122768178-a2eee700-d2a3-11eb-80ed-0d0efb63114d.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
<img width="1080" alt="#281 INSTAGRAM" src="https://user-images.githubusercontent.com/78659181/122768225-ae421280-d2a3-11eb-90dc-171e382b11bf.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![Reddit](https://user-images.githubusercontent.com/78659181/122769033-7d161200-d2a4-11eb-9b75-b71c4d523972.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoimenov00 - 4800

**Comment by Chrisha1212** [comment]
@stoimenov00 - 4800
