### ISSUE TITLE
Good 'ol infographic

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#282]
**Task**
The description will be " Difference between Banks and Crypto:
*Transfer speed
*Transaction fees
*Anonymity"

Due date: 06.22.2021
We need an infographic for: Facebook, Instagram, Twitter, Reddit, Linkedin, Pintrest and Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I will work on this one

**Comment by stoimenov00** [comment]
Linkedin
![Linkedin](https://user-images.githubusercontent.com/78659181/122838410-5680c700-d2f6-11eb-910b-f60f4626e07f.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Facebook
<img width="1200" alt="#281 Facebook (1)" src="https://user-images.githubusercontent.com/78659181/122838547-8c25b000-d2f6-11eb-9ec1-3f3628b8c3af.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pinterest
<img width="1000" alt="#281 Pineterest" src="https://user-images.githubusercontent.com/78659181/122838584-a3649d80-d2f6-11eb-9683-0852d7bb9cf1.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
![Twitter](https://user-images.githubusercontent.com/78659181/122838609-b4151380-d2f6-11eb-93fd-6e6994ae6832.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![Did you know there are many ways crypto is mined (3)](https://user-images.githubusercontent.com/78659181/122838688-e1fa5800-d2f6-11eb-9790-fdef1a18cbaa.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
![Instagram](https://user-images.githubusercontent.com/78659181/122838728-f8a0af00-d2f6-11eb-9475-bb24a6850e38.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79
