### ISSUE TITLE
Short Clip/GIF's

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#283]
**Task**
We need a giff or a short clip about how TNBC works.

We need this for Facebook, Twitter, LinkedIn and Instagram. Also the payment will be changed accordingly.

Due Date: 06.25.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I’ll start working on these

**Comment by Docebo-Netflix** [comment]
FB, Instagram
https://www.dropbox.com/s/oozey92zmb8bvh9/FB_Insta_1080x1080.mp4?dl=0

**Comment by Docebo-Netflix** [comment]
Twitter
https://www.dropbox.com/s/x79xaydft4za3o4/Twitter_1920x1080.mp4?dl=0

**Comment by Chrisha1212** [comment]
@SwedishFisherman -3000
