### ISSUE TITLE
Crypto Advice

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#284]
**Task**
The description will be "Crypto is changing everything: insurance, banking, corporate registration, ownership of assets"

Due date: 06.24.2021
We need an infographic for: Facebook, Instagram, Twitter, Reddit, Linkedin, Pintrest and Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
Facebook
<img width="1200" alt="#284 Facebook" src="https://user-images.githubusercontent.com/78659181/123462672-e2426e00-d5ea-11eb-9b20-d83c88b4aa18.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
<img width="1080" alt="#284 INSTAGRAM" src="https://user-images.githubusercontent.com/78659181/123462728-f71f0180-d5ea-11eb-8683-bfeaccc9b93f.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Linkedin
<img width="1080" alt="#284 Linkedin" src="https://user-images.githubusercontent.com/78659181/123462764-02722d00-d5eb-11eb-8338-98fcdda7029c.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pinterest
<img width="1000" alt="#284 Pineterest" src="https://user-images.githubusercontent.com/78659181/123462797-0aca6800-d5eb-11eb-81df-1f361c900172.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
<img width="1200" alt="#284 Twitter" src="https://user-images.githubusercontent.com/78659181/123462833-16b62a00-d5eb-11eb-84b2-3565a1cc7d3c.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![Reddit](https://user-images.githubusercontent.com/78659181/123462902-2afa2700-d5eb-11eb-8955-16f1b436199a.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoimenoVoo- 4800
