### ISSUE TITLE
Real world

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#285]
**Task**
This infographic will have a link to our newly launched blog and will say:  "How useful is crypto currency in the real world? "

Due to: 06.27.2021
We will need this for: Facebook, Instagram, Twitter, LinkedIn, Pintrest, Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I will work on this one

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit-Issue-285](https://user-images.githubusercontent.com/78985665/123555329-f6e14c00-d739-11eb-89bc-053e7ed4d403.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-Issue-285](https://user-images.githubusercontent.com/78985665/123555343-0a8cb280-d73a-11eb-99e8-12eb6fb64c85.png)

**Comment by Docebo-Netflix** [comment]
Pinterest
![Pinterest-Issue-285](https://user-images.githubusercontent.com/78985665/123713610-a21cfe80-d829-11eb-868b-a79a83f98d87.png)

**Comment by Docebo-Netflix** [comment]
Linkedin
![LinkedIn-Issue-285](https://user-images.githubusercontent.com/78985665/123756372-b4bb2600-d871-11eb-91c5-3005e56f6a66.png)

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook-Issue-285](https://user-images.githubusercontent.com/78985665/123867993-f5538780-d8e3-11eb-9678-977531c3e627.png)

**Comment by Docebo-Netflix** [comment]
Instagram
![Instagram-Issue-285](https://user-images.githubusercontent.com/78985665/123872695-4b2b2e00-d8ea-11eb-94f6-454fe92af23c.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman - 4800
