### ISSUE TITLE
Inspirational Post

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#286]
**Task**
The description will be: "Kingsley Advani – Selling All Worldly Possessions"

Due to: 06.27.2021
We will need this for: Facebook, Instagram, Twitter, LinkedIn, Pintrest, Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
Facebook
![Facebook #287](https://user-images.githubusercontent.com/27518021/123441224-47429780-d5dc-11eb-860c-0a1cdd92d2a6.jpg)

Instagram
![Instagram #287](https://user-images.githubusercontent.com/27518021/123441155-36922180-d5dc-11eb-8ba5-22576bfbb21d.jpg)

Twitter
![Twitter #287](https://user-images.githubusercontent.com/27518021/123441115-2bd78c80-d5dc-11eb-9cb8-204cfad974ef.jpg)

LinkedIn
![LinkedIn #287](https://user-images.githubusercontent.com/27518021/123441255-4dd10f00-d5dc-11eb-9c17-5c68c5d4e8ed.jpg)

Pinterest
![Pinterest-#287](https://user-images.githubusercontent.com/27518021/123441276-532e5980-d5dc-11eb-953a-c3fe44da6528.jpg)

Reddit
![reddit #287](https://user-images.githubusercontent.com/27518021/123441285-54f81d00-d5dc-11eb-8021-0b7db4ed80d2.jpg)

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by Chrisha1212** [comment]
@Toledit - 4800
