### ISSUE TITLE
Crypto tips and hacks

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#287]
**Task**
The description will be "Build, Learn, Grow"

Due to: 06.27.2021
We will need this for: Facebook, Instagram, Twitter, LinkedIn, Pintrest, Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![Build, Learn, Grow](https://user-images.githubusercontent.com/71756108/123282109-d80b6b80-d527-11eb-9fdb-4e57b77ea792.png)


size: 1080 x 1080px
🤞🏼 🤞🏼
A/c:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by clarkycode** [comment]
![Crypto Tips   Hacks](https://user-images.githubusercontent.com/76585195/123531429-204ca880-d737-11eb-8bd0-d04e1b2de252.png)
Original Photo by <a href="https://unsplash.com/@artic_studios?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Daniel Öberg</a> on <a href="https://unsplash.com/?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>

Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-Issue-287](https://user-images.githubusercontent.com/78985665/123532546-d9bd6680-d6c2-11eb-89b2-dd06e6703245.png)

Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit-Issue-285](https://user-images.githubusercontent.com/78985665/123918142-6e7cca00-d938-11eb-8079-16bc54cd1518.png)

Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by Docebo-Netflix** [comment]
Linkedin

![LinkedIn-Issue-285](https://user-images.githubusercontent.com/78985665/123918220-818f9a00-d938-11eb-807e-fc3ca3d6a617.png)


Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by Docebo-Netflix** [comment]
Pinterest
![Pinterest-Issue-285](https://user-images.githubusercontent.com/78985665/123920625-0380c280-d93b-11eb-9ec7-7ac2da4e349e.png)

**Comment by Chrisha1212** [comment]
@clarkycode -800
@SwedishFisherman - 4000

**Comment by Chrisha1212** [comment]
> ![Build, Learn, Grow](https://user-images.githubusercontent.com/71756108/123282109-d80b6b80-d527-11eb-9fdb-4e57b77ea792.png)
> 
> size: 1080 x 1080px
> 🤞🏼 🤞🏼
> A/c: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

@Prawesh-MAGNETIC-800. please your account number here

**Comment by Chrisha1212** [comment]
> Reddit
> ![Reddit-Issue-285](https://user-images.githubusercontent.com/78985665/123918142-6e7cca00-d938-11eb-8079-16bc54cd1518.png)
> 
> Account#
> a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

will be posted this in Insta

**Comment by Chrisha1212** [comment]
> > ![Build, Learn, Grow](https://user-images.githubusercontent.com/71756108/123282109-d80b6b80-d527-11eb-9fdb-4e57b77ea792.png)
> > size: 1080 x 1080px
> > 🤞🏼 🤞🏼
> > A/c: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd
> 
> @Prawesh-MAGNETIC-800. please your account number here

will be posted this in reddit
