### ISSUE TITLE
Crypto Question

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#288]
**Task**
The description will be "Do you have thenewboston account manager already?

Due to: 06.27.2021
We will need this for: Facebook, Instagram, Twitter, LinkedIn, Pintrest, Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I will work on this

**Comment by stoimenov00** [comment]
Facebook
<img width="1200" alt="#288 Facebook" src="https://user-images.githubusercontent.com/78659181/123452318-97baf480-d5de-11eb-9433-fe6c069ae5a4.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
<img width="1080" alt="#288 INSTAGRAM" src="https://user-images.githubusercontent.com/78659181/123452385-a7d2d400-d5de-11eb-8782-d367c78e681f.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pineterest
<img width="1000" alt="#288 Pinterest" src="https://user-images.githubusercontent.com/78659181/123452763-08faa780-d5df-11eb-9f75-1e0ebe418b94.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Linkedin
<img width="1080" alt="#288 Linkedin" src="https://user-images.githubusercontent.com/78659181/123452974-42cbae00-d5df-11eb-97e1-33e487920d05.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
<img width="1200" alt="#288 Twitter" src="https://user-images.githubusercontent.com/78659181/123453036-5414ba80-d5df-11eb-9897-ccbdf9aab15d.png">
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![reddit](https://user-images.githubusercontent.com/78659181/123453118-6ee72f00-d5df-11eb-9503-0692063df70c.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoimenov00 -4800
