### ISSUE TITLE
Motivational content

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#289]
**Task**
The description will be "Discover your potential with thenewboston."

Due to: 06.27.2021
We will need this for: Facebook, Instagram, Twitter, LinkedIn, Pintrest, Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I will work on this

**Comment by Prawesh-MAGNETIC** [comment]
![Discover](https://user-images.githubusercontent.com/71756108/123257024-4263e200-d50f-11eb-863f-89fc9f95794a.png)

size: 1080 x 1080

**Comment by xrviv** [comment]
![tnb](https://user-images.githubusercontent.com/44260360/123500428-9df9b100-d670-11eb-9f67-38a1041d4b18.png)
Original photo Unsplash License (FREE) 
Photo by [<a href="https://unsplash.com/@nadineshaabana?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Nadine Shaabana</a> on <a href="https://unsplash.com/s/photos/discover?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>](url)
  
Modifications by: Daniel Andrei Romero Garcia

**Comment by clarkycode** [comment]
![Motivational Content](https://user-images.githubusercontent.com/76585195/123519439-e7341a00-d6dd-11eb-9656-e4b7aeb402a1.png)

Original photo by [Ali Pazani](https://www.pexels.com/@alipazani) on [Pexels.com](https://www.pexels.com/photo/photo-of-woman-wearing-turtleneck-top-2777898/)

Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

**Comment by Chrisha1212** [comment]
@Prawesh-MAGNETIC -800
@clarkycode -800
@fongsai-yuk -800

**Comment by Chrisha1212** [comment]
@Prawesh-MAGNETIC -account number

**Comment by Prawesh-MAGNETIC** [comment]
> @Prawesh-MAGNETIC -account number

@Chrisha1212   my account number: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd
Sorry :D :)

**Comment by Chrisha1212** [comment]
> ![tnb](https://user-images.githubusercontent.com/44260360/123500428-9df9b100-d670-11eb-9f67-38a1041d4b18.png)
> Original photo Unsplash License (FREE)
> Photo by [Nadine Shaabana](https://unsplash.com/@nadineshaabana?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/discover?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)
> 
> Modifications by: Daniel Andrei Romero Garcia

**Comment by Chrisha1212** [comment]
> > ![tnb](https://user-images.githubusercontent.com/44260360/123500428-9df9b100-d670-11eb-9f67-38a1041d4b18.png)
> > Original photo Unsplash License (FREE)
> > Photo by [Nadine Shaabana](https://unsplash.com/@nadineshaabana?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/discover?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)
> > Modifications by: Daniel Andrei Romero Garcia

@fongsai-yuk whats your account number?

**Comment by xrviv** [comment]
Hi, :) 

89e2f209951ab820aecca89e3af91093ca5e3a42387b6fa06cdf5dc30d57649e

**Comment by Chrisha1212** [comment]
> ![Discover](https://user-images.githubusercontent.com/71756108/123257024-4263e200-d50f-11eb-863f-89fc9f95794a.png)
> 
> size: 1080 x 1080

@bojan-ilijevski  this one is for facebook and insta

**Comment by Chrisha1212** [comment]
> ![Motivational Content](https://user-images.githubusercontent.com/76585195/123519439-e7341a00-d6dd-11eb-9656-e4b7aeb402a1.png)
> 
> Original photo by [Ali Pazani](https://www.pexels.com/@alipazani) on [Pexels.com](https://www.pexels.com/photo/photo-of-woman-wearing-turtleneck-top-2777898/)
> 
> Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

this one will be for Twitter and Linked in

**Comment by Chrisha1212** [comment]
> > > ![tnb](https://user-images.githubusercontent.com/44260360/123500428-9df9b100-d670-11eb-9f67-38a1041d4b18.png)
> > > Original photo Unsplash License (FREE)
> > > Photo by [Nadine Shaabana](https://unsplash.com/@nadineshaabana?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/discover?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)
> > > Modifications by: Daniel Andrei Romero Garcia
> 
> @fongsai-yuk whats your account number?

for pinterest and reddit
