### ISSUE TITLE
Have project logos created

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#290]
Have project logos created for any of these projects that are missing logos https://thenewboston.com/projects You can use them "Project Logo" template here https://github.com/thenewboston-developers/Marketing/issues/new/choose

Once they are all completed, message me ( @buckyroberts ) and I can add them to the website.

**Comment by stweyel** [comment]
What about these closed issue logos. Are they all rejected?

https://github.com/thenewboston-developers/Marketing/issues/248
https://github.com/thenewboston-developers/Marketing/issues/246
https://github.com/thenewboston-developers/Marketing/issues/245
https://github.com/thenewboston-developers/Marketing/issues/235
https://github.com/thenewboston-developers/Marketing/issues/234

...

**Comment by manishram** [comment]
@stweyel paid!!
