### ISSUE TITLE
Wordpress Blog

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#291]
1. Fix this so the underline doesn't extend passed the text.
![image](https://user-images.githubusercontent.com/58598872/123530499-42283a00-d6fb-11eb-9057-2e9546c2b26b.png)
2. Display these images as equal heights 
![image](https://user-images.githubusercontent.com/58598872/123530506-61bf6280-d6fb-11eb-9dc4-8f1608494481.png)

*This is for the wordpress devs only

**Comment by IvanDanilov66** [comment]
Done !
Acc number : f1d85cecf85d7da38401dc58fabf1aa4294c881bb9d2c47642d1b460017f06cd
