### ISSUE TITLE
Create App Icon for Mobile App

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#292]
**Task**
Create an app icon for the mobile app.

**Image Specs**
Size: 1080 x 1080px
Format: PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Thewimpykid18** [comment]
![thenewboston](https://user-images.githubusercontent.com/34057001/123542768-180d6100-d769-11eb-8ab2-834010f4621e.png)

**Comment by ThejeshBommisetty** [comment]
![mobile app logo](https://user-images.githubusercontent.com/47267710/123555030-c5e83200-d7a0-11eb-86da-c7a6e87c0e81.png)

Account Number : adf0b5529eb8dc52ff636f1fd8c43d1d59e077a88def0014476a03d6cd301e26

**Comment by Danks13** [comment]
![Untitled-1](https://user-images.githubusercontent.com/86719468/123949201-35754180-d99a-11eb-9c05-f8b0d82ef144.png)

**Comment by mwelwankuta** [comment]
![NewBostonAppIcon](https://user-images.githubusercontent.com/64831126/123974391-6bea9680-d971-11eb-8445-974069a5e398.png)

**Comment by mwenku** [comment]
Account Number: 34830d09415a8479c28723528e87eb5e20721addac21522255b04b5baa8046c5

![TheNewBostonAppIcon](https://user-images.githubusercontent.com/64831126/124250878-24cbe500-dada-11eb-845c-f4816083e856.png)

**Comment by Chrisha1212** [comment]
@mwelwankuta - 800

**Comment by Chrisha1212** [comment]
@mwelwankuta - can you include your account number?

**Comment by mwenku** [comment]
> @mwelwankuta - can you include your account number?

@Chrisha1212  I have added the account number

**Comment by stweyel** [comment]
@Chrisha1212 is this closed?

**Comment by mwenku** [comment]
> @mwelwankuta - 800

Account Number : 34830d09415a8479c28723528e87eb5e20721addac21522255b04b5baa8046c5

**Comment by NotDinnerbonee** [comment]
![Uploading image_2021-07-05_091556.png…]()

**Comment by NotDinnerbonee** [comment]
![tnbmobilelogo](https://user-images.githubusercontent.com/86939817/124414440-7a222380-dd72-11eb-834c-bdfaa8152f7c.png)

**Comment by stweyel** [comment]
https://github.com/thenewboston-developers/Marketing/issues/292#issuecomment-873307973 ?
