### ISSUE TITLE
Reddit banner graphic

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#295]
**Task**
Create a new banner for our subreddit here https://www.reddit.com/r/thenewboston/

**Image Specs**
Size: 4,000 x 128px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![Building a Better Economy](https://user-images.githubusercontent.com/71756108/124096731-7cd1ff80-da78-11eb-8d02-0983b08132e5.png)


![thenewboston](https://user-images.githubusercontent.com/71756108/124062848-22707900-da4f-11eb-9a89-fbbef8416ce8.png)


![thenewboston (2)](https://user-images.githubusercontent.com/71756108/124063164-d40faa00-da4f-11eb-8b1b-bc12d420c6e2.png)



size: 4000 x 128

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due
---
User: @Prawesh-MAGNETIC 
Amount: 1000

**Comment by Chrisha1212** [comment]
@Prawesh-MAGNETIC  account number?

**Comment by Prawesh-MAGNETIC** [comment]
> @Prawesh-MAGNETIC account number?

@Chrisha1212   my account number: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd
Sorry, :D :)
