### ISSUE TITLE
Informative Video

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#296]
**Task**
Attached Voice over to the Video

**Background**

- Match the music to the Narrator Voice **https://github.com/thenewboston-developers/Marketing/issues/272**

**Comment by Prawesh-MAGNETIC** [comment]
https://user-images.githubusercontent.com/71756108/124065282-133ffa00-da54-11eb-8f00-b9322917321f.mp4

**Comment by Chrisha1212** [comment]
>  VoiceOver.mp4

@Prawesh-MAGNETIC -800

**Comment by Chrisha1212** [comment]
>  VoiceOver.mp4

@Prawesh-MAGNETIC  account number?

**Comment by Prawesh-MAGNETIC** [comment]
> > VoiceOver.mp4
> 
> @Prawesh-MAGNETIC account number?

@Chrisha1212 my account number: b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd
Sorry,  :D :)
