### ISSUE TITLE
Now Hiring Graphic for "Technical Recruiter"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#297]
**Task**
Create a graphic that will be used on social media to help recruiting for our "Technical Recruiter" position.

**Job Post**
To apply: https://thenewboston.com/openings/Engineering/senior-python-django-developer

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Hiring Technical Recruiter](https://user-images.githubusercontent.com/76585195/124301917-0fff5800-db93-11eb-96ff-a4e20a5594a3.png)

**Comment by Prawesh-MAGNETIC** [comment]
![Technical Recruiter](https://user-images.githubusercontent.com/71756108/124315719-fad5f980-db91-11eb-8015-564f635cbcaa.png)



A/c:  b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by stweyel** [comment]
![social tech recruit](https://user-images.githubusercontent.com/25363181/124352512-d06f5500-dc00-11eb-92c9-78a9eaa05767.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by Chrisha1212** [comment]
@clarkycode - 800
