### ISSUE TITLE
Now Hiring Graphic for "Senior Python Developer"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#298]
**Task**
Create a graphic that will be used on social media to help recruiting for our "Senior Python Developer" position.

**Job Post**
To apply: https://thenewboston.com/openings/Community/technical-recruiter

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![Senior Python Developer](https://user-images.githubusercontent.com/71756108/124293672-86409200-db74-11eb-9bd3-29ae00f9b2a1.png)


A/C:  b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Hiring Python Developer](https://user-images.githubusercontent.com/76585195/124340755-035a1e80-dbea-11eb-9a89-4ef16ccc1547.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-Issue-298](https://user-images.githubusercontent.com/78985665/124308234-d809fd80-db1d-11eb-8420-d9c0d2bb0baf.png)

Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by Docebo-Netflix** [comment]
Pinterest
![Pinterest-Issue-298](https://user-images.githubusercontent.com/78985665/124308292-f40d9f00-db1d-11eb-86bf-3f72dfe12515.png)


Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by Docebo-Netflix** [comment]
FB, Instagram, LinkedIn
![FB_Insta_Linkedin-Issue-298](https://user-images.githubusercontent.com/78985665/124308381-0f78aa00-db1e-11eb-9b90-2e2efa0b2027.png)


Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by stweyel** [comment]
![social pyth dev](https://user-images.githubusercontent.com/25363181/124336858-1b0cb500-dba0-11eb-850d-09c10bfe57b2.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by Chrisha1212** [comment]
@clarkycode - 800
@SwedishFisherman - 800
