### ISSUE TITLE
Now Hiring Graphic for "Head of Human Resources"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#299]
**Task**
Create a graphic that will be used on social media to help recruiting for our "Head of Human Resources" position.

**Job Post**
To apply: https://thenewboston.com/openings/Community/human-resources-head

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Hiring Head of Human Resources 2](https://user-images.githubusercontent.com/76585195/124362493-ca608f00-dc67-11eb-8c15-27f30c8c8c8a.png)

**Comment by stweyel** [comment]
![social human res](https://user-images.githubusercontent.com/25363181/124334783-7dfa4e00-db98-11eb-897f-a0e4facf1013.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by Chrisha1212** [comment]
@clarkycode - 800

**Comment by Chrisha1212** [comment]
@clarkycode - 800
