### ISSUE TITLE
Now Hiring Graphic for "Recruiting Lead"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#300]
**Task**
Create a graphic that will be used on social media to help recruiting for our "Recruiting Lead" position.

**Job Post**
To apply: https://thenewboston.com/openings/Community/recruiting-lead

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![Recruiting Lead](https://user-images.githubusercontent.com/71756108/124306474-120dea80-db84-11eb-9c82-b1997c09f839.png)



A/c:    b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Hiring Recruiting Lead](https://user-images.githubusercontent.com/76585195/124309740-c5370d80-db9d-11eb-83f2-9a18941a7bae.png)

**Comment by stweyel** [comment]
![social recruit lead3](https://user-images.githubusercontent.com/25363181/124333957-f14e9080-db95-11eb-98a6-9da8dcfed55e.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by Chrisha1212** [comment]
@clarkycode - 800
