### ISSUE TITLE
Graphic to get Colfax back on the team

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#301]
**Task**
Create a graphic so fantastic, so marvelous, that it will convince Colfax to rejoin the team. Here is his LinkedIn photo. He didn't give me "explicit permission" to use it, but he probably would so feel free to include it in the graphic in any way:

![1517425547501](https://user-images.githubusercontent.com/8547538/124223061-d6a5ea00-dab7-11eb-996a-f0d506a7fa4f.jpeg)

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![COLFAX](https://user-images.githubusercontent.com/71756108/124277998-550b9600-db63-11eb-80ab-212e77618d1f.png)

**Comment by Prawesh-MAGNETIC** [comment]
![TheEconomyBuilder](https://user-images.githubusercontent.com/71756108/124280262-1a572d00-db66-11eb-9116-32b7eb4f6345.png)


Love and Respect to Colfax: The Economy Builder.

**Comment by hussu010** [comment]
me thinking of making a meme to get Colfax back:
![download](https://user-images.githubusercontent.com/55182298/124285232-75405280-db6d-11eb-9148-72abdc5b3e85.png)

I talk memes no graphics :(
![download (1)](https://user-images.githubusercontent.com/55182298/124286122-57bfb880-db6e-11eb-8ffc-0fc755467ecb.png)

Violence ain't answer but still
![download (2)](https://user-images.githubusercontent.com/55182298/124286379-9a819080-db6e-11eb-98aa-e4fcbd150777.png)

The summary
![download (3)](https://user-images.githubusercontent.com/55182298/124289451-116c5880-db72-11eb-9656-b84cfb3a1382.png)

**Comment by Prawesh-MAGNETIC** [comment]
![ElonMusk Just Tweeteeeeeddd](https://user-images.githubusercontent.com/71756108/124310841-67e59100-db8a-11eb-8e0d-6df9686053f8.png)


It's a tweet by ElonMusk!

**Comment by stweyel** [comment]
some background info would be nice...

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @Prawesh-MAGNETIC 
Amount: 1600

and

User: @hussu010 
Amount: 1600

**Comment by Prawesh-MAGNETIC** [comment]
> @Chrisha1212 Payment Due
> 
> User: @Prawesh-MAGNETIC
> Amount: 1600
> 
> and
> 
> User: @hussu010
> Amount: 1600


My A/c no:  b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd   :pray: :partying_face: :magnet:

**Comment by Chrisha1212** [comment]
@hussu010 what's your account number?

**Comment by hussu010** [comment]
> @hussu010 what's your account number?

22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by manishram** [comment]
Just a backup in case **Colfax** didn't get convinced with the previous ones. 😂😂

![colfax](https://user-images.githubusercontent.com/22790904/124350789-5943bc00-dc14-11eb-8675-82d85b1697ea.PNG)
