### ISSUE TITLE
Blog post tickets

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#302]
Please write up blog post tickets for these blog topics. They should work well in targeting our audience in Nigeria and the Philippines. Also, you can use [this as a template](https://github.com/thenewboston-developers/Marketing/blob/master/.github/ISSUE_TEMPLATE/blog-post.md). 

1. When did cryptocurrency start ?
2. Can cryptocurrency crash ?
3. How to buy cryptocurrency ?
4. Are cryptocurrency taxed ?
5. How is cryptocurrency created ?
6. Which cryptocurrency should I invest in ?
7. Where cryptocurrency is stored ?
8. 3 cryptocurrencies with potential
9. Can crypto-currencies be hacked?
10. Crypto-currency without fees: what you need to know!
11. Cryptocurrency vs token
12. Cryptocurrency vs stocks
13. Comparative : crypto currency vs traditional bank currency
14. All about the crypto-currency ban in Nigeria
15. How does cryptocurrency trading work ?
16. Which trading platform is best for Cryptocurrency?
17. How does Cryptocurrency trading work?
18. Top 9 Cryptocurrency exchange list.
19. Is Cryptocurrency regulated in the Philippines?
20. How does cryptocurrency value increase?
21. What is the best crypto exchange in the Philippines?
22. 10 ways to start cryptocurrency trading in 2021.
23. Are cryptocurrency exchanges regulated?
24. Tips to make money with Cryptocurrency.
25. Are there day trading limits on Crypto?
26. The best Crypto exchanges in Nigeria.
27. Is cryptocurrency a good investment?
28. The most popular cryptocurrency apps in Nigeria.
29. Tips to buy Cryptocurrency in the Philippines?
30. How can I trade Cryptocurrency in the Philippines?
31. The best Crypto trading platforms in Nigeria.
32. Which cryptocurrency is best to invest in 2021?
33. Cryptocurrency trading strategy for beginners.
34. The top 10 Cryptocurrencies in 2021.
35. 5 Crypto companies in the Philippines you should know.
36. Which Crypto has the most transactions per day?
37. 5 Reasons why Cryptocurrency is the future of finance.
38. The 5 benefits of trading Cryptocurrencies.
39. Step by step guide to investing in Cryptocurrency.
40. The top 3 things to consider when buying cryptocurrency.

**Comment by shalombrain** [comment]
Hi @buckyroberts @Chrisha1212 how can I work on this task?

I'd love to be assigned to it and also love to know how much would be paid for each blog?

**Comment by buckyroberts** [comment]
Sure @shalombrain - that would be great :-) We don't have the individual issues written up for them yet. When we do you can leave a comment with your final post and your account number there. Here are the criteria for each post:

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

We are rewarding 1,000 TNBC/post.

**Comment by shalombrain** [comment]
Okay, I will start working on them ASAP, do I have to be assigned or something?

**Comment by Chrisha1212** [comment]
> Okay, I will start working on them ASAP, do I have to be assigned or something?

I'll make a github issue for each one check it on Marketing Task
