### ISSUE TITLE
Blog Post: When did cryptocurrency start ?

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#303]
**Blog Topic**
Explain how cryptocurrency started in the early 1980s

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by shalombrain** [comment]
On it

**Comment by shalombrain** [comment]
Hey, @Chrisha1212 should the post be sent in doc format, pdf, or posted as a regular text?
@buckyroberts

**Comment by shalombrain** [comment]
https://docs.google.com/document/d/1gvq9zFRnztszsKVOUd9_RoHwdLpOiYhk1Zu79z__gLY/edit?usp=sharing

**Comment by shalombrain** [comment]
https://docs.google.com/document/d/1gvq9zFRnztszsKVOUd9_RoHwdLpOiYhk1Zu79z__gLY/edit?usp=sharing

CC: @Chrisha1212 @buckyroberts

**Comment by Chrisha1212** [comment]
> https://docs.google.com/document/d/1gvq9zFRnztszsKVOUd9_RoHwdLpOiYhk1Zu79z__gLY/edit?usp=sharing
> 
> CC: @Chrisha1212 @buckyroberts

What's your account number?

**Comment by shalombrain** [comment]
51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by Chrisha1212** [comment]
@shalombrain- 1000
