### ISSUE TITLE
Blog Post: All about the crypto-currency ban in Nigeria

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#316]
**Blog Topic**
Explain the reason why the government ban crypto-currency in Nigeria.
**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by C3lxius** [comment]
@Chrisha1212 I'd like to work on this task. I'm Nigerian, so at the heart of the issue and very well versed in essay and content writing.

**Comment by Chrisha1212** [comment]
> @Chrisha1212 I'd like to work on this task. I'm Nigerian, so at the heart of the issue and very well versed in essay and content writing.

Sure

**Comment by C3lxius** [comment]
Below is the Google doc link
 https://docs.google.com/document/d/1Yy87FLC_qOpFhASgNQsG-HyAuipEWaIIhnBHZUHej4Y/edit?usp=drivesdk

TNBC Account: e7a94744dc66b24e679d2f0d118c64ba168c700c7896f21bc05884f03f54e0c0

Thanks.

**Comment by Chrisha1212** [comment]
@C3lxius  requesting for edit access

**Comment by C3lxius** [comment]
Granted.

**Comment by C3lxius** [comment]
Hi... so... was there supposed to be some sort of reward for writing this?😇😇

**Comment by Docebo-Netflix** [comment]
@Chrisha1212 @C3lxius Did you need a few images for this blog post?
