### ISSUE TITLE
Blog Post: How does cryptocurrency trading work ?

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#317]
**Blog Topic**
Explain how trading works in cryptocurrency.
**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by C3lxius** [comment]
Hi there. I would like to work on this.

**Comment by Chrisha1212** [comment]
> Hi there. I would like to work on this.

Sure :)

**Comment by Chrisha1212** [comment]
> Hi there. I would like to work on this.

Hi are you still working on this?

**Comment by C3lxius** [comment]
I actually forgot about this... Sorry.
But yeah... I'll do it and drop the link In a few..👌🏾

**Comment by Chrisha1212** [comment]
> I actually forgot about this... Sorry.
> But yeah... I'll do it and drop the link In a few..👌🏾

Alright do you have discord account?

**Comment by C3lxius** [comment]
Again... sorry. I've been away for some personal stuff. Is this still open? And yes, i do have a discord account.
