### ISSUE TITLE
Blog Post: Top 9 Cryptocurrency exchange list.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#319]
**Blog Topic**
Write down the top 9 cryptocurrency exchange explain each one.
**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by stephen1204paul** [comment]
Hi can I work on this?

**Comment by Chrisha1212** [comment]
> Hi can I work on this?

@stephen1204paul Yes :)
