### ISSUE TITLE
Blog Post: What is the best crypto exchange in the Philippines?

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#322]
**Blog Topic**
find out what is the best crypto exchange in the Philippines and How does it work.

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by MayeDay** [comment]
Hello is this still open?

**Comment by Chrisha1212** [comment]
@MayeDay Yes :)
