### ISSUE TITLE
Blog Post: Are cryptocurrency exchanges regulated?

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#324]
**Blog Topic**
Explain if all cryptocurrency exchanges regulated rt cryptocurrency trading in 2021.

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by miladmohammadint** [comment]
@Chrisha1212 @buckyroberts This is my first time participating so apologies in advance if I violate any norms. Please see my blog draft below.
[Are Cryptocurrency Exchanges Regulated?.pdf](https://github.com/thenewboston-developers/Marketing/files/7385707/Are.Cryptocurrency.Exchanges.Regulated.pdf)
