### ISSUE TITLE
Blog Post: Tips to make money with Cryptocurrency.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#325]
**Blog Topic**
Explain different ways to make money with cryptocurrency.

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by xrviv** [comment]
- Writer: Daniel Andrei R. Garcia
- Proofread: ______________
- Date Written: 7/25/2021
- Number of Words: 853
- Read Time: Est. 3 minutes 54 seconds
- Link to Article: https://docs.google.com/document/d/1tRD1eNSGFkNKCQF82GyZSMkaz1bAI8GVtbNxJKBI15M/edit?usp=sharing
- TNB Account #: 89e2f209951ab820aecca89e3af91093ca5e3a42387b6fa06cdf5dc30d57649e
- Image Attribution: [Unsplash License](https://unsplash.com/license) (Free to Use Commercially, No Attribution Required)

![cover](https://user-images.githubusercontent.com/44260360/126902227-77fdfeb8-1bf7-4d0c-9616-5465a987fd73.jpg)
