### ISSUE TITLE
Blog Post: The most popular cryptocurrency apps in Nigeria.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#329]
**Blog Topic**
what is the most popular cryptocurrency apps in Nigeria. Explain how does it work?

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by AliHaider20** [comment]
What is the meaning of label 1000?

**Comment by hussu010** [comment]
@AliHaider20 it means 1000 TNBC will be paid once there's a blog post written and ready to be published.

**Comment by AliHaider20** [comment]
> @AliHaider20 it means 1000 TNBC will be paid once there's a blog post written and ready to be published.

Got it. Thanks 👍.

**Comment by Chrisha1212** [comment]
> > @AliHaider20 it means 1000 TNBC will be paid once there's a blog post written and ready to be published.
> 
> Got it. Thanks 👍.

Are you working on it?

**Comment by AliHaider20** [comment]
> 
> 
> 
> > > @AliHaider20 it means 1000 TNBC will be paid once there's a blog post written and ready to be published.
> > 
> > Got it. Thanks 👍.
> 
> Are you working on it?

Right now not working. Busy in exams.

**Comment by Gstar219** [comment]
> **Blog Topic**
> what is the most popular cryptocurrency apps in Nigeria. Explain how does it work?
> 
> **Blog Criteria**
> 
> * Must be 600-800 words
> * Please do research to make sure the information stated is thoroughly accurate
> * Please make sure content is understandable to someone who knows nothing about crypto
> * Must be proofread by another person
> * Must not contain copyrighted material
> * Include read time
> * Include who wrote it
> * Include title
> * Include secondary titles within article so people can see how information is chunked out

Is this still open?
