### ISSUE TITLE
Blog Post: How can I trade Cryptocurrency in the Philippines?

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#331]
**Blog Topic**
List down and explain how people can trade cryptocurrency in the Philippines.

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by markmendozadev** [comment]
Can I work on this? :D can I talk about any other platform?

**Comment by markmendozadev** [comment]
Hey not sure if this is what you're looking for but can you check? 
https://docs.google.com/document/d/1J3F7Zl0MeSUf4l8bADI8rC6UL0_Co5qJPjzgex1lS1U/edit?usp=sharing

**Comment by tspearing** [comment]
Hi @markmendozadev, I've passed these comments on to the marketing team. We'll get back to you.

**Comment by Chrisha1212** [comment]
> Hey not sure if this is what you're looking for but can you check?
> https://docs.google.com/document/d/1J3F7Zl0MeSUf4l8bADI8rC6UL0_Co5qJPjzgex1lS1U/edit?usp=sharing

Hey @markmendozadev, can check the docs? let ass know if the changes resolved already.

**Comment by MayeDay** [comment]
Is this still open?

**Comment by Chrisha1212** [comment]
@MayeDay Yes :)
