### ISSUE TITLE
Blog Post: Cryptocurrency trading strategy for beginners.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#333]
**Blog Topic**
List down what are the strategies to trade for beginners?

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by eladcrock** [comment]
Hi, Is this still available?

**Comment by Chrisha1212** [comment]
> Hi, Is this still available?

Hey @eladcrock yes it is. can you work on it?

**Comment by eladcrock** [comment]
Sure can! Thanks I’ll get to work on it
