### ISSUE TITLE
Blog Post: The top 10 Cryptocurrencies in 2021.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#334]
**Blog Topic**
List down the Top 10 cryptocurrencies and explain some updates on why they are in the top 10.
**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by YashovardhanSingh** [comment]
@Chrisha1212 https://blogs-for-tnb.blogspot.com/2021/09/the-top-10-cryptocurrencies-in-2021.html
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by YashovardhanSingh** [comment]
is this one done?

**Comment by rpleau** [comment]
I would be interested in contributing this task.  Also, I think it should address The New Boston Coin unique selling proposition/value in the marketplace.
Please let me know.
With best regards,
Richard

**Comment by YashovardhanSingh** [comment]
@Chrisha1212 Is my blog used?

**Comment by Chrisha1212** [comment]
@YashovardhanSingh  lemme check.
