### ISSUE TITLE
Blog Post: 5 Crypto companies in the Philippines you should know.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#335]
**Blog Topic**
List down five crypto companies in the Philippines and explain what are those and who are they?

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by ethelmangao** [comment]
Document: https://docs.google.com/document/d/169s09Ral-UdQ0FjGKKMeGM4ks93z0gZo9FLvoJItSzM/edit?usp=sharing

Account Number: f94727c95a003538f3d552435e14ae21565539db149d31590937d042767fe1e2

**Comment by Chrisha1212** [comment]
@ethelmangao - 1000
