### ISSUE TITLE
Blog Post: 5 Reasons why Cryptocurrency is the future of finance.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#337]
**Blog Topic**
Give us 5 Reasons why Cryptocurrency is the future of finance. explain why?

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by nicocrozier** [comment]
Still available?

**Comment by Chrisha1212** [comment]
> Still available?
Yes @nicocrozier

**Comment by nicocrozier** [comment]
https://github.com/nicocrozier/Activity-Reports/blob/master/5%20reasons%20why%20crypto%20is%20the%20future%20of%20finance.pdf


Done

8d35c77a400fdf86ce990caaa91b9316a9b30a6bd238613070515603be148339

**Comment by nicocrozier** [comment]
Was my Blog post not sufficient? I can edit if needed. @Chrisha1212

**Comment by Chrisha1212** [comment]
> Was my Blog post not sufficient? I can edit if needed. @Chrisha1212

Will review it :)

**Comment by WillyanSantosMoreira** [comment]
Can I work on this, please?

**Comment by WillyanSantosMoreira** [comment]
Can I work on this, please?
