### ISSUE TITLE
Blog Post: Step by step guide to investing in Cryptocurrency.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#339]
**Blog Topic**
List down the Step by step guide to investing in Cryptocurrency.

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by xrviv** [comment]
Is 800 words a hard limit? I'll try to squeeze the content within, but I'm afraid it may become a little thin.

**Comment by xrviv** [comment]
**Writer:** Daniel Andrei Romero Garcia
**Word** Count: 761
**Read time**: 3 minutes 48 seconds
**Proofread by**: Still looking
**Images license:** Unsplash License (similar to Creative Commons 0 License. No Attribution Required. No restrictions)

https://docs.google.com/document/d/1UhI0J0QCq78ffpGNZsQ7sbzozugSvck4Vy7H5CQvoLs/edit?usp=sharing

Account Number: 89e2f209951ab820aecca89e3af91093ca5e3a42387b6fa06cdf5dc30d57649e

**Comment by Chrisha1212** [comment]
> **Writer:** Daniel Andrei Romero Garcia
> **Word** Count: 761
> **Read time**: 3 minutes 48 seconds
> **Proofread by**: Still looking
> **Images license:** Unsplash License (similar to Creative Commons 0 License. No Attribution Required. No restrictions)
> 
> https://docs.google.com/document/d/1UhI0J0QCq78ffpGNZsQ7sbzozugSvck4Vy7H5CQvoLs/edit?usp=sharing
> 
> Account Number: 89e2f209951ab820aecca89e3af91093ca5e3a42387b6fa06cdf5dc30d57649e

Nice Work @fongsai-yuk

**Comment by Chrisha1212** [comment]
@fongsai-yuk -1000
