### ISSUE TITLE
Blog Post: The top 3 things to consider when buying cryptocurrency.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#340]
**Blog Topic**
List down the top 3 things to consider when buying cryptocurrency.
**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by Gstar219** [comment]
Good day, This is a link to the task above. 
https://docs.google.com/document/d/176bDC7el3C8xFCQmTjju1pJ2Ck2S3RIw9oRi5dZOllA/edit?usp=sharing

**Comment by Gstar219** [comment]
It an Orginal Content is written by me Makinde Gbolahan Samuel 
Discord name: Makinde Gbolahan #0268
Proofread by Olowu Daniel

**Comment by Gstar219** [comment]
Good Day here is the Doc Link to the blog Post above
https://docs.google.com/document/d/176bDC7el3C8xFCQmTjju1pJ2Ck2S3RIw9oRi5dZOllA/edit?usp=sharing

**Comment by xrviv** [comment]
**Writer:** Daniel Andrei Romero Garcia
**Word Count:** 804
**Read time:** 3 minutes 57 seconds
**Proofread by:** Still looking
**Images license:** Unsplash License (_similar to Creative Commons 0 License. No Attribution Required. No restrictions_)

https://docs.google.com/document/d/1Xv6x-Y-Xrp_MgpZDg3xF2qUL-ZPeFd7KTseRHcsTKTc/edit?usp=sharing

**Question**: By the way, where do we publish this? Should I publish on my own blog and link to https://thenewboston.com ? Thanks.
**Account Number:** 89e2f209951ab820aecca89e3af91093ca5e3a42387b6fa06cdf5dc30d57649e

**Comment by manishram** [comment]
@fongsai-yuk we'll publish your blog to our blog website: blog.thenewboston.com

**Comment by xrviv** [comment]
Awesome! And nice to meet you!

**Comment by Chrisha1212** [comment]
@fongsai-yuk -1000

**Comment by xrviv** [comment]
Thank you!
