### ISSUE TITLE
Still very early

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#341]
**Task**
The description will be "Learning about crypto in 2021 is like learning about the internet in 1994. This is just the beginning."
Due to: 07.15.2021
We will need this for: Facebook, Instagram, Twitter, LinkedIn, Pintrest, Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
I'll start working on this issue

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook-Issue-341](https://user-images.githubusercontent.com/78985665/125577164-826ea668-fef6-406c-9fc7-81fd9fa69cc4.png)

Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by Docebo-Netflix** [comment]
Instagram
![Instagram-Issue-341](https://user-images.githubusercontent.com/78985665/125577256-00b691a5-c1f3-4863-80c7-6dfdd1e92bd7.png)

**Comment by Docebo-Netflix** [comment]
Linkedin
![LinkedIn-Issue-341](https://user-images.githubusercontent.com/78985665/125577329-5b0bc81b-e01b-4f23-a724-01bd5fbb6d6f.png)

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit-Issue-341](https://user-images.githubusercontent.com/78985665/125768962-c6fb9328-7bae-407e-8434-66af35b53b26.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-Issue-341](https://user-images.githubusercontent.com/78985665/125770276-6013a94d-a5ed-427f-80a3-c4a745b6c429.png)

**Comment by Docebo-Netflix** [comment]
Pinterest

![Pinterest-Issue-341](https://user-images.githubusercontent.com/78985665/125868617-06757c01-4ff7-4a63-9f6e-2a0caf0cfaf4.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman - 4800
