### ISSUE TITLE
Jeremy Gardner

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#342]
**Task**
Description will be "Jeremy Gardner – Building a Crypto Empire"
Due to date: 07.15.2021
We will need this for: Facebook, Instagram, Twitter, LinkedIn, Pintrest, Reddit

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
Facebook
![Facebook-#342](https://user-images.githubusercontent.com/27518021/125630986-be24e1f0-91df-41a3-89bb-2f3b3a3f7a78.jpg)
Instagram
![Instagram-#342](https://user-images.githubusercontent.com/27518021/125631037-15cec16c-8ff9-4e0d-841d-1acbe4d6c9eb.jpg)
Twitter
![twitter-#342](https://user-images.githubusercontent.com/27518021/125608544-9547c3eb-6575-47fd-9661-ef1775633428.jpg)
LinkedIn
![LinkedIn-#342](https://user-images.githubusercontent.com/27518021/125631093-1e386718-302c-46a3-b727-7e3ddac31a83.jpg)
Reddit
![Reddit-#342](https://user-images.githubusercontent.com/27518021/125631125-59757fcb-c5e3-48c3-b6eb-5a2d37cc1f51.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a
Pinterest
![Pinterest-#342](https://user-images.githubusercontent.com/27518021/125631814-03ae1330-7e39-44f6-8db9-6846b2d08808.jpg)

**Comment by Chrisha1212** [comment]
@Toledit - 4800
