### ISSUE TITLE
Crypto Story

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#343]
**Task**
The description will be "Mr. Smith – The Person You Want to Be"
Due to: 07.18.2021
We need this for: Facebook, Instagram, Twitter, Reddit, Pintrest and LinkedIn 

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by stoimenov00** [comment]
I will work on this one

**Comment by stoimenov00** [comment]
Facebook
![Facebook](https://user-images.githubusercontent.com/78659181/126427252-14269bfc-0cd8-403c-a387-737b44801426.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Twitter
![Twitter](https://user-images.githubusercontent.com/78659181/126427277-4d97fd76-2576-485c-86eb-97ee60c9dab1.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Instagram
![Instagram](https://user-images.githubusercontent.com/78659181/126426886-86396585-71f8-4ba1-bc19-413fd7f676fb.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
LinkedIn
![Pintrest](https://user-images.githubusercontent.com/78659181/126426953-c3ee2dcc-2111-4bc7-95ac-c866b4e29c42.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Pinterest
![Untitled design](https://user-images.githubusercontent.com/78659181/126427047-11c18778-1c33-45ad-84cd-bef3358b74bb.png)
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by stoimenov00** [comment]
Reddit
![image](https://user-images.githubusercontent.com/78659181/126429162-76dc2927-ef07-48ce-94c8-28192ef1262a.png)

a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by Chrisha1212** [comment]
@stoimenov00 - 4800
