### ISSUE TITLE
Crypto Advice

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#344]
**Task**
The description will be "Financial Intelligence Pays Off. Dream it. Achieve it"
Due to: 07.18.2021
We need this for: Facebook, Instagram, Twitter, Reddit, Pintrest and LinkedIn 

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Docebo-Netflix** [comment]
Reddit
![Reddit-Issue-344](https://user-images.githubusercontent.com/78985665/126032137-cc979db2-0d24-48f7-8209-5657ffd42ae9.png)

Account#
a3e779bdb64f28307177244ac2b42e209519c163cdd18c92c303a93642dcc00f

**Comment by Docebo-Netflix** [comment]
Facebook
![Facebook-Issue-344](https://user-images.githubusercontent.com/78985665/126032111-1b958eb2-65da-4ff6-a2d4-427afad9e0ba.png)

**Comment by Docebo-Netflix** [comment]
Instagram
![Instagram-Issue-344](https://user-images.githubusercontent.com/78985665/126032467-d25c7509-db4c-4a1e-9d58-b51dc263c32c.png)

**Comment by Docebo-Netflix** [comment]
LinkedIn
![LinkedIn-Issue-344](https://user-images.githubusercontent.com/78985665/126097983-73d338f6-c27f-4e3f-8939-119ce9f9e001.png)

**Comment by Docebo-Netflix** [comment]
Pinterest
![Pinterest-Issue-344](https://user-images.githubusercontent.com/78985665/126098205-1f910804-97b8-4688-9055-f59ed1e1d23a.png)

**Comment by Docebo-Netflix** [comment]
Twitter
![Twitter-Issue-344](https://user-images.githubusercontent.com/78985665/126100854-1855924a-049a-4e8d-8c01-782a4084c50c.png)

**Comment by Chrisha1212** [comment]
@SwedishFisherman - 4800
