### ISSUE TITLE
Marketing Specialist India

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#345]
**Task**
Infographic for a job opening about Marketing Specialist in India 
Here are the requirements even though I don't know if they should in the infographic, that's up to you

Responsibilities: 
- Administrative duties
- Drive traffic from social media
- Execute marketing strategy
- Create reports on marketing performance
- Work with the marketing team to manage brand and marketing initiatives
Technology Requirements:
- Gsuite
- Marketing tools
-Familiar with all social media

*We need one infographic

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Prawesh-MAGNETIC** [comment]
![Marketing Specialist India](https://user-images.githubusercontent.com/71756108/126037133-6c811147-c126-4b93-9dab-4adb44684cbb.png)




![Marketing Specialist in India](https://user-images.githubusercontent.com/71756108/126054551-6da65a4c-b669-4f63-8c4e-6260bad1c1e2.png)





A/c   No:    b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by Toledit** [comment]
![India](https://user-images.githubusercontent.com/27518021/126418630-5c9deb06-7b7e-4fae-8dd8-20dc792977a0.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Hiring Marketing Specialist India](https://user-images.githubusercontent.com/76585195/126548642-3edb1708-a742-473c-8d61-64e35e5deabb.png)

**Comment by Chrisha1212** [comment]
@Toledit - 800
