### ISSUE TITLE
Marketing Specialist Nigeria

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#346]
**Task**
Infographic for a job opening about Marketing Specialist in Nigeria
Here are the requirements even though I don't know if they should in the infographic, that's up to you

Responsibilities: 
- Administrative duties
- Drive traffic from social media
- Execute marketing strategy
- Create reports on marketing performance
- Work with the marketing team to manage brand and marketing initiatives
Technology Requirements:
- Gsuite
- Marketing tools
-Familiar with all social media

*We need one infographic

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by Toledit** [comment]
![nigeria](https://user-images.githubusercontent.com/27518021/126050795-9568cff7-348c-4e9d-a429-07b2d2c69824.jpg)
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Hiring Marketing Specialist Nigeria](https://user-images.githubusercontent.com/76585195/126548842-189fe89d-be22-4678-b2be-af5a12cc0a07.png)

**Comment by Chrisha1212** [comment]
@Toledit - 800
