### ISSUE TITLE
Project Logo for "Automated Freelancing Service"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#347]
**Task**
Create a logo for the "Automated Freelancing Service" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
![freelance64](https://user-images.githubusercontent.com/25363181/126900510-3859a8b1-bbe6-4902-a538-6e1d26f73597.png)
![freelance256](https://user-images.githubusercontent.com/25363181/126900511-e40bc366-01a1-4a8d-9d72-88edc29c4adb.png)
![freelance512](https://user-images.githubusercontent.com/25363181/126900512-b2248b94-d61a-49f3-b07c-a5f9f2f429b3.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
