### ISSUE TITLE
Project Logo for "Hierarchical deterministic (HD) Wallets for TNB"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#348]
**Task**
Create a logo for the "Hierarchical deterministic (HD) Wallets for TNB" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
![hd keys64](https://user-images.githubusercontent.com/25363181/126914686-0384c444-3efd-47f3-b0ec-40c021ea70b2.png)
![hd keys256](https://user-images.githubusercontent.com/25363181/126914688-638d115d-3cf6-4024-ad75-c510bbf8289d.png)
![hd keys512](https://user-images.githubusercontent.com/25363181/126914689-56ad08ca-8a12-4d77-a6f9-e5371ab3b046.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
