### ISSUE TITLE
Project Logo for "Kotlin Multiplatform Mobile SDK"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#349]
**Task**
Create a logo for the "Kotlin Multiplatform Mobile SDK
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
![Kotlin64](https://user-images.githubusercontent.com/25363181/126867316-5d90c44f-aea4-4f27-881c-9603575ec251.png)
![Kotlin256](https://user-images.githubusercontent.com/25363181/126867317-bd5ab29f-2b1e-4c62-86d7-2ac7735ce65c.png)
![Kotlin512](https://user-images.githubusercontent.com/25363181/126867318-5d65d256-2e14-4637-8e62-d3cb53df6d03.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
