### ISSUE TITLE
Project Logo for "TNB Discord Security"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#350]
**Task**
Create a logo for the "TNB Discord Security
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
![discord security64](https://user-images.githubusercontent.com/25363181/126882753-ef34584d-55ba-4d95-aa61-e4f6ff789559.png)
![discord security256](https://user-images.githubusercontent.com/25363181/126882754-2b39feb7-8cc3-4b8c-8b3d-15b3a2f54015.png)
![discord security512](https://user-images.githubusercontent.com/25363181/126882755-3e39ad12-9092-4c49-bed4-331df8448fea.png)


94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
