### ISSUE TITLE
Project Logo for "Restaurants Self-Order App"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#351]
**Task**
Create a logo for the "Restaurants Self-Order App
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
![restaurant64](https://user-images.githubusercontent.com/25363181/126903915-91346a3e-ba1c-4cc9-b280-1e59b807a930.png)
![restaurant256](https://user-images.githubusercontent.com/25363181/126903916-b16b3fd2-b27d-45fc-94a0-c09a47ab26ce.png)
![restaurant512](https://user-images.githubusercontent.com/25363181/126903917-e1e7566d-900c-4792-9886-93eecff9cadc.png)


94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by stweyel** [comment]
![restaurant2-64](https://user-images.githubusercontent.com/25363181/126912298-606440da-b5fa-49b7-8ebc-66c64b8c8ce6.png)
![restaurant2-256](https://user-images.githubusercontent.com/25363181/126912299-4aba0042-7689-49b5-8ecb-d57c7e8982e7.png)
![restaurant2-512](https://user-images.githubusercontent.com/25363181/126912300-87c8b227-706b-40f2-b995-ce7cb83a08da.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
