### ISSUE TITLE
Project Logo for "TNB Discord Shop"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#352]
**Task**
Create a logo for the "TNB Discord Shop
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by denistsoi** [comment]
This was already submitted to Pixel on discord. (the submitted work which is currently being used on discord).

![](https://cdn.discordapp.com/attachments/825419645259350116/852894351092613130/Untitled_Artwork.png)

Alternative verctorised deliverables were also recently submitted.


![](https://cdn.discordapp.com/attachments/825419645259350116/862010669640843304/tnb-shop-background-light.png)

![](https://cdn.discordapp.com/attachments/825419645259350116/862010670870298634/tnb-shop-transparent.png)

**Comment by denistsoi** [comment]
--- Edit

Please look at this thread in contrast to my above comment
https://github.com/thenewboston-developers/Marketing/issues/358#issuecomment-886178783
