### ISSUE TITLE
Project Logo for "TNB Heroes"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#353]
**Task**
Create a logo for the "TNB Heroes
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
![hero64](https://user-images.githubusercontent.com/25363181/126882024-a0e92eee-9da1-4663-9462-5fbb21e8edd1.png)
![hero256](https://user-images.githubusercontent.com/25363181/126882025-fd339ebe-0999-4d8e-a256-1decd14615f7.png)
![hero512](https://user-images.githubusercontent.com/25363181/126882026-f2e27ac8-11c7-4db5-bd58-7f933f988ad4.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
