### ISSUE TITLE
Project Logo for "TNB List"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#354]
**Task**
Create a logo for the "TNB List
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by shalombrain** [comment]
![Frame 14](https://user-images.githubusercontent.com/20520142/126866883-4a5a60e0-1d1e-4752-9a35-effa88b210d6.png)
![Frame 15](https://user-images.githubusercontent.com/20520142/126866886-db5811ae-ed0a-458d-814e-fda953eec048.png)
![Frame 16](https://user-images.githubusercontent.com/20520142/126866887-1610adfb-1c31-4c22-aca1-aa93b52dc285.png)

Account Number: 51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by stweyel** [comment]
![list64](https://user-images.githubusercontent.com/25363181/126917224-ebe6e518-cf03-438f-a989-32eb90a6a7c3.png)
![list256](https://user-images.githubusercontent.com/25363181/126917225-92975490-f604-4e02-84ff-8a7fdc6bab3b.png)
![list512](https://user-images.githubusercontent.com/25363181/126917226-c36f2a1f-a1dd-43dc-91ce-37bed17d498e.png)


94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by stweyel** [comment]
_like this one better..._

![list-dark64](https://user-images.githubusercontent.com/25363181/126997104-38bb3ec2-3591-434d-bff2-cca787fefb00.png)
![list-dark256](https://user-images.githubusercontent.com/25363181/126997106-7c3587c1-7912-4f19-9c5a-027091cee916.png)
![list-dark512](https://user-images.githubusercontent.com/25363181/126997109-dd7a2c82-6657-4f49-84ed-ee45bda33304.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by denistsoi** [comment]
![Logo-Alt](https://user-images.githubusercontent.com/3061779/127181070-14960aae-1628-4362-a158-1e0d6e6d209f.png)
![Logo-Dark-Alt](https://user-images.githubusercontent.com/3061779/127181148-acfbc955-7d5e-4a71-8c0d-df17be1e86cd.png)
![Logo-Dark](https://user-images.githubusercontent.com/3061779/127181181-1fb81064-75e6-4286-944a-a2da9d5c1531.png)
![Logo-Light-Alt](https://user-images.githubusercontent.com/3061779/127181219-3d23a780-2d5a-489a-a4da-ee66f1531ebb.png)
![Logo-Light](https://user-images.githubusercontent.com/3061779/127181293-71e0e150-25f3-4d84-82cb-55d72b59fe74.png)
![Logo-Transparent-Alt](https://user-images.githubusercontent.com/3061779/127181301-9abd6be5-e761-4603-b66b-0f326ceabd71.png)
![Logo-Transparent](https://user-images.githubusercontent.com/3061779/127181306-95523a62-b44f-496e-80b5-2ff7a2472d97.png)
![Logo](https://user-images.githubusercontent.com/3061779/127181324-d2e64bd6-4782-4566-9a70-c456a56a3af2.png)
