### ISSUE TITLE
Project Logo for "TNBAnon"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#355]
**Task**
Create a logo for the "TNBAnon" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by shalombrain** [comment]
![Frame 9](https://user-images.githubusercontent.com/20520142/126866446-b50dd3fb-cff6-48fe-9ec6-3390f0364baa.png)
![Frame 12](https://user-images.githubusercontent.com/20520142/126866447-165f07fe-763e-4640-881d-df84b9a40bdb.png)
![Frame 13](https://user-images.githubusercontent.com/20520142/126866448-d66c62a6-7800-4e70-afd1-2179a0996d8d.png)

Account Number: 51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by stweyel** [comment]
![Anon64](https://user-images.githubusercontent.com/25363181/126875155-103e4226-5239-4dc6-9356-ee836c3f1f4a.png)
![Anon256](https://user-images.githubusercontent.com/25363181/126875156-5e3f601a-195a-46ae-aacd-b31275ee411b.png)
![Anon512](https://user-images.githubusercontent.com/25363181/126875157-32f30e8d-16d6-4c84-a547-699b649d8b80.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
