### ISSUE TITLE
Project Logo for "TNBC Analytics"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#356]
**Task**
Create a logo for the "TNBC Analytics
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by shalombrain** [comment]
![Frame 14](https://user-images.githubusercontent.com/20520142/126866583-66392a06-ad12-4a65-ad38-27f66d0a1ed0.png)
![Frame 15](https://user-images.githubusercontent.com/20520142/126866585-bb831430-ee59-4f53-b315-a777ef5c471c.png)
![Frame 16](https://user-images.githubusercontent.com/20520142/126866587-b2c9cde1-3601-4422-b38e-754bd2cb4997.png)

Account Number: 51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by stweyel** [comment]
![analytics64](https://user-images.githubusercontent.com/25363181/126876410-007c8870-bfac-40cc-948d-0ea5c8ce02c2.png)
![analytics256](https://user-images.githubusercontent.com/25363181/126876411-c4666fd4-d129-4814-822a-a5c349070a3b.png)
![analytics512](https://user-images.githubusercontent.com/25363181/126876412-ec72a772-3226-4b86-86b2-61c97759f945.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
