### ISSUE TITLE
Project Logo for "TNBC POS"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#357]
**Task**
Create a logo for the "TNBC POS
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by shalombrain** [comment]
![Group 1](https://user-images.githubusercontent.com/20520142/126866372-77d41523-5149-43a4-bd13-2f387119baa2.png)
![Group 3](https://user-images.githubusercontent.com/20520142/126866373-7d76b73d-4fed-4016-a848-d7ec270698bb.png)
![Vector](https://user-images.githubusercontent.com/20520142/126866374-ddb17e33-cc80-47f1-a03c-cf24bda01b66.png)

Account Number: 51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by stweyel** [comment]
![tnbcpos64](https://user-images.githubusercontent.com/25363181/126868501-4f58d104-b8b8-4290-b9be-a1bb988a6e48.png)
![tnbcpos256](https://user-images.githubusercontent.com/25363181/126868503-550c18a1-8dd9-4246-b796-d0750b6039bc.png)
![tnbcpos512](https://user-images.githubusercontent.com/25363181/126868504-2949e935-e558-4795-b281-141cc8ef489a.png)


94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
