### ISSUE TITLE
Project Logo for "TNBC Treasure Hunt"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#358]
**Task**
Create a logo for the "TNBC Treasure Hunt
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
![treasure hunt64](https://user-images.githubusercontent.com/25363181/126874243-9dfe0b73-5a13-4141-a2db-4307170dfdbd.png)
![treasure hunt256](https://user-images.githubusercontent.com/25363181/126874245-785b8fa6-7712-4a60-9737-547debd11c53.png)
![treasure hunt512](https://user-images.githubusercontent.com/25363181/126874246-acd0ae68-b596-47fa-8ca4-bad5b243634d.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by Prawesh-MAGNETIC** [comment]
![TNBC Treasure Hunt](https://user-images.githubusercontent.com/71756108/126877245-0f243ad6-d55f-46c3-a4a8-cc4424adbff5.png)

🤞🏼🤞🏼🤞🏼😁

A/C No:   b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd

**Comment by denistsoi** [comment]
Sorry all - but Project owner for TNBC Treasure hunt... but this project logo isn't an open task -

**Comment by Prawesh-MAGNETIC** [comment]
> Sorry all - but Project owner for TNBC Treasure hunt... but this project logo isn't an open task -

Sure sir, acknowledged! Thank you for the information! 🙏🏼🙂

**Comment by stweyel** [comment]
> Sorry all - but Project owner for TNBC Treasure hunt... but this project logo isn't an open task -

@Chrisha1212 Could you please comment on this?!

**Comment by denistsoi** [comment]
@stweyel @Prawesh-MAGNETIC  - sorry from the time I mentioned in my comment until now

I've spoken with both @Chrisha1212 and @manishram about these tickets.

They're separate bounties from the Projects (and openly given by the government).

The Project lead can opt to use whatever was submitted but it is up to the marketing/government to decide which design is the best and submit the bounty accordingly.

i.e. this logo and whatever is used (or worked upon) is mutually exclusive

**Comment by denistsoi** [comment]
Apologises @stweyel - the team here should've mentioned that it was mutually exclusive rather than leaving it ambiguous for the Project Leads and subsequent designers on those projects to assume that our work would be undermined by these bounties.

For myself, I'm not personally looking for a logo - but this task is different - so feel free to design to your hearts content.

**Comment by stweyel** [comment]
@denistsoi No need to apologize.

@Chrisha1212  and all others... This procedure is indeed very confusing and everything but transparent (There're other occurrences as well). I've a strong feeling that we face a decent lack of (clear) communication which easily leads to careless handling of a respectful appreciation of peoples input and commitment. Which is a dangerous thing for a growing community based on exactly that! No ranting, just a notice to not loosing care...
