### ISSUE TITLE
Project Logo for "TNBGem"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#359]
**Task**
Create a logo for the "TNBGem" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by shalombrain** [comment]
![Frame 7](https://user-images.githubusercontent.com/20520142/126866058-f01c8238-0488-4af4-b41e-aade3e71c5eb.png)
![Frame 8](https://user-images.githubusercontent.com/20520142/126866060-7960bf0f-bf43-4061-be67-ed20ee7b5ac3.png)

Acoount Number: 51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by stweyel** [comment]
![gem64](https://user-images.githubusercontent.com/25363181/127566359-34ec546b-856f-4879-a31b-5d9e469f3cfd.png)
![gem256](https://user-images.githubusercontent.com/25363181/127566360-082204c7-a6f7-42c2-9d10-f63163a91fd1.png)
![gem512](https://user-images.githubusercontent.com/25363181/127566363-1bd52314-39c1-4dbf-8c51-6315e5b7634b.png)


94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by stweyel** [comment]
![gem2-64](https://user-images.githubusercontent.com/25363181/127569482-fc191ec5-94b1-4473-9132-3c4b3a176bf5.png)
![gem2-256](https://user-images.githubusercontent.com/25363181/127569484-9e147d54-e627-4b0a-9395-a15c2bb7e574.png)
![gem2-512](https://user-images.githubusercontent.com/25363181/127569486-09604658-9c80-44bc-8527-affc6e6ecfac.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
