### ISSUE TITLE
Project Logo for "aiotnb - Python network library"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#360]
**Task**
Create a logo for the "aiotnb - Python network library
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by shalombrain** [comment]
![Frame 4](https://user-images.githubusercontent.com/20520142/126865874-133a7e0f-74c3-4e17-91f3-2dc8a8a6cc0a.png)
![Frame 5](https://user-images.githubusercontent.com/20520142/126865876-96beb411-90b8-4989-ada3-9ae9f828c939.png)
![Frame 6](https://user-images.githubusercontent.com/20520142/126865877-e67b0b64-6ffc-426d-a282-6f5ff933bbd8.png)

Account Number: 51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by stweyel** [comment]
![python network64](https://user-images.githubusercontent.com/25363181/126883452-ff7eb90b-ef4f-4fa6-ab62-c7cc2e38834c.png)
![python network256](https://user-images.githubusercontent.com/25363181/126883453-b996947e-c03f-43f5-994b-924dd57bec7c.png)
![python network512](https://user-images.githubusercontent.com/25363181/126883454-2010f76d-02b7-493b-832f-76684d4c0cb3.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by denistsoi** [comment]
Hi all - this was already completed in https://github.com/AnonymousDapper/aiotnb/issues/1
(I worked closely with AnonymousDapper over 2 weeks and was submitted and completed 2 weeks ago).

--- Edit

Please look at this thread in contrast to my above comment
https://github.com/thenewboston-developers/Marketing/issues/358#issuecomment-886178783

**Comment by denistsoi** [comment]
![Transparent](https://user-images.githubusercontent.com/3061779/127145359-75a333bc-9952-4d17-a56a-090f332ac523.png)
