### ISSUE TITLE
Project Logo for "tnbGo"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#361]
**Task**
Create a logo for the "tnbGo" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by xrviv** [comment]
![Issue 361 - tnbgo](https://user-images.githubusercontent.com/44260360/126865144-003f322e-8a6d-4784-8e0c-dc617a0d511c.png)

Account number: 89e2f209951ab820aecca89e3af91093ca5e3a42387b6fa06cdf5dc30d57649e

**Comment by shalombrain** [comment]
![Frame 1](https://user-images.githubusercontent.com/20520142/126865594-29cbd794-5d1c-4da2-8762-dfb4651a3618.png)
![Frame 2](https://user-images.githubusercontent.com/20520142/126865597-cab82b81-bdc3-4e34-bb40-921f65688d20.png)
![Frame 3](https://user-images.githubusercontent.com/20520142/126865598-c2252308-c21c-41ba-a610-00c0af9a22fa.png)

Account Number: 51552a8b3b32cd3389908f8dbbb8f23856898f7953b3c27e7ab50b073d15330f

**Comment by stweyel** [comment]
![Go64](https://user-images.githubusercontent.com/25363181/126869140-b89ac582-5874-41d6-bebc-def21907a48e.png)
![Go256](https://user-images.githubusercontent.com/25363181/126869142-c1f20b8d-b67e-4fd5-bdea-46ed0ff25b13.png)
![Go512](https://user-images.githubusercontent.com/25363181/126869143-5cd64698-403e-4b9a-97fe-93b26de3906e.png)

94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
