### ISSUE TITLE
Don't be afraid to jump, we believe in you!

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#363]
**Task**
The description will be "Don't be afraid to jump, we believe in you!"
We need it for Facebook, Instagram, Twitter, LinkedIn, Pintrest and Reddit
Due Date: 07.28.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Don't be Afraid to Jump](https://user-images.githubusercontent.com/76585195/126887306-0e9a060a-08e0-4079-a9c0-23272add1098.png)
Facebook

**Comment by clarkycode** [comment]
Account No: f60f9bbc7d7f5d12209de5d97c118ab5136bb8915d4b288f7117289d890718fd

![Instagram](https://user-images.githubusercontent.com/76585195/126888221-be7f93ac-bc7f-4a45-8df8-c62d7374c785.png)
Instagram
