### ISSUE TITLE
The future is what we make it. Lets push the world in a better direction.

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#365]
**Task**
The description will be "The future is what we make it. Lets push the world in a better direction."
We need it for Facebook, Instagram, Twitter, LinkedIn, Pintrest and Reddit
Can you work on this first because we need it for the 27th Due Date: 07.26.2021

**Background**
We are an open source development community and are building our own cryptocurrency called "coins". Contributors are 
able to earn coins through a variety of ways such as fixing bugs, building apps, designing graphics, blockchain 
research, and more.

**Image Specs**
Size: 1080 x 1080px
Format: JPG or PNG

**Assets**
Feel free to use any of our assets at: https://thenewboston.com/assets

**Comment by shalombrain** [comment]
Is this open to everyone?
