### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#366]
**What**
We need a bot that gets the comments from our Facebook and Twitter posts and puts them in a spreadsheet with their: names, country (if they have specified in their in bio) and what they actually commented.

**Why**
We don't have the time to go through hundreds of comments manually 

**Deliverables**
Fully working, tested, and documented Python bot. All source code must be uploaded to GitHub.

**Comment by Aareon** [comment]
Claimed.

**Comment by YashovardhanSingh** [comment]
Is this issue still on?

**Comment by zokirmahamadjonovold** [comment]
Is it open ?
can i do this task?
i can create telegram bot what you want

**Comment by nicocrozier** [comment]
Still open i have most of it done, it just has to be run manually.

**Comment by bojan-ilijevski** [comment]
This issue is closed for now, but we will open it in the future.
