### ISSUE TITLE
Product Update

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#368]
@manishram Hey Manish, since we want to give the community an update on new project updates, lets make a post about the Woocommerce Plugin now that its all done.

Can you write out what the feature name is, what the feature is, and what the value of the feature is? After you are done with that, please assign Tristan to spice up the content using our Brand Tone. 

Feature:
What is it:
What is the value:

**Comment by manishram** [comment]
**Feature:**
TNBpay plugin for woo-commerce. 

**What is it:**
A plugin that sellers can use to quickly integrate TNBC as the payment method to their woo-commerce shop.

**What is the value:**
With this free and open-source plugin, people can make their online woo-commerce store where they can sell goods for TNBC.

**Comment by tspearing** [comment]
Feature:
A TNBC plugin for woo-commerce.

What is it:
A plugin that integrates TNBC as the payment method for online stores that use woo-commerce.

What is the value:
Online stores can sell goods for TNBC using a free plugin which takes less than 2 minutes to set up and requires no coding.

**Comment by kristykjlee** [comment]
Please credit Olowudaniel1 on instagram

**Comment by kristykjlee** [comment]
https://bit.ly/3AAvJ0z

**Comment by kristykjlee** [comment]
No transaction fees
Seeemless integration
Instant payment confirmation
Make payment wiht TNBC

**Comment by kristykjlee** [comment]
@Chrisha1212 Ready to post. Use this content below when posting.

Congratulations to @Olowudaniel1 for launching TNBpay! TNBpay is a TNBC plug-in for woo-commerce. It is plug-in that integrates TNBC as the payment method for online stores that use woo-commerce. Online stores can sell goods for TNBC using a free plugin which takes less than 2 minutes to set up and requires no coding. No transaction fees, seem-less integration, and instant payment confirmation! 

Check it out! 
https://bit.ly/3AAvJ0z

**Comment by kristykjlee** [comment]
[Woocommerce.png.zip](https://github.com/thenewboston-developers/Marketing/files/6965413/Woocommerce.png.zip)
@Chrisha1212
