### ISSUE TITLE
Code Arkive

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Marketing#369]
**Event name:** 
Code Arkive

**Post Content:**
Code Arkive host riddles and prizes for thenewboston community. Wakawaka recently won 10,000 TNB from breaking this tough riddle. Check out the riddle and stay tuned for the next riddle and prize!

**Website:**
https://codearkive.pythonanywhere.com/

**Rules:**
http://codearkive.pythonanywhere.com/rules/

**Comment by manishram** [comment]
@kristykjlee 
There should be, "Code Arkive ~host~ **hosts** riddles"

**Comment by kristykjlee** [comment]
@Chrisha1212 Use this content below when posting.


Hey guys! Niekon (from our discord community) created CodeArkive to host riddles and prizes for thenewboston community. Wakawaka recently won 10,000 TNB from breaking this tough riddle. Try solving this riddle and stay tuned for the next riddle and prize! You can view their website on our bio. Comment below if you know the answer.

**Comment by kristykjlee** [comment]
@Chrisha1212 This is a carousel post, the posts are listed numerically. 
[CodeArkive.zip](https://github.com/thenewboston-developers/Marketing/files/6965379/CodeArkive.zip)

**Comment by Chrisha1212** [comment]
> @Chrisha1212 This is a carousel post, the posts are listed numerically.
> [CodeArkive.zip](https://github.com/thenewboston-developers/Marketing/files/6965379/CodeArkive.zip)

Alright will schedule it now :)
