### ISSUE TITLE
Make a Hiring Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#374]
**Community Engagement Specialist**
We are looking for a fun, sociable individual that can engage with our community, organize events, and promote a healthy atmosphere.
**Responsibilities**

- Encourage conversations within the community.

- Brainstorm ideas on games, contests, activities, etc within the community.

- Help answer general questions for people within the community.

- Stay up to date with community discussions.

- Gather feedback from the community and create documentation on community feedback weekly.

**Requirements**

- Well-spoken, well-written

- Must be fun, chill, and dope

- Sociable

Hiring Link:
https://thenewboston.com/openings/Community/community-engagement-specialist

**Comment by Docebo-Netflix** [comment]
![Facebook, Instagram - 374](https://user-images.githubusercontent.com/78985665/129472400-cc4ca291-1467-4c86-b6f2-244bf789e6be.png)

**Comment by Docebo-Netflix** [comment]
Here are the edits

![Facebook, Instagram - 374](https://user-images.githubusercontent.com/78985665/129500821-eed2461f-c395-4805-8876-7b5b5ee17292.png)
