### ISSUE TITLE
Blog Post: Chess Tournament

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#375]
**Blog Topic**
Create a blog post about the chess tournament that will take place on this Discord server: https://discord.gg/9d3gFYeYzX and Website https://tnbcgames.com/ 

Important information that should be mentioned.

What is it? A chess tournament.

Where: Discord and the internet

When: September 20, 2021 Date of registration

Who: Everyone

Join here: https://discord.gg/9d3gFYeYzX and https://tnbcgames.com/

Registration Fee: 40 TNBC

**Prize**

- 5,000 for the first place

- 3,000 for placing second

- 2,000 for third

Mention @olowudaniel1 for more information.

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**How to submit?**
- Submit your content using this google form: https://forms.gle/ktA3siH2sycsDUSo6

**Comment by shalombrain** [comment]
Hi @Chrisha1212, I would love to take on this task.

**Comment by Chrisha1212** [comment]
> Hi @Chrisha1212, I would love to take on this task.

Take it :)

**Comment by Gstar219** [comment]
Hi 
I would love to work on this project

**Comment by markmendozadev** [comment]
sent an entry as well. :D

**Comment by Chrisha1212** [comment]
> Hi
> I would love to work on this project

Sure just  upload the docs here

**Comment by Chrisha1212** [comment]
> sent an entry as well. :D

Sure sure

**Comment by Gstar219** [comment]
> > Hi
> > I would love to work on this project
> 
> Sure just upload the docs here

https://docs.google.com/document/d/1t4vkidK41cYzvG8SSGEofXiRnuvc3GKjLem_ncmDxow/edit?usp=sharing

**Comment by Chrisha1212** [comment]
> > > Hi
> > > I would love to work on this project
> > 
> > 
> > Sure just upload the docs here
> 
> https://docs.google.com/document/d/1t4vkidK41cYzvG8SSGEofXiRnuvc3GKjLem_ncmDxow/edit?usp=sharing

requesting for acces. please

**Comment by shalombrain** [comment]
https://docs.google.com/document/d/1ry9S_1IkLjdYLrVV954wrs7nTXp5myg6-YimTX5AKTk/edit?usp=sharing @Chrisha1212

**Comment by Gstar219** [comment]
Done

**Comment by Gstar219** [comment]
> > > > Hi
> > > > I would love to work on this project
> > > 
> > > 
> > > Sure just upload the docs here
> > 
> > 
> > https://docs.google.com/document/d/1t4vkidK41cYzvG8SSGEofXiRnuvc3GKjLem_ncmDxow/edit?usp=sharing
> 
> requesting for acces. please

Done

**Comment by YashovardhanSingh** [comment]
is this done?

**Comment by Chrisha1212** [comment]
Hey guys we decided to use @Gstar219 work . Congratulatuions!

**Comment by Chrisha1212** [comment]
@Gstar219 - 1000

**Comment by Chrisha1212** [comment]
@Gstar219 please send me your account number in discord MsChrishaph#0709

**Comment by Gstar219** [comment]
> @Gstar219 please send me your account number in discord MsChrishaph#709

Okay 
Thank you

**Comment by Gstar219** [comment]
> @Gstar219 please send me your account number in discord MsChrishaph#709

07fcc17feba3ce5ff135d698cedca39e8ac697524461914354652f25e8f8da52
