### ISSUE TITLE
WordPress Blog

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Marketing#378]
1. Remove OBJ 
![image](https://user-images.githubusercontent.com/58598872/134731837-423b88d0-ce4c-4adc-8414-26f0518aa5c3.png)
2. Add an image
3. Create Game Tournament category and move the article there

The article is already posted so we need this as soon as possible 

*This is only for the WordPress dev.

**Comment by IvanDanilov66** [comment]
Done !
Acc number: f1d85cecf85d7da38401dc58fabf1aa4294c881bb9d2c47642d1b460017f06cd
