### ISSUE TITLE
Design Featured Images for Apps

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Marketing#379]
Design awesome featured images for these apps:
1. [Keysign](https://developer.thenewboston.com/projects/approved-projects/00e64bb4-37b0-453e-a778-26251818affc)
2. [TNB Faucet](https://developer.thenewboston.com/projects/approved-projects/589649fb-dfaa-4081-b04a-2e9179cf1a21)
3. [TNB Discord Bot](https://developer.thenewboston.com/projects/approved-projects/42d288db-862c-4920-be4b-56f53445b58d)
4. [HD Keygen](https://developer.thenewboston.com/projects/approved-projects/2058c70b-c5f2-404b-a377-ab767937b651)
5. [TNB Discord Shop](https://developer.thenewboston.com/projects/approved-projects/cc5c6721-a8d3-4a5d-913f-facd3fd476d0)
6. [TNBC Games](https://tnbcgames.com/)
7. [CodeArkive](https://codearkive.pythonanywhere.com/)

**Graphics should be of 1:1 ratio** (280px X 280px)

**Here are few examples:**
![Screen Shot 2021-09-27 at 12 44 36 PM](https://user-images.githubusercontent.com/68207101/134974870-a8a056e2-db32-43ec-8396-f42222a415dc.png)

**Comment by manishram** [comment]
@Toledit

**Comment by stweyel** [comment]
@manishram Is this assigned to Toledit? If not, which size is expected for the images and where will they be placed?

**Comment by manishram** [comment]
Hey @stweyel, yes this task is for Toledit. We need these graphics for: https://thenewboston.com/arcade
But we have some update to the design of this page so we need **280px X 280px** (1:1) graphics.

**Comment by Toledit** [comment]
https://github.com/thenewboston-developers/Design/issues/240#issuecomment-930482390
