### ISSUE TITLE
Create fun events for the community

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#382]
**What**
Chrisha research and come up with fun events for the community. Consider how we can distribute coins through the event as well. 

**Why**
Because its fun :) 

**Deliverables**
Come up with ideas for fun events and come up with dates on when we should start the event. As a community engagement specialist, you will be hosting the event and we can help out with creating marketing posts for it too.

**Comment by Chrisha1212** [comment]
**Halloween Event Ideas**
https://docs.google.com/document/d/1PUtKWOx3mngGUIxWlAl3GIAAuXQ2RQuN1iXmTJ5CYnE/edit

**Comment by Chrisha1212** [comment]
Can I work on this event for this year @kristykjlee ?
