### ISSUE TITLE
Bitty

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#385]
**Name of App**

- 

**App tagline**

- 

**Link to website**

- 

**Overview of app (What project lead wants people to know about the app)**

- 

**Developers name**

- 

**Developers GitHub**

- 

**Developers Discord name/ID**

- 

**Info on how to Install the App (For applications that are not websites) (Can I download it from Google Play? App Store? Where?)**

- 

**Release Date of app**

- 

**App Category**

-

**Comment by Kycermann** [comment]
Name of App: Bitty

App tagline: Bitty is the interactive multiplayer Discord story game.

Link to website: https://discord.gg/joinbitty

Overview of app (What project lead wants people to know about the app)
Join an interactive adventure: a collaborative multiplayer RPG and collectible Discord game.

Developers name: Pixel

Developers GitHub: @Kycermann

Developers Discord name/ID: Pixel#5000

Info on how to Install the App (For applications that are not websites) (Can I download it from Google Play? App Store? Where?)
Use `/bitty` in #random in the thenewboston Discord server or add Bitty to your Discord server:

https://discord.com/api/oauth2/authorize?client_id=725281406254579755&permissions=1088&scope=bot%20applications.commands

Release Date of app: December 1st 2021

App Category
Game
