### ISSUE TITLE
TNB Analytics

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#386]
**Name of App**

- TNB Analytics

**App tagline**

- Transparency To Better Economy 

**Link to website**

- http://tnbanalytics.com/

**Overview of app (What project lead wants people to know about the app)**

- TNBC Analytics is an application that represents the transparency of TNBC distribution systems. It scans the TNBC Blockchain filtered by TNB Treasury & Government public key, processes the data,  and displays it to the website. There are statistics with approximate values, charts, data tables which represent the real time transactions of TNB. There is a FAQ ( http://tnbanalytics.com/faq ) where we have more information about TNB Analytics. 

- Right now TNB Analytics is on version 1.0.17. We’re working on more functionalities and better user experience. It is fully open source and would be always open to contribute and earn TNBC. Developers can fork the project repo, do updates and make a pull request. We would verify if the update is good for the community. Then the contributor would be rewarded with TNBC.
Github repositories  are given below : 
Frontend repo : https://github.com/Techminate/TNBC-Analytics-Frontend
Backend repo : https://github.com/Techminate/TNBC-Analytics-Backend

**Developers name**

- Sazid Ahmed (Backend Dev)
- Hussu (Backend Dev) 
- Nathanael Jageni (Frontend Dev)
- Afrin Sarker (Frontend Dev)
- Ali Ar Reza (UI/UX Designer)

**Developers GitHub**

- https://github.com/SazidAhmed
- https://github.com/hussu010
- https://github.com/liefwerk
- https://github.com/afrinsarker
- https://github.com/Ali-Ar-Reza

**Developers Discord name/ID**

- SazidAhmed#8192
- hussu#9966
- liefwerk#9435
- Annie sticky#3799
- Ali Reza#1369

**Info on how to Install the App (For applications that are not websites) (Can I download it from Google Play? App Store? Where?)**

- Already released and ready to visit at http://tnbanalytics.com

**Release Date of app**

- 6 December 2021

**App Category**

- Analytical Web Application

**Comment by Toledit** [comment]
Featured graphics & screenshots design here [#2179](https://github.com/thenewboston-developers/Contributor-Payments/issues/2179) 
Or here on [google drive](https://drive.google.com/drive/folders/18pM68Bha2uksGr_6BKaGPrtMNbpxhu6K?usp=sharing)
