### ISSUE TITLE
GetMeFunky

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#387]
**Name of App**

- GetMeFunky

**App tagline**

- Get cool stuff with TNBC.

**Link to website**

- https://getmefunky.com

**Overview of app (What project lead wants people to know about the app)**

- We are building a platform where people can purchase apparel and accessories with TNBC. These include but are not limited to t-shirts, hoodies, caps, coffee mugs, etc. This project, with the help of partners, will be delivering the ordered goods to the doorstep.

**Developers name**

- Manish

**Developers GitHub**

- https://github.com/manishram

**Developers Discord name/ID**

- Manish#4379

**Info on how to Install the App (For applications that are not websites) (Can I download it from Google Play? App Store? Where?)**

- N/A

**Release Date of app**

- 7th January 2022

**App Category**

- E-commerce / Marketplace

**Comment by manishram** [comment]
<img width="375" alt="GetMeFunky" src="https://user-images.githubusercontent.com/22790904/149355776-0f9f393f-0fea-4a81-bb52-3634d6abb9df.png">
