### ISSUE TITLE
Week 3 - Facebook (Monday - Friday)

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#45]
**Monday**
Some crypto's are mined while others can be staked, which ever way,noye that they are decentralized. #crypto #digitalcurrency #cryptocurrency

**Tuesday**
TheNewBoston is on the cutting edge of crypto development. We have a system where transactions take place up to 1000 times faster than bitcoin! #crypto #digitalcurrency #cryptocurrency

**Wednesday**
Your crypto exists on a public ledger where everyone can see which public key owns which crypto. However, no one knows the identity of the person who controls the public key. #crypto #digitalcurrency #cryptocurrency

**Thursday**
Crypto transactions take place between buyers and sellers using cryptography to secure the trade. However, it isn't necessary to understand cryptography to enjoy the benefits. #crypto #digitalcurrency #cryptocurrency

**Friday**
Crypto exchanges are open all day, every day. Unlike stock exchanges, they never close. #crypto #digitalcurrency #cryptocurrency

**Comment by Toledit** [comment]
**Graphics of Facebook post for week 3** 
*don't use stuff from the iteration folder

by @Toledit: 912af796d64349e97a29d7bb63192b5f1a97d1f5d00e7bb260a9fb397a34c027

[tnb_facebook_week 3.zip](https://github.com/thenewboston-developers/Marketing/files/6001523/tnb_facebook_week.3.zip)
