### ISSUE TITLE
Blog Topic: How other countries are facilitating crypto

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#49]
**Blog Topic**
How other countries are facilitating crypto

**Blog Criteria:**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by tspearing** [comment]
[How other countries are facilitating crypto.docx](https://github.com/thenewboston-developers/Marketing/files/6072896/How.other.countries.are.facilitating.crypto.docx)

**Comment by BenCooler** [comment]
@kristykjlee 

made the edits on your post

**Comment by tspearing** [comment]
@BenCooler, where can we access the edits?

**Comment by BenCooler** [comment]
@tspearing @kristykjlee 

Sorry for the late response, here you go.
[How.other.countries.are.facilitating.crypto (edited).docx](https://github.com/thenewboston-developers/Marketing/files/6120567/How.other.countries.are.facilitating.crypto.edited.docx)
