### ISSUE TITLE
Blog Topic: Where people can go to spend or trade crypto

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#50]
**Blog Topic**
Where people can go to spend or trade crypto

**Blog Criteria:**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by Kycermann** [comment]
I'm writing the blog post about this :)

**Comment by kristykjlee** [comment]
@Kycermann Hey, are you still working on this? Or do you need me to reassign?

**Comment by Kycermann** [comment]
@kristykjlee ooh I'll submit in the next 24 hours!

**Comment by Kycermann** [comment]
https://docs.google.com/document/d/1TFxDpbNmb1wmg6710d7ix3cxar_49eHkMcnwpnc290g/edit?usp=sharing :)
Account number is f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by BenCooler** [comment]
@kristykjlee 

made the edits on your post
