### ISSUE TITLE
Week 1 - Marketing Analysis (Twitter)

### ISSUE THREAD

**Issue by jonmidas** [thenewboston-developers/Marketing#58]
https://docs.google.com/document/d/1DXcPB7O3UwAm8CO93y4pHQ--CaaWyvBdLgus1iothUk/edit?usp=sharing

**Comment by Francaolisa** [comment]
Okay, will submit the summary report today.

**Comment by Francaolisa** [comment]
I got access denied while trying to access your report that you uploaded on google docs.
