### ISSUE TITLE
Marketing Analysis Weekly Report Template

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#59]
Socail Media Account: 
Report date: [02-19-2021]
Slack Name: 
GitHub ID:

[Analytics Report/ with Image Attached]-

[Demographics and Segmentation]-

[Target Market]-

[Market Need]-

[Competition]-

[Barriers to Entry]

[Regulation]

[Hashtags]

Accomplishments this week

[Paragraph or numbered]

Goals for next week

[Goal 1]
[Goal 2]

Long term goals

[Goal 1]
[Goal 2]
Concerns

[Paragraph or numbered]

**Comment by grapelounge** [comment]
LinkedIn Marketing Report
[Marketing Analysis - LinkedIn.txt](https://github.com/thenewboston-developers/Marketing/files/6015155/Marketing.Analysis.-.LinkedIn.txt)
