### ISSUE TITLE
LinkedIn Banner

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#6]
This ticket is assigned to @SOHDA31 .

- [ ]  Design a new banner for thenewboston LinkedIn page

**Comment by kristykjlee** [comment]
hey @odetolataiwo since this is a newer repository, I wanted to call out that this is the first ticket in the Marketing repository that is ready for payment! @SOHDA31 was assigned to this ticket and now he is finished with his task. His account# is 5257c00dc543a348f3aee0c7871d7e659d4ec63b68838302f3f4da978e13c92a. Thanks!

**Comment by odetolataiwo** [comment]
done @kristykjlee
