### ISSUE TITLE
Week 1 - Weekly Report

### ISSUE THREAD

**Issue by Mathlucklala** [thenewboston-developers/Marketing#65]
- Monitored and ensures that contents shared by the designing team were all informative, catchy, and attracted some level of engagement.
- Engaged audience following us and commenting on our platforms and followed a few whose profile aligns with our vision
- Analysis shows we are making progress on our platforms, the impressions keep increasing.
- Recommend that we push for all in slack to follow our various platforms in order to increase the expected traction.
- We need to more on our Facebook and Instagram publicity while Linkedin and tweeter are increasing their engagements
- Hashtag #digitalcurreny is currently pilling more weight at the moment
- I equally shared some contents on https://www.linkedin.com/company/68632541

**Comment by Francaolisa** [comment]
Okay, will submit the summary report today.
