### ISSUE TITLE
Week 2 - Twitter (Monday-Friday)

### ISSUE THREAD

**Issue by swaiba43** [thenewboston-developers/Marketing#67]
[Twitter_Post_Week - 2_Update_.zip](https://github.com/thenewboston-developers/Marketing/files/6014617/Twitter_Post_Week.-.2_Update_.zip)

**Comment by Docebo-Netflix** [comment]
Hi Swaiba, are these edited graphics. I'm comparing these to the originals and I don't see a difference. Could you confirm?

**Comment by swaiba43** [comment]
yes.

**Comment by swaiba43** [comment]
those are all 2 week designs. I've been told to put them here now @SwedishFisherman.
