### ISSUE TITLE
Week 3 - Twitter (Monday-Friday)

### ISSUE THREAD

**Issue by swaiba43** [thenewboston-developers/Marketing#68]
[Twitter_Post_Week - 3.zip](https://github.com/thenewboston-developers/Marketing/files/6014624/Twitter_Post_Week.-.3.zip)

**Comment by Docebo-Netflix** [comment]
Hi Swaiba, again, are these edited graphics?

I'm comparing these to the originals and I don't see a difference. Could you confirm?

**Comment by swaiba43** [comment]
those are all 3 week designs. I've been told to put them here now.
