### ISSUE TITLE
Week 1 - Marketing Analysis  Report (LinkedIn)

### ISSUE THREAD

**Issue by NodeSpice** [thenewboston-developers/Marketing#70]
Marketing Analysis Attached.
[Marketing.Analysis.-.LinkedIn.txt](https://github.com/thenewboston-developers/Marketing/files/6015165/Marketing.Analysis.-.LinkedIn.txt)
![image](https://user-images.githubusercontent.com/38263524/108599289-4e237a00-735e-11eb-8708-8a99d56cb36a.png)

https://docs.google.com/document/d/1m4_Qo7g_33c9L6nEEIp2C-_NYc0ynX6tAcmjBejzIY0/edit?usp=sharing

**Comment by Francaolisa** [comment]
Okay, will submit the summary report today.
