### ISSUE TITLE
Blog Topic: Private vs Public Keys and what are cryptocurrencies anyway?

### ISSUE THREAD

**Issue by tspearing** [thenewboston-developers/Marketing#71]
Blog Topic
Private vs Public Keys and what are cryptocurrencies anyway?

Blog Criteria:

Must be 600-800 words.
Please do research to make sure the information stated is thoroughly accurate
Please make sure content is understandable to someone who knows nothing of crypto
Must be proofread by another person
Must not be copyrighted
Include read time
Include who wrote it
Include Title
Include secondary titles within article so people can see how information is chunked out

**Comment by tspearing** [comment]
[Blog Topic Private vs Public Keys and what are cryptocurrencies anyway.docx](https://github.com/thenewboston-developers/Marketing/files/6017232/Blog.Topic.Private.vs.Public.Keys.and.what.are.cryptocurrencies.anyway.docx)

**Comment by SteveHedden** [comment]
Here's my edits:
[Blog.Topic.Private.vs.Public.Keys.and.what.are.cryptocurrencies.anyway_sgh.docx](https://github.com/thenewboston-developers/Marketing/files/6032876/Blog.Topic.Private.vs.Public.Keys.and.what.are.cryptocurrencies.anyway_sgh.docx)

**Comment by tspearing** [comment]
Final version attached here:

[Blog.Topic.Private.vs.Public.Keys.and.what.are.cryptocurrencies.anyway_sgh-Final.docx](https://github.com/thenewboston-developers/Marketing/files/6037104/Blog.Topic.Private.vs.Public.Keys.and.what.are.cryptocurrencies.anyway_sgh-Final.docx)
