### ISSUE TITLE
Week 1 - Marketing Analysis weekly report (facebook)

### ISSUE THREAD

**Issue by mr9tynine** [thenewboston-developers/Marketing#72]
Socail Media Account:
Report date: [02-19-2021]
Slack Name: Mr9tynine
GitHub ID: @mr9tynine

[Analytics Report/ with Image Attached]- 

[Demographics and Segmentation]-Over 65 million potential users (Statistics according to Blockchain wallet analysis)

[Target Market]-Cryptocurrency users

[Market Need]-Regulation and visibility

[Competition]-Top 5 crypto currencies in market capitalization (Bitcoin, Ethereum, XRP, Tether, Bitcoin Cash)

[Barriers to Entry]-Coin yet to be launched.

[Regulation]

[Hashtags]-#crypto, #bitcrypto

Accomplishments this week

[Paragraph or numbered]

Goals for next week

[Goal 1]
[Goal 2]

Long term goals

[Goal 1]
[Goal 2]
Concerns

[Paragraph or numbered]

**Comment by Francaolisa** [comment]
Okay, will submit the summary report today.
