### ISSUE TITLE
week 3 meme contents (9 items)

### ISSUE THREAD

**Issue by kizzi789** [thenewboston-developers/Marketing#86]
account number: 1ddde4c124a46e71c3777eaa5fd1ba4e2e67cefa2a868ecacb95c2797ea4545c

https://drive.google.com/drive/folders/1lJj2QKCujjTwsDF5j-R0Qv9jWBDPEIGg?usp=sharing

**Comment by kizzi789** [comment]
account number: 1ddde4c124a46e71c3777eaa5fd1ba4e2e67cefa2a868ecacb95c2797ea4545c
https://drive.google.com/drive/folders/1lJj2QKCujjTwsDF5j-R0Qv9jWBDPEIGg?usp=sharing

![6](https://user-images.githubusercontent.com/78949557/109374563-6e16e880-78de-11eb-84e5-5f1c5fb7a4a6.png)
![7](https://user-images.githubusercontent.com/78949557/109374564-6eaf7f00-78de-11eb-9836-5bdbf79ddbdc.png)
![8](https://user-images.githubusercontent.com/78949557/109374565-70794280-78de-11eb-948b-873d1666de40.png)
![9](https://user-images.githubusercontent.com/78949557/109374566-7111d900-78de-11eb-9afc-732ca54cc9f7.png)





![1](https://user-images.githubusercontent.com/78949557/109374555-648d8080-78de

https://user-images.githubusercontent.com/78949557/109374559-68210780-78de-11eb-9e15-0b5a32634949.mp4
![4](https://user-images.githubusercontent.com/78949557/109374560-69eacb00-78de-11eb-9166-1c78cf5ac154.png)

https://user-images.githubusercontent.com/78949557/109374562-6bb48e80-78de-11eb-9b03-15766aafb1ab.mp4


-11eb-946d-40e48a323b52.png)
![2](https://user-images.githubusercontent.com/78949557/109374558-66efda80-78de-11eb-9213-d0b4612c94f3.png)

**Comment by Docebo-Netflix** [comment]
Hi Kizzi, in the future can you ZIP these files into one folder as well?
