### ISSUE TITLE
week 3 memes (9 items)

### ISSUE THREAD

**Issue by kizzi789** [thenewboston-developers/Marketing#87]
account number: 1ddde4c124a46e71c3777eaa5fd1ba4e2e67cefa2a868ecacb95c2797ea4545c
https://drive.google.com/drive/folders/1lJj2QKCujjTwsDF5j-R0Qv9jWBDPEIGg?usp=sharing

![1](https://user-images.githubusercontent.com/78949557/109374714-55f39900-78df-11eb-8963-17c7615dd640.png)
![2](https://user-images.githubusercontent.com/78949557/109374716-5855f300-78df-11eb-9961-f812fc2ed8f9.png)

https://user-images.githubusercontent.com/78949557/109374718-59872000-78df-11eb-90b8-666fc41aae3b.mp4
![4](https://user-images.githubusercontent.com/78949557/109374722-6146c480-78df-11eb-87c9-e7e08f2dafcd.png)

https://user-images.githubusercontent.com/78949557/109374725-6277f180-78df-11eb-9a38-3c6904e1459f.mp4

![6](https://user-images.githubusercontent.com/78949557/109374730-702d7700-78df-11eb-9e73-bbb85e2b6907.png)
![7](https://user-images.githubusercontent.com/78949557/109374731-715ea400-78df-11eb-81d8-0b5f456b4104.png)
![8](https://user-images.githubusercontent.com/78949557/109374733-73286780-78df-11eb-9567-3de77aa2b7ce.png)
![9](https://user-images.githubusercontent.com/78949557/109374734-74599480-78df-11eb-85a2-2a573ea1b181.png)

**Comment by Docebo-Netflix** [comment]
Hi Kizzi, I only count 8 memes. Can you please upload these into one folder that is Zipped so there is no confusion on how many items.
