### ISSUE TITLE
How cryptocurrency helps charities

### ISSUE THREAD

**Issue by tspearing** [thenewboston-developers/Marketing#92]
Blog Topic
How cryptocurrency helps charities

Blog Criteria:

Must be 600-800 words.
Please do research to make sure the information stated is thoroughly accurate
Please make sure content is understandable to someone who knows nothing of crypto
Must be proofread by another person
Must not be copyrighted
Include read time
Include who wrote it
Include Title
Include secondary titles within article so people can see how information is chunked out

**Comment by SOHDA31** [comment]
I gave it a try. Please give it a read and let me know if this can be used or not.
https://docs.google.com/document/d/16yDvGSSHCSd91DoK9Fc8LhgmxuJ-tYNLgcwTk1KV6G8/edit?usp=sharing

**Comment by BenCooler** [comment]
edited

[How cryptocurrency can help charities-edited.docx](https://github.com/thenewboston-developers/Marketing/files/6138570/How.cryptocurrency.can.help.charities-edited.docx)

**Comment by tawanike** [comment]
@kristykjlee Just checking if this is ready for payment? Do we only pay the author or the editor also gets paid?

**Comment by SOHDA31** [comment]
> edited
> 
> [How cryptocurrency can help charities-edited.docx](https://github.com/thenewboston-developers/Marketing/files/6138570/How.cryptocurrency.can.help.charities-edited.docx)
> 

Hey hi! Do you still need me to enable editing in the doc or the one you have edited will be alright?

**Comment by SOHDA31** [comment]
Hey so it is showing paid but I didn't receive any payment though. Just letting you know.

**Comment by kristykjlee** [comment]
@SOHDA31 Hey Sohda, the payment goes to the writer and @BenCooler was the dedicated proofreader.

**Comment by SOHDA31** [comment]
Yeah exactly I was the writer and didn't receive the payment. 🙁

**Comment by tspearing** [comment]
@SOHDA31, sorry, there was a mix up. I will send you 5000 coins. Please respond within this issue with an address.

**Comment by SOHDA31** [comment]
Oh okay @tspearing. Here -  5257c00dc543a348f3aee0c7871d7e659d4ec63b68838302f3f4da978e13c92a

**Comment by tspearing** [comment]
@SOHDA31, sent. Sorry for the delay, I haven't had much access to the internet.

**Comment by SOHDA31** [comment]
@tspearing It's okay. Thanks.
