### ISSUE TITLE
memes p.1

### ISSUE THREAD

**Issue by dashapvlv** [thenewboston-developers/Marketing#93]
![image0](https://user-images.githubusercontent.com/77531868/109411192-5a888200-79b1-11eb-9d7b-b0690258c6e9.jpg)
![image1](https://user-images.githubusercontent.com/77531868/109411194-5bb9af00-79b1-11eb-9701-75e36d6da2a3.jpg)
![image2](https://user-images.githubusercontent.com/77531868/109411196-5bb9af00-79b1-11eb-809d-311eb03f0d09.jpg)

**Comment by Chrisha1212** [comment]
@dashapvlv whats your account number?

**Comment by dashapvlv** [comment]
acc number:
468450a2e36024ac9167d6790bf51b05a2d320e44cfa1b77aa4bb05960dcb98a
