### ISSUE TITLE
Promotional Material

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Marketing#94]
**ISSUE ASSIGNED TO Fidan Stoimenov**

**Description**
Please make 1 graphic that tells people to follow all of thenewboston's social platforms. (Instagram, Facebook, Twitter, LinkedIn). We're basically going to get this post and get the community to spread the message with this graphic as well. (Acts like a digital flyer) 

**Criteria:**
Find the best standard dimensions for this post. (Choose a dimension that will be good for social platforms) 
Include social media icons in the post, no links. Links will be in the caption.
Follow the style of the facebook/instagram graphics. (White background)
Keep the look modern, clean, and professional. 
Text in the graphic should say something like "Come join and build a community and learn about cryptocurrency."
Include thenewboston logo somewhere

**Here is a link to all our social media accounts for reference:**
https://www.instagram.com/thenewboston_official/
https://www.facebook.com/TheNewBoston-464114846956315
https://www.linkedin.com/company/thenewboston-developers/?viewAsMember=true
https://twitter.com/thenewboston_og

**Comment by heykulthe** [comment]
Hey @kristykjlee , just a suggestion: It would be better if you assign issues using the Assignees option provided on the right of the issue. That helps improve the percentage in code-review and is counted as helpful.

**Comment by stoimenov00** [comment]
![fb_twitter](https://user-images.githubusercontent.com/78659181/109589669-f679d100-7b0a-11eb-8d00-7634677198b7.jpg)

**Comment by stoimenov00** [comment]
![instagram_linkedin1-01 1-01](https://user-images.githubusercontent.com/78659181/109594052-63449980-7b12-11eb-8b0b-fcf0657a4fd1.jpg)

**Comment by stoimenov00** [comment]
My Account Number
a04ee5f815bbd53b4d4d99d2bcd4a987b73ccb08b5d84477108d29283e0afd79

**Comment by kristykjlee** [comment]
@Chrisha1212 ready to publish

**Comment by Chrisha1212** [comment]
> @Chrisha1212 ready to publish

Is this for all social media? and do I have to post it as a content or cover? because I notice there's 2 size.

**Comment by stoimenov00** [comment]
Square is for Instagram and LinkedIn. Landscape is for Facebook and Twitter.
