### ISSUE TITLE
Make an Infographic Social Media Polls

### ISSUE THREAD

**Issue by oluwatomiwatemidayo** [thenewboston-developers/Marketing#99]
1) How much, if at all, have you heard or read about cryptocurrencies such as Bitcoin or ethereum?
- A lot
- Some
- Not much
- Just hearing about it

2) Do you own cryptocurrency?
- Yes
- No

3) What is your age?
- (1901 - 1926)
- (1927 - 1945)
- (1946 - 1964)
- (1965 - 1980)
- (1981 - 2000)
- (2001 - present)

4) What is your income level?
- +$100,000
- $100,000-$50,000
- $50,000-$20,000
- $20,000-$0

5) Cryptocurrency is non-government regulated which offers users more freedom. Would this increase your interest in using cryptocurrency?
- Yes 
- No

6) Unlike other currencies, cryptocurrency requires much less fees to operate. Would this increase your interest in using cryptocurency?
- Yes
- No

7) Cryptocurrency is still in its infancy stage and may undergo many changes in the near future which makes it extremely volatile. How likely will this affect your decision to use cryptocurrency?
- Most likely - 1
- 2
- 3
- 4 
- 5 - Not likely

8) How likely are you to invest in cryptocurrency this year?
- Extremely likely
- Very likely
- Somewhat likely
- Not so likely
- Not at all likely

9) In your opinion, which is more risky, investing in the stock market or investing in cryptocurrency?
- Stock market
- Cryptocurrency
- Both are equally risky

10) In 5 years, do you think cryptocurrency will be worth more or less than today?
- Significantly more
- Somewhat more
- About the same
- Somewhat less
- Significantly less

**Comment by Ayah206** [comment]
![poll4](https://user-images.githubusercontent.com/53304347/111012979-23957180-839e-11eb-97e6-7ff9902866e9.jpg)
![poll5b](https://user-images.githubusercontent.com/53304347/111012980-25f7cb80-839e-11eb-803a-1fed1ea5f36b.jpg)
![poll1](https://user-images.githubusercontent.com/53304347/111012982-2728f880-839e-11eb-9b0e-4c7b30ea9036.jpg)
![poll2](https://user-images.githubusercontent.com/53304347/111012984-28f2bc00-839e-11eb-8543-0d65f83bb863.jpg)
![poll3e](https://user-images.githubusercontent.com/53304347/111012987-2a23e900-839e-11eb-92c8-32f9dd596c66.jpg)
![poll10](https://user-images.githubusercontent.com/53304347/111012988-2abc7f80-839e-11eb-9992-106273be5e3c.jpg)
![tnbcgraphic](https://user-images.githubusercontent.com/53304347/111012990-2bedac80-839e-11eb-9d08-669d7292d5b9.jpg)
![poll7](https://user-images.githubusercontent.com/53304347/111012992-2c864300-839e-11eb-84cf-2c21764c00d0.jpg)
![poll6b](https://user-images.githubusercontent.com/53304347/111012996-2db77000-839e-11eb-9dd7-08ac87ca4267.jpg)
![poll8](https://user-images.githubusercontent.com/53304347/111012997-2e500680-839e-11eb-98fc-d8eb6a9adc76.jpg)


Account number:
9e40414427477a3b75fbf2174553b1aa548c3f4e5ff4acbb125aa26f20081821

**Comment by Chrisha1212** [comment]
This are the approved Image 
https://user-images.githubusercontent.com/53304347/111012979-23957180-839e-11eb-97e6-7ff9902866e9.jpg
https://user-images.githubusercontent.com/53304347/111012982-2728f880-839e-11eb-9b0e-4c7b30ea9036.jpg
https://user-images.githubusercontent.com/53304347/111012987-2a23e900-839e-11eb-92c8-32f9dd596c66.jpg
https://user-images.githubusercontent.com/53304347/111012988-2abc7f80-839e-11eb-9992-106273be5e3c.jpg
https://user-images.githubusercontent.com/53304347/111012990-2bedac80-839e-11eb-9d08-669d7292d5b9.jpg
https://user-images.githubusercontent.com/53304347/111012992-2c864300-839e-11eb-84cf-2c21764c00d0.jpg
https://user-images.githubusercontent.com/53304347/111012997-2e500680-839e-11eb-98fc-d8eb6a9adc76.jpg
